public/views/index/body.ejs

Signed-off-by: Henrik "HerHde" Hüttemann <mail@herh.de>

Add missing space to footer

---

.editorconfig
app.js

this should cut down on unneccessary changes ('churn')

specifying the locale jsons to be in the exact style of poeditor

---

docs/configuration-config-file.md
docs/configuration-env-vars.md
lib/config/default.js
lib/config/environment.js
lib/config/index.js
lib/web/imageRouter/lutim.js
package.json

Continuing work by @dylanderv from https://github.com/hackmdio/codimd/pull/1136

Add support for image hosting with lutim

---

package.json
public/js/extra.js

Seems like there is some XSS that was fixed by the HackMD team. It's not merged yet. But I don't expect there to appear many problems. Needs some verification and should work.

Fix stored XSS in the graphviz error message rendering

---

app.js

Signed-off-by: naimo <nicolas@aimon.fr>

fix unix socket not removed on shutdown

---

docs/setup/manual-setup.md

It was brought to our attention that the manual setup instructions had flaws. I think I fixed them.

fixing manual upgrade instructions and completing requirements

---

docs/guides/auth/keycloak.md

Admittedly a little tired today, so I doubt this is up to scratch just yet. I'd recommend spinning up an instance of Keycloak locally using the `jboss/keycloak` container, and trying to run through it that way.
I'll make this as a draft for now so that I can add screenshots and whatnot. I'd appreciate any feedback you have to offer, especially from those who haven't touched Keycloak before.

Provide documentation for configuration with Keycloak

---

.eslintrc.js
public/css/index.css
public/css/ui/toolbar.css
public/js/lib/editor/index.js
public/js/lib/editor/toolbar.html
public/vendor/showup/showup.css
webpack.common.js

Fixes #23
I'm taking care of this one since @SISheogorath said it would be a nice issue to work on.
You'll notice I've enabled support for SASS/SCSS and moved the toolbar code to an SCSS file. I saw that  the loader was already present in the webpack config, so I guessed it would be OK to use it. I think it makes our life much easier when it comes to theming, but let me know if you'd like me to fall back to standard CSS.
Still, I believe it would be worth start splitting the CSS into smaller chunks.

Fix toolbar day mode and upload button

---

README.md
public/views/index/body.ejs

fix issues #70 and #72

---

docs/guides/providing-terms.md

Add documentation for the new imprint feature

---

lib/config/environment.js
lib/web/imageRouter/s3.js

(Continuing work by @madddi from https://github.com/hackmdio/codimd/pull/1142)

make aws s3 endpoint configurable

---

lib/config/dockerSecret.js

In case #166 is correct, here is the PR to fix it.

Docker Secrets: Correct Source Path

---

docs/configuration-config-file.md
docs/configuration-env-vars.md

Replaced gravatar with libravatar (as in #153).
Extended the documentation on login methods with links to the guides etc.

Extended config.js documentation on login methods and libravatar

---

lib/realtime.js

Did about half an hour of testing before class; from what I can tell, everything still works fine!
Signed-off-by: Amolith <amolith@nixnet.xyz>

remove legacy code to solve #58

---

docs/dev/webpack.md

Improve webpack dev documentation

---

lib/web/imageRouter/lutim.js

See https://github.com/Dylanderv/node-lutim/blob/master/lib/lutim.js#L105

Fix crash in lutim integration

---

docs/setup/manual-setup.md

In particular, clarify issue with MySQL/MariaDB and therewith resolve #238 .

[DOC] Misc improvements to manual setup instructions

---

bin/heroku

Reported in our chatroom, sequelize does not like the dialect property. I took it out.

heroku complains about dialect

---

docs/guides/auth/gitlab-self-hosted.md

Update example config for gitlab authorization

Update example config for gitlab authorization

---

public/css/font.css
webpack.common.js

It should resolve #253.
It would be great if @MartB or @Techassi could try out the changes and confirm they fix their issue.

Fix font loading when useCDN is false

---

lib/web/note/util.ts

Signed-off-by: Charles Parmentier <charles.parmentier@hotmail.com>

Fixes relative path for fetching the style

---

bin/cleanup

Just fixed some whitespaces in the cleanup script to make eslint happy.

Fixed eslint errors in cleanup-script

---

public/css/ui/toolbar.css
public/js/lib/editor/index.js
public/js/lib/editor/toolbar.html
public/views/shared/help-modal.ejs

add icon to toolbar with list of diagrams

---

public/css/slide.css

Should fix codimd#308.
Not 100% sure if it may breaks other stuff or if there is a more elegant way.
Signed-off-by: Marvin Gaube <dev@marvingaube.de>

Make "transform-style: preserve-3d;" screen-only.

---

docs/configuration-config-file.md
docs/configuration-env-vars.md
lib/config/default.js
lib/config/environment.js
lib/config/hackmdEnvironment.js
lib/web/auth/oauth2/index.js

Add OIDC scopes for email & profile retrieval

---

lib/history.ts

[historyPost](https://github.com/davidmehren/codimd/blob/539d99b8352585131122424b0b6d4441cc5b4fcf/lib/history.ts#L147) already made sure we have an array

setHistory: Do not parse history into an array again

---

public/docs/features.md

This converts all links which redirect to another page to the final redirect, fixes dead links and updates all links to https.
CI failing is unrelated to this change.

Fix redirected, outdated links and convert all to https

---

lib/library-ext.d.ts
lib/models/note.ts
lib/models/revision.ts
lib/ot/editor-socketio-server.ts
lib/realtime.ts
lib/utils.ts

This PR adds type annotations in `realtime.ts`, fixes a bug in our types for connect-flash and replaces the very confusing `processData` call with the nullish coalescing operator.

More type annotations

---

package.json
public/views/codimd/foot.ejs
public/views/pretty.ejs
public/views/slide.ejs
yarn.lock

I need to use the hide today marker in the gantt view of mermaid. This is supported since 8.5.0

Update to mermaid 8.5.1

---

public/views/codimd/foot.ejs
public/views/pretty.ejs
public/views/slide.ejs

I forgot them in my mermaid update

Fix checksums of mermaid

---

.eslintignore
package.json
src/lib/config/interfaces.ts
src/lib/config/utils.ts
src/lib/history.ts
src/lib/library-ext.d.ts
src/lib/models/note.ts
src/lib/models/user.ts
src/lib/realtime.ts
src/lib/utils.ts
src/lib/web/auth/dropbox/index.ts
src/lib/web/auth/google/index.ts
src/lib/web/auth/oauth2/oauth2-custom-strategy.ts
src/lib/web/auth/utils.ts
src/lib/web/note/actions.ts
src/lib/web/note/controller.ts
src/lib/web/note/slide.ts
src/lib/web/note/util.ts
src/lib/workers/dmpWorker.ts
tsconfig.json
yarn.lock

This contains mostly more types at various places. We also excluded the migrations from eslint and fixed a bug in the note history updates

Make ESLint happy again

---

docs/setup/cloudron.md

Added a link to the demo and source code repo

Update Cloudron docs

---

src/lib/realtime.ts
src/lib/web/note/util.ts

This makes it more convenient to modify the permission model, both for
future modifications and for custom installations.
This changes the `owner` property of NoteSession to `ownerId`, which is
a more accurate description anyway.

Centralize permission checking

---

src/lib/web/statusRouter.ts

c.f. (slightly outdated, but same spirit)
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/43434#issuecomment-607181516

Fix typescript error

---

public/js/index.js
public/js/lib/common/login.js
public/js/lib/editor/index.js
public/js/locale.js
src/lib/app.ts

I've heard Chrome gets unhappy otherwise.

Port cookies changes from master branch

---

docs/dev/openapi.yml

Added serverVersion to status

---

README.md

The projects are going into completely different directions these days.
Therefore I think it's no longer appropriated to have this note
around.

Remove note about HackMD

---

README.md

To make it more obvious for people, a note in the README as recommended
by @danyork seems like a good idea.
Signed-off-by: Sheogorath <sheogorath@shivering-isles.com>

Add note about renaming

---

docs/configuration-config-file.md
src/lib/config/interfaces.ts
src/lib/models/index.ts

PR #330 implementing Issue #329 added the ldap.starttls option and passes it through
This follows up by adding the starttls option to the documentation and adding it to the Config interface.
Fixing an eslinter error and warning on the side.

#330 followup

---

locales/en.json
public/js/extra.js
public/js/locale.js
public/views/codimd/body.ejs

This PR fixes the fact that moment.js was not set to the language the user selected.
This was reported as an issue by @numero-six in #275.

[1.x] Fix: Set moment.js locale to users' locale (#275)

---

docs/dev/db-schema.plantuml
docs/dev/public_api.yml
package.json
src/api/public/me/me.controller.spec.ts
src/api/public/notes/notes.controller.spec.ts
src/api/public/notes/notes.controller.ts
src/notes/note.dto.ts
src/notes/note.entity.ts
src/notes/note.utils.ts
src/notes/notes.module.ts
src/notes/notes.service.spec.ts
src/notes/notes.service.ts
src/revisions/revision-metadata.dto.ts
src/revisions/revision.dto.ts
src/revisions/revision.entity.ts
src/revisions/revisions.module.ts
src/revisions/revisions.service.spec.ts
src/revisions/revisions.service.ts
src/users/users.service.ts
test/public-api/notes.e2e-spec.ts
yarn.lock

Implement /notes route

---

test/public-api/users.e2e-spec.ts

Note that they don't contain the functions from the services yet.

Added test functions for /me routes

---

docs/dev/public_api.yml

Fixes types of timestamps and property name

---

jest-e2e.json
package.json
test/jest-e2e.json

As advised in https://github.com/nestjs/nest/issues/3169#issuecomment-588287478

Collect coverage information for E2E tests 

---

src/monitoring/monitoring.service.ts

Source version from package.json

---

docs/dev/db-schema.plantuml
docs/dev/public_api.yml
package.json
src/api/public/me/me.controller.ts
src/api/public/media/media.controller.spec.ts
src/api/public/media/media.controller.ts
src/api/public/public-api.module.ts
src/app.module.ts
src/errors/errors.ts
src/media/backends/backend-type.enum.ts
src/media/backends/filesystem-backend.ts
src/media/media-backend.interface.ts
src/media/media-upload.entity.ts
src/media/media.module.ts
src/media/media.service.spec.ts
src/media/media.service.ts
src/media/multer-file.interface.ts
src/notes/notes.service.ts
src/users/user.entity.ts
src/users/users.service.spec.ts
src/users/users.service.ts
test/public-api/notes.e2e-spec.ts
yarn.lock

This PR adds support for uploading media. It will probably only contain support for filesystem storage, other storage backends can be added at a later time.

Implement media uploads

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/enhancement_request.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/question---other.md
.github/pull_request_template.md

Shamelessly <del>stolen</del> inspired from the react client repo.

Add templates for issues and PRs

---

CONTRIBUTING.md

Contribution documentation
This PR improves our contribution docs by adding an overview on how somebody can help the project. It also clarifies the steps required to make a PR.

Improve contribution docs

---

docs/setup/reverse-proxy.md

Documentation
This PR adds documentation for reverse-proxy setup.
#256

Add documentation for reverse-proxy use

---

.github/pull_request_template.md

changed PR Template to indicate DCO and change handling of unnecessary checkboxes.

updated PR Template

---

public/js/index.js

Frontend JS
#596 missed deleting one line, which broke the frontend :astonished:

Remove reference to nonexisting DOM element

---

.mailmap
AUTHORS

The AUTHORS file is a bit outdated. I regenerated it.

Generate new AUTHORS file

---

docs/setup/manual-setup.md
lib/config/index.js

documentation & logging
Starting with 1.7, releases include the frontend bundle.
This PR updates the docs accordingly.
Additionally, remaining mentions of `config.js` in log statements were replaced by `config.json`.

Update manual install docs & config errors

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/enhancement_request.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/question---other.md

Issue templates
This PR updates our issue templates to use the new labels

Update issue templates to use the new labels

---

docs/history.md

Fix some typos in history.md

---

docs/dev/openapi.yml
package.json
public/docs/release-notes.md

Version number
This PR improves the version number!

Release HedgeDoc 1.7.0

---

docs/setup/yunohost.md

Documentation
Add a better SVG "Install-with-yunohost" badge that works better with new GitHub dark theme

Set Install-with-yunohost bagde to SVG

---

README.md
docs/setup/kubernetes.md

docs
This PR improves the kubernetes documentation.

changed kubernetes setup doc

---

.gitignore
docs/dev/documentation.md
docs/dev/getting-started.md
docs/guides/index.md
docs/images/favicon.png
docs/images/logo.png
docs/index.md
mkdocs.requirements.txt
mkdocs.yml

docs
This PR improves the documentation by building with mkdocs.

Documentation with mkdocs

---

.github/workflows/reuse.yml

reuse workflow
This PR  fixes the branch for the reuse workflow

used correct branch for reuse workflow

---

.github/workflows/nest.js.yml
.gitignore
README.md
package.json
src/api/utils/markdownbody-decorator.ts
src/monitoring/monitoring.service.ts
src/revisions/authorship.entity.ts
test/public-api/users.e2e-spec.ts

Continous integrations
This PR adds a CI workflow for our Nest.js backend.
#654

Add CI workflow

---

renovate.json

That hopefully reduces the number of PRs

Renovate: group all packages under @nestjs

---

docs/content/guides/auth/nextcloud.md

Documentation
Fix indentation of code : https://docs.hedgedoc.org/guides/auth/nextcloud/

docs: Fix indentation of code

---

docs/content/guides/auth/github.md
docs/content/guides/auth/gitlab-self-hosted.md
docs/content/guides/auth/keycloak.md
docs/content/guides/auth/ldap-ad.md
docs/content/guides/auth/mattermost-self-hosted.md
docs/content/guides/auth/nextcloud.md
docs/content/guides/auth/saml-keycloak.md
docs/content/guides/auth/saml-onelogin.md
docs/content/guides/auth/saml.md
docs/content/guides/auth/twitter.md
docs/content/guides/minio-image-upload.md
docs/content/guides/s3-image-upload.md
docs/mkdocs.yml
docs/requirements.txt

Documentation
This PR fixes various formatting and rendering issues in the documentation.
Python's markdown renderer has a different output than GitHub, so some pages had broken formatting.

Various documentation improvements

---

yarn.lock

I updated some dependencies in preparation for the upcoming release.
Please test!

Update dependencies on `master`

---

src/config/app.config.ts
src/config/auth.config.ts
src/config/csp.config.ts
src/config/database.config.ts
src/config/hsts.config.ts
src/config/media.config.ts
src/config/utils.spec.ts
src/config/utils.ts

config
This PR improves error messages.
- Add labels to most Joi objects
- Convert all auth variable insert names to upper case to prevent inconsistent naming of the variables
- Rewrite auth errors to correctly point out the problematic variable
- Add tests for the config utils functions
fixes #743

config: Improve error messages 

---

docs/content/dev/db-schema.plantuml
src/notes/note.entity.ts

There is an inconsistency in table names.
Maybe it's better to add this description to all tables.

Make database names consistent

---

src/auth/auth.service.ts
tsconfig.json

base64url encoder
This PR fixes the base64url encoder and encodes the secret as base64url

Fix base64url transformation

---

src/config/auth.config.ts
src/config/csp.config.ts
src/config/media.config.ts
src/config/utils.ts

This PR fixes inconsistent env vars
This should make the translation from env var name to config name and vice versa more consistent.
fixes #751

config: Fix inconsistent env vars

---

docs/content/setup/getting-started.md
docs/content/theme/styles/hedgedoc-custom.css
docs/mkdocs.yml

Documentation
This PR adds a "Getting Started" Page

[Docs] Add "getting started" page

---

src/api/private/tokens/tokens.controller.ts
src/api/public/me/me.controller.ts
src/api/public/media/media.controller.ts
src/api/public/monitoring/monitoring.controller.ts
src/api/public/notes/notes.controller.ts

openapi doc
This PR resturctures the openapi spec.
For this tags are used. Each Controller get it's own tag and will be put in a separate section.
See docs.nestjs.com/openapi/operations#tags

[Docs] Add api tags to group controller

---

package.json
yarn.lock

Webpack config
This PR updates more webpack loaders to their latest versions.

More Webpack loader updates

---

.github/workflows/nest.js.yml
package.json

package.json
This PR changes `yarn format` to check the files and `yarn format:fix` to do the actually
fixing
fixes #920

Package.json: Switch yarn format and format:check

---

src/main.ts

uploads controller
This PR adds a controller for uploads.
#479

StaticServe: Fix serving images under uploads/ 

---

src/auth/auth.service.spec.ts

This PR fixes the AuthService unit test.
The unit test now uses per test mocking of the necessary functions instead of one mock in the beforeEach call.
Also some tests got expanded to cover more error cases.

Tests: Rewrote AuthService unit test

---

docs/content/dev/db-schema.plantuml
src/api/public/me/me.controller.spec.ts
src/api/public/media/media.controller.spec.ts
src/api/public/notes/notes.controller.spec.ts
src/api/public/notes/notes.controller.ts
src/api/public/public-api.module.ts
src/groups/group.entity.ts
src/history/history.service.spec.ts
src/media/media.service.spec.ts
src/notes/notes.module.ts
src/notes/notes.service.spec.ts
src/notes/notes.service.ts
src/permissions/permissions.module.ts
src/permissions/permissions.service.spec.ts
src/permissions/permissions.service.ts
src/revisions/revisions.service.spec.ts
src/users/user.entity.ts
test/public-api/notes.e2e-spec.ts

This adds permission checking for the notes route. The checking may be moved to an guard to make it cleaner.

Add Permission System

---

src/api/public/me/me.controller.spec.ts
src/api/public/media/media.controller.spec.ts
src/api/public/notes/notes.controller.spec.ts
src/api/public/notes/notes.controller.ts
src/errors/errors.ts
src/groups/group-info.dto.ts
src/groups/group.entity.ts
src/groups/groups.module.ts
src/groups/groups.service.spec.ts
src/groups/groups.service.ts
src/history/history.service.spec.ts
src/media/media.service.spec.ts
src/notes/note-permissions.dto.ts
src/notes/notes.module.ts
src/notes/notes.service.spec.ts
src/notes/notes.service.ts
src/permissions/note-group-permission.entity.ts
src/permissions/note-user-permission.entity.ts
src/permissions/permissions.service.spec.ts
src/revisions/revisions.service.spec.ts
src/revisions/revisions.service.ts
src/users/users.service.ts
src/utils/arrayDuplicatCheck.ts
test/public-api/notes.e2e-spec.ts

Note service
This PR completes the note service and adds an unit test.
fixes #542

Feature: Complete note service

---

docs/content/dev/db-schema.plantuml
src/notes/note.entity.ts
src/notes/notes.service.spec.ts
src/notes/notes.service.ts

Note: Rename viewcount to viewCount for compliance

---

src/permissions/permissions.module.ts

PermissionsModule
This PR removes some unnecessary imports

PermissionsModule: Remove unused imports

---

docs/content/dev/2.0.md

Docs: Add description for special groups

---

package.json
src/media/backends/azure-backend.ts
src/media/media.module.ts
src/media/media.service.ts
yarn.lock

media backend
This PR adds the azure media backend.
To test this the following lines should be added to the `.env` file
```
HD_MEDIA_BACKEND="azure"
HD_MEDIA_BACKEND_AZURE_CONNECTION_STRING="DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;"
HD_MEDIA_BACKEND_AZURE_CONTAINER="test"
```
this assumes that you have [Azurite](https://github.com/Azure/Azurite) running.
Before you can test anything you need to create the container in Azurite. That can be done with the [azure cli](https://docs.microsoft.com/en-us/cli/azure/install-azure-cli):
`az storage container create --name test --public-access blob --connection-string …

AzureBackend: Add Azure MediaBackend 

---

src/app.module.ts

app module
This PR adds a reminder to remove the synchronize option.
This auto creates schema on startup and is not intended for production use
See https://typeorm.io/#/connection-options/common-connection-options

AppModule: Add reminder to remove synchronize

---

docs/content/media/azure.md
docs/content/media/filesystem.md
docs/content/media/imgur.md
docs/content/media/s3.md

docs
This PR adds documentation for the media backends
- Azure
- Filesystem
- Imgur
- S3

Docs: Add Azure, Filesystem, Imgur and S3

---

src/api/public/me/me.controller.ts
src/history/history.service.spec.ts
src/history/history.service.ts
test/public-api/me.e2e-spec.ts

public api me route
This PR adds /me/history/:note to the public api.
fixes #475

PublicAPI: Add /me/history/:note 

---

docs/content/dev/public_api.yml
src/api/public/me/me.controller.spec.ts
src/api/public/me/me.controller.ts
src/media/media-upload.dto.ts
src/media/media.service.spec.ts
src/media/media.service.ts
test/public-api/me.e2e-spec.ts

Route that returns all uploads made by the authenticated user.
Public
Route that returns all uploads made by the authenticated user.
#1009

PublicAPI: Add GET /me/media

---

src/api/private/me/history/history.controller.spec.ts
src/api/private/me/history/history.controller.ts
src/api/private/private-api.module.ts
src/history/history-entry-creation.dto.ts
src/history/history.service.spec.ts
src/history/history.service.ts
test/private-api/history.e2e-spec.ts

private api
This PR adds the history route to the private api.

PrivateAPI: history

---

src/api/public/me/me.controller.ts
src/api/public/media/media.controller.ts
src/api/public/monitoring/monitoring.controller.ts
src/api/public/notes/notes.controller.ts
src/api/utils/descriptions.ts
src/groups/group-info.dto.ts
src/history/history-entry-update.dto.ts
src/history/history-entry.dto.ts
src/media/media-upload-url.dto.ts
src/media/media-upload.dto.ts
src/monitoring/monitoring.service.ts
src/monitoring/server-status.dto.ts
src/notes/note-authorship.dto.ts
src/notes/note-metadata.dto.ts
src/notes/note-permissions.dto.ts
src/notes/note.dto.ts
src/revisions/revision-metadata.dto.ts
src/revisions/revision.dto.ts
src/users/user-info.dto.ts
test/public-api/media.e2e-spec.ts
test/public-api/notes.e2e-spec.ts

apidocs
This PR improves documentation for the public api

Docs: Improve documentation for the public api

---

src/api/public/notes/notes.controller.spec.ts
src/api/public/notes/notes.controller.ts
src/media/media.service.spec.ts
src/media/media.service.ts
test/public-api/notes.e2e-spec.ts

public api
This PR adds `GET /api/v2/notes/{note}/media` to the public api

PublicApi: Add GET /api/v2/notes/{note}/media

---

test/public-api/me.e2e-spec.ts
test/public-api/notes.e2e-spec.ts

public e2e tests
This PR removes uploaded files after tests.
This way the tests can run in any order as some of the media tests rely on an empty (or non-existing) uploads directory.
Also the me e2e test was renamed to the correct name.

PublicE2E: Remove uploaded files after test

---

test/public-api/media.e2e-spec.ts

public api
This PR ports the extra tests in the POST /media test from the private apis to the public apis E2E tests.
Also the whole test suit was renamed to 'Media'.

PublicE2EMedia: Port the extra test from the private api

---

README.md

README
This PR adds a twitter badge to the README

README: Add Twitter Badge

---

CHANGELOG.md

CHANGELOG.md
This PR updates the refenrence to our changelog.
Fixes #1113

Update CHANGELOG.md to point to releases page

---

docs/content/dev/notes.md
docs/mkdocs.yml

development docs
This PR adds notes to the development docs.
fixes #864

Add dev docs about notes

---

docs/content/media/webdav.md
src/config/media.config.ts
src/media/backends/backend-type.enum.ts
src/media/backends/webdav-backend.ts
src/media/media.module.ts
src/media/media.service.ts

webdav media backend
This PR adds the webdav media backend
fixes #1041

Add WebDAV media backend

---

src/api/public/media/media.controller.ts

public api documentation
This PR makes it possible to truly upload a file with openapi documentation.
#1052

PublicAPI: Add file upload dialog to openapi docs

---

src/api/private/me/me.controller.spec.ts
src/api/private/me/me.controller.ts
src/api/private/private-api.module.ts
src/api/public/media/media.controller.ts
src/auth/auth-token.entity.ts
src/groups/group.entity.ts
src/media/media-upload.entity.ts
src/media/media.service.spec.ts
src/media/media.service.ts
src/notes/note.entity.ts
src/users/identity.entity.ts
src/users/user.entity.ts
src/users/users.service.spec.ts
src/users/users.service.ts
test/private-api/me.e2e-spec.ts

private api
This PR adds the me route to the private api.
#987

PrivateAPI: me

---

src/revisions/revisions.service.ts

revision service
This PR adds missing awaits to the service

RevisionsService: Add missing awaits

---

.github/workflows/nest.js.yml

CI
This PR adds Node.js 16 to our CI pipeline

CI: Run tests with Node.js 16 [develop]

---

README.md

README
This PR adds our logo to the README.
We have such a lovely logo we should use it on our user-facing README.

README: Replace HedgeDoc header with logo

---

src/app.module.ts
src/main.ts

private api
This PR fixes some small issues with the private api that came up while letting backend and frontend work together…
- 
the corresponding PR in the frontend https://github.com/hedgedoc/react-client/pull/1201

PrivateApi: Fix Communication between frontend and backend

---

src/api/private/notes/notes.controller.spec.ts
src/media/media.service.spec.ts

Remove superfluous overrideProvider statements

---

docs/content/dev/db-schema.plantuml
package.json
src/auth/auth.service.spec.ts
src/auth/auth.service.ts
src/notes/note.entity.ts
src/notes/notes.service.spec.ts
src/notes/notes.service.ts
test/private-api/me.e2e-spec.ts
test/private-api/notes.e2e-spec.ts
test/public-api/me.e2e-spec.ts
test/public-api/notes.e2e-spec.ts
yarn.lock

Signed-off-by: Philip Molares <philip.molares@udo.edu>### Component/Part
notes
This PR adds the publicId field to the note entity, uses it in the service and adjusts the tests accordingly.

feat(note): Add publicId field 

---

SECURITY.md

Minor adjustment, should be self-explanatory.

Fix link is SECURITY.md

---

src/auth/auth.service.spec.ts

auth tests
Add also an hour difference between createdAt and validUntil to better detect
these errors.

Fix copy paste error in auth toAuthTokenDto test

---

src/api/private/me/history/history.controller.ts
src/api/private/media/media.controller.ts
src/api/private/notes/notes.controller.ts
src/api/public/me/me.controller.ts
src/api/public/media/media.controller.ts
src/api/public/notes/notes.controller.ts
src/history/history.service.spec.ts
src/history/history.service.ts
src/media/media.service.spec.ts
src/media/media.service.ts
src/notes/get-note.pipe.ts
src/notes/notes.service.ts
src/revisions/revisions.service.ts
test/private-api/history.e2e-spec.ts
test/private-api/me.e2e-spec.ts
test/private-api/notes.e2e-spec.ts
test/public-api/me.e2e-spec.ts
test/public-api/media.e2e-spec.ts
test/public-api/notes.e2e-spec.ts

Public & private API
This pipe transforms a note ID or alias to a Note object by loading it from the database.
It also performs error associated error handling.

Introduce GetNotePipe

---

src/groups/groups.service.spec.ts
src/groups/groups.service.ts
src/groups/groups.special.ts
src/main.ts
src/permissions/permissions.service.spec.ts
src/permissions/permissions.service.ts
src/users/users.service.spec.ts
src/users/users.service.ts
src/utils/createSpecialGroups.ts

groups / bootstrap 
This PR initialises special groups on bootstrap

feat: initialise special groups on bootstrap

---

docs/content/setup/docker.md

Docs for Docker
This PR documents the changes in https://github.com/hedgedoc/container/pull/29.
https://github.com/hedgedoc/container/issues/25 and https://github.com/hedgedoc/container/pull/29

Docs: Document UPLOADS_MODE env var for Docker image

---

src/api/private/me/history/history.controller.ts
src/api/private/notes/notes.controller.ts
src/api/public/me/me.controller.ts
src/api/public/notes/notes.controller.ts
src/api/utils/get-note.pipe.ts
src/api/utils/permissions.guard.ts
src/permissions/permissions.decorator.ts
src/permissions/permissions.enum.ts
test/private-api/notes.e2e-spec.ts
test/public-api/notes.e2e-spec.ts

public and private api
This PR adds a permissions guard and refactors controller methods accordingly

Add permissions guard and refactor controller methods accordingly

---

src/api/private/me/history/history.controller.ts
src/api/private/notes/notes.controller.ts
src/api/public/me/me.controller.ts
src/api/public/notes/notes.controller.ts
src/api/utils/get-note.interceptor.ts
src/api/utils/permissions.guard.ts
src/api/utils/request-note.decorator.ts

api
This PR replaces the GetNotePipe with GetNoteInterceptor and RequestNote.

feat: get note interceptor

---

docs/content/dev/openapi.yml
docs/content/setup/docker.md
docs/content/setup/manual-setup.md
package.json
public/docs/release-notes.md

Version Number
This PR bumps the version number to 1.9.2.

Release 1.9.2

---

.github/workflows/njsscan-analysis.yml

CI
This PR adds code scanning using njsscan, which detects security issues using semgrep

CI: Setup njsscan

---

docs/content/guides/reverse-proxy.md

docs/reverse-proxy: align NC

---

src/api/private/alias/alias.controller.ts
src/api/private/auth/auth.controller.ts
src/api/private/config/config.controller.ts
src/api/private/me/me.controller.ts
src/api/private/media/media.controller.ts
src/api/private/notes/notes.controller.ts

API documentation
This PR adds missing Swagger API tags

API docs: Add missing tags

---

.eslintrc.js
package.json
test/private-api/alias.e2e-spec.ts
test/private-api/auth.e2e-spec.ts
test/private-api/history.e2e-spec.ts
test/private-api/me.e2e-spec.ts
test/private-api/media.e2e-spec.ts
test/private-api/notes.e2e-spec.ts
test/private-api/register-and-login.e2e-spec.ts
test/private-api/tokens.e2e-spec.ts
test/public-api/alias.e2e-spec.ts
test/public-api/me.e2e-spec.ts
test/public-api/media.e2e-spec.ts
test/public-api/notes.e2e-spec.ts
test/test-setup.ts

E2E tests
This PR adds more E2E tests
This is the continuation of https://github.com/hedgedoc/hedgedoc/pull/1877

E2E tests: Improve test coverage for Alias routes

---

src/auth/auth-token.dto.ts
src/history/history-entry-import.dto.ts
src/history/history-entry.dto.ts
src/media/media-upload.dto.ts
src/notes/note-metadata.dto.ts
src/notes/note-permissions.dto.ts
src/notes/note.dto.ts
src/revisions/edit.dto.ts
src/revisions/revision-metadata.dto.ts
src/revisions/revision.dto.ts

Validation/DTOs
This PR fixes/completes validation of incoming JSON by adding a few missing annotations to the DTOs.

Improve JSON validation

---

package.json
src/config/app.config.spec.ts
src/config/app.config.ts
src/config/auth.config.ts
src/config/database.config.ts
src/config/hsts.config.ts
src/config/note.config.ts
src/config/utils.spec.ts
src/config/utils.ts
yarn.lock

config validation
This PR fixes error in config validation
Fixes #2510

fix: InternalServerError on private api /config call

---

src/logger/console-logger.service.spec.ts
src/logger/console-logger.service.ts

logger
This PR adds sanitization to the logger service.

feat: sanitize logs

---

docs/content/dev/auth/ldap.md
package.json
src/api/private/auth/auth.controller.ts
src/config/auth.config.spec.ts
src/config/auth.config.ts
src/config/utils.spec.ts
src/config/utils.ts
src/frontend-config/frontend-config.service.spec.ts
src/identity/identity.module.ts
src/identity/identity.service.ts
src/identity/ldap/ldap-login.dto.ts
src/identity/ldap/ldap.strategy.ts
src/identity/local/local.strategy.ts
test/private-api/fixtures/hedgedoc.pem
test/private-api/fixtures/hedgedoc.pem.license
yarn.lock

ldap auth
This PR adds ldap auth

feat: ldap auth

---

docs/content/configuration.md
docs/content/guides/auth/nextcloud.md

docs
This PR add info boxes about unsupported CAs and node
#2414

docs: add info about unsupported CAs and node

---

docs/content/dev/getting-started.md

docs
This PR fixes some typos in the docs

docs: fix some typos

---

public/docs/features.md

The [MathJax example in Features page](https://demo.hedgedoc.org/features#MathJax):
This PR improve consistency in the MathJax example:

Improve consistency in MathJax examples.

---

src/api/private/notes/notes.controller.ts

private api
This PR adds permission routes to private api.
As this is basically a copy of the public api and there are no tests there, this PR omits them as well and leaves their creation to https://github.com/hedgedoc/hedgedoc/issues/2636.

feat: add permission routes to private api

---

src/api/private/notes/notes.controller.ts
src/api/public/notes/notes.controller.ts
src/media/media-upload.dto.ts
src/media/media.service.spec.ts
src/media/media.service.ts
src/notes/alias.entity.ts
src/notes/alias.service.ts
src/notes/note.entity.ts
src/permissions/note-group-permission.entity.ts
src/permissions/note-user-permission.entity.ts
src/permissions/permissions.service.spec.ts
src/realtime/realtime-note/realtime-note-store.service.ts
src/realtime/realtime-note/realtime-note-store.spec.ts
src/realtime/realtime-note/realtime-note.service.spec.ts
src/realtime/realtime-note/realtime-note.spec.ts
src/realtime/websocket/websocket.gateway.spec.ts
src/revisions/edit.entity.ts
src/revisions/revisions.service.spec.ts
src/users/user.entity.ts

entities
This PR replaces UUID primary keys with integers and adjusts tests accordingly.
Closes #1292

refactor: use integer primary keys

---

.env.example
docker/README.md
docs/content/config/index.md

documentation
This PR fixes the example and documents
according to cd5256da7fa01d6fa88be0dc509f946029caa053

Fix remaining HD_DATABASE_DIALECT and HD_DATABASE_STORAGE

---

src/config/media.config.spec.ts
src/config/media.config.ts

config
This PR fixes the media config.

fix(config): use correct keys in media config

---

src/api/private/notes/notes.controller.ts
src/api/utils/request-user.decorator.ts
src/history/history.service.spec.ts
src/history/history.service.ts
src/identity/session.guard.ts
test/private-api/groups.e2e-spec.ts
test/test-setup.ts

guest access
This PR adds guest access to the application.

feat: allow guests in HedgeDoc 2

---

README.md

chore: update mastodon badge (master)

---

README.md

chore: Update Mastodon badge (develop)

---

docs/content/dev/openapi.yml
docs/content/setup/docker.md
docs/content/setup/manual-setup.md
package.json
public/docs/release-notes.md
yarn.lock

Closes https://github.com/hedgedoc/hedgedoc/issues/2809

Release 1.9.6

---

.github/workflows/frontend-docker.yml
codecov.yml

Codecov + CI
This PR moves the codecov config and fixes the frontend docker workflow

Fix workflows and codecov

---

.github/workflows/backend-docker.yml
.github/workflows/backend-e2e-tests.yml
.github/workflows/backend-tests.yml
.github/workflows/frontend-docker.yml
.github/workflows/frontend-e2e-tests.yml
.github/workflows/frontend-lint.yml
.github/workflows/frontend-netlify-deploy-main.yml
.github/workflows/frontend-netlify-deploy-pr.yml
.github/workflows/frontend-test-and-build.yml
frontend/src/components/common/copyable/copy-to-clipboard-button/copy-to-clipboard-button.test.tsx
frontend/src/components/common/motd-modal/motd-modal.test.tsx
frontend/src/components/common/note-loading-boundary/create-non-existing-note-hint.test.tsx
frontend/src/components/editor-page/document-bar/aliases/aliases-add-form.test.tsx
frontend/src/components/editor-page/document-bar/aliases/aliases-list-entry.test.tsx
frontend/src/components/layout/settings-dialog/utils/on-off-button-group.test.tsx

Frontend
This PR fixes some linting errors in the frontend code

Fix frontend tests & frontend workflow

---

backend/src/realtime/realtime-note/realtime-note.ts
backend/src/realtime/realtime-note/test-utils/mock-connection.ts
backend/src/realtime/realtime-note/websocket-connection.spec.ts
backend/src/realtime/realtime-note/websocket-connection.ts
backend/src/realtime/websocket/websocket.gateway.spec.ts
backend/src/realtime/websocket/websocket.gateway.ts
backend/src/session/session.service.spec.ts
backend/src/session/session.service.ts

Realtime connection
This PR improves the realtime connection setup to allow users without session to connect.
Closes #2690

fix(realtime): Allow connections for guest users

---

frontend/cypress/e2e/history.spec.ts
frontend/src/components/common/modals/__snapshots__/common-modal.test.tsx.snap
frontend/src/components/common/modals/common-modal.test.tsx
frontend/src/components/history-page/history-card/history-card.tsx
frontend/src/components/history-page/history-table/history-table-row.tsx

Cypress Tests for History
This PR fixes the e2e tests for the history page.

fix(frontend): Fix history e2e tests

---

backend/docker/Dockerfile
backend/src/utils/serverVersion.spec.ts
backend/src/utils/serverVersion.ts
docs/content/dev/docker.md
frontend/docker/Dockerfile

Dockerfiles
This PR fixes the Dockerfiles of backend and frontend so they produce useable images.

fix(docker): fix Dockerfiles of backend and frontend

---

frontend/docker/Dockerfile

Dockerfile
This PR fixes the frontend dockerfile

fix(docker): fix workspace focus command

---

package.json
webpack.common.js
yarn.lock

Webpack
This PR adds the package clean-webpack-plugin to avoid unnecessary and broken files in the build directory to hopefully prevent undetected broken changes like described in #3335 .

feat(bundle): add webpack clean plugin

---

frontend/src/redux/note-details/reducers/build-state-from-set-note-data-from-server.test.ts

frontend tests
This PR fixes a failing test case that I introduced in #3333 by accident and that got ignored until now.
#3333

fix(tests): add license field to frontmatter

---

docs/mkdocs.yml

Docs
This PR activates the search plugin.

feat(docs): activate search plugin

---

backend/src/api/public/notes/notes.controller.ts
backend/src/auth/auth.service.spec.ts
backend/src/auth/auth.service.ts
backend/src/config/mock/customization.config.mock.ts
backend/src/config/mock/external-services.config.mock.ts
backend/src/errors/error-mapping.ts
backend/test/private-api/media.e2e-spec.ts
backend/test/private-api/tokens.e2e-spec.ts
backend/test/public-api/media.e2e-spec.ts
backend/test/public-api/notes.e2e-spec.ts
backend/test/test-setup.ts

This PR adds more end-to-end tests

Add more E2E tests

---

commons/tsconfig.json

Added declaration map in ts config

chore: added decalration map

---

renovate.json

renovate config
This PR let's renovate run each day.

ci: let renovate run every day of the week

---

frontend/src/components/editor-page/head-meta-properties/opengraph-head.tsx

Frontend HTML Head generation
This PR refactors the html head generation to reduce the number of used "\<Head>" elements.

refactor(frontend): reorganize html head elements

---

docker/.env
docker/.env.license
docker/Caddyfile
docker/docker-compose.yml
docs/content/config/index.md
docs/content/setup/getting_started.md
docs/mkdocs.yml

docs
This PR adds a recommended Docker deployment and a getting started guide.
https://github.com/hedgedoc/hedgedoc/issues/3553

docs: add getting started guide

---

commons/src/message-transporters/websocket-transporter.ts

Websocket connection
The error event of the websocket occurs if the connection is already closed. Therefore, the disconnect call does nothing and the transporter won't throw the disconnected event.

fix: use correct callback on websocket error

---

commons/src/message-transporters/websocket-transporter.ts

websocket connection
This PR improves the message transporter and forces it to throw the disconnected event if a message should be sent over a disconnected websocket.

fix: disconnect websocket if trying to send over closed connection

---

backend/src/realtime/realtime-note/realtime-user-status-adapter.ts
commons/src/message-transporters/message.ts
frontend/locales/en.json
frontend/src/components/editor-page/editor-pane/editor-pane.tsx
frontend/src/components/editor-page/editor-pane/hooks/yjs/use-send-realtime-activity.ts
frontend/src/components/editor-page/sidebar/user-line/user-line.module.scss
frontend/src/components/editor-page/sidebar/user-line/user-line.tsx
frontend/src/components/editor-page/sidebar/users-online-sidebar-menu/active-indicator.module.scss
frontend/src/components/editor-page/sidebar/users-online-sidebar-menu/active-indicator.tsx
frontend/src/components/editor-page/sidebar/users-online-sidebar-menu/own-user-line.tsx

Realtime
Realtime state activity is now synchronized using the browsers visibility api.

feat(realtime): synchronize and show realtime activity state

---

backend/src/realtime/realtime-note/realtime-note.spec.ts
backend/src/realtime/realtime-note/realtime-user-status-adapter.spec.ts
backend/src/realtime/realtime-note/test-utils/mock-connection.ts

backend realtime tests 
This PR refactors some realtime tests and utils.

improve realtime tests

---

frontend/cypress/e2e/history.spec.ts
frontend/cypress/fixtures/history-2.json
frontend/cypress/fixtures/history.json
frontend/cypress/support/visit-test-editor.ts
frontend/src/components/common/note-loading-boundary/note-loading-boundary.tsx
frontend/src/pages/api/private/notes/features/index.ts

Frontend E2E Test
This PR fixes the cypress tests

fix: correct test note in cypress environment

---

frontend/locales/en.json
frontend/src/components/editor-page/editor-pane/editor-pane.tsx
frontend/src/components/editor-page/editor-pane/hooks/codemirror-extensions/use-code-mirror-line-wrapping-extension.ts
frontend/src/components/layout/settings-dialog/editor/editor-settings-tab-content.tsx
frontend/src/components/layout/settings-dialog/editor/line-wrapping-setting-button-group.tsx
frontend/src/redux/editor/methods.ts
frontend/src/redux/editor/reducers.ts
frontend/src/redux/editor/types.ts

Editor
This PR adds a setting for line wrapping
Fixes #3506

Add setting for line wrapping

---

frontend/src/pages/api/private/notes/features/index.ts

frontend mock api
This PR fixes the features page in the mocked backend api.

fix: fix permissions in mocked feature page

---

frontend/src/components/common/copyable/copy-to-clipboard-button/copy-to-clipboard-button.spec.tsx
frontend/src/components/common/html-to-react/html-to-react.spec.tsx
frontend/src/components/markdown-renderer/extensions/bootstrap-icons/__snapshots__/bootstrap-icon-markdown-extension.spec.tsx.snap
frontend/src/components/markdown-renderer/extensions/bootstrap-icons/bootstrap-icon-markdown-extension.spec.tsx
frontend/src/components/markdown-renderer/markdown-to-react/__snapshots__/markdown-to-react.spec.tsx.snap
frontend/src/components/markdown-renderer/markdown-to-react/markdown-to-react.spec.tsx
frontend/src/components/markdown-renderer/markdown-to-react/test-utils/test-markdown-renderer-extension.ts
frontend/src/components/markdown-renderer/markdown-to-react/test-utils/test-node-processor.ts
frontend/src/components/markdown-renderer/markdown-to-react/test-utils/test-replacer.tsx
frontend/src/extensions/extra-integrations/blockquote/__snapshots__/blockquote-extra-tag-markdown-extension.spec.tsx.snap
frontend/src/extensions/extra-integrations/blockquote/blockquote-extra-tag-markdown-extension.spec.tsx
frontend/src/extensions/extra-integrations/katex/__snapshots__/katex-frame.spec.tsx.snap
frontend/src/extensions/extra-integrations/katex/__snapshots__/katex-markdown-extension.spec.tsx.snap
frontend/src/extensions/extra-integrations/katex/katex-frame.spec.tsx
frontend/src/extensions/extra-integrations/katex/katex-frame.tsx
frontend/src/extensions/extra-integrations/katex/katex-markdown-extension.spec.tsx

Frontend
This PR fixes several minor issues in unit tests.

Fix frontend tests

---

backend/src/permissions/permissions.service.spec.ts

Fixes [3706](https://github.com/hedgedoc/hedgedoc/issues/3706)
[3706](https://github.com/hedgedoc/hedgedoc/issues/3706)

refactor: create mock function for noteRepo and eventemiter

---

frontend/locales/en.json
frontend/src/components/landing-layout/footer/version-info/version-info-modal.tsx

Frontend
This PR improves the design of version info modal

Update design for version info modal

---

frontend/src/components/editor-page/editor-pane/hooks/yjs/use-realtime-connection.ts

Websocket connection
This PR changes the reconnect behaviour by increasing the timeout with every try

feat(frontend): increase reconnect timeout with every try

---

backend/src/api/private/media/media.controller.ts
backend/src/api/public/media/media.controller.ts
backend/src/api/public/notes/notes.controller.ts
backend/src/api/utils/get-note.interceptor.ts
backend/src/api/utils/note-header.interceptor.ts
backend/src/api/utils/permissions.guard.ts
backend/src/api/utils/request-note.decorator.ts
backend/src/api/utils/request-user.decorator.ts
backend/src/api/utils/request.type.ts
backend/src/api/utils/session-authprovider.decorator.ts
backend/src/auth/mock-auth.guard.ts
backend/src/identity/session.guard.ts
backend/src/media/media-upload.dto.ts
backend/src/media/media-upload.entity.ts
backend/src/media/media.service.ts
backend/src/permissions/permissions.service.spec.ts
backend/src/permissions/permissions.service.ts
backend/test/private-api/media.e2e-spec.ts
backend/test/public-api/media.e2e-spec.ts

Guests can now upload media to a note if they have write access to it.

Guests can upload media!

---

frontend/src/components/common/new-note-button/new-note-button.tsx
frontend/src/extensions/external-lib-app-extensions/graphviz/graphviz-frame.tsx

Frontend
This PR cleans up some frontend code by removing redundant code.

Clean up some frontend effects

---

.github/workflows/e2e-tests.yml

CI
This PR updates the cypress browsers docker image in the e2e workflow

deps(ci): update cypress browsers docker image

---

backend/src/auth/auth.service.spec.ts
backend/src/auth/auth.service.ts

Backend
This PR increases the test coverage for auth.service.ts

increased test coverage for auth.service

---

frontend/src/components/editor-page/editor-pane/hooks/yjs/use-send-realtime-activity.ts

Frontend
Remove a memory leak in the realtime code

fix(frontend): fix event emitter leak in realtime status

---

docs/content/dev/setup/frontend.md

Documentation
This PR adds production logging documentation to frontend.md file
- [] This PR targets the correct branch: `master` for 1.x & docs, `develop` for 2.x
https://github.com/hedgedoc/hedgedoc/issues/4335

Added documentation to enable production logging

---

backend/src/realtime/realtime-note/realtime-note.spec.ts
backend/src/realtime/realtime-note/realtime-user-status-adapter.spec.ts
backend/src/realtime/realtime-note/test-utils/mock-connection.ts
backend/src/realtime/realtime-note/test-utils/mock-message-transporter.ts
backend/src/realtime/websocket/websocket.gateway.ts
commons/src/message-transporters/message-transporter.ts
commons/src/y-doc-sync/y-doc-sync-adapter.spec.ts
commons/src/y-doc-sync/y-doc-sync-adapter.ts
frontend/src/components/editor-page/editor-pane/editor-pane.tsx

Communication
This PR fixes race conditions in the realtime communication..

Race condition hunt

---

turbo.json

Turbo tasks
This PR adds a missing dependency to the turbo task for "test".

chore(turbo): add dependency tasks test

---

docs/.markdownlint.json
docs/.markdownlint.json.license
docs/content/config/index.md
docs/content/config/media/azure.md
docs/content/config/media/filesystem.md
docs/content/config/media/imgur.md
docs/content/config/media/s3.md
docs/content/config/media/webdav.md
docs/content/dev/auth/ldap.md
docs/content/dev/design_docs/api_auth.md
docs/content/dev/design_docs/config.md
docs/content/dev/design_docs/events.md
docs/content/dev/design_docs/notes.md
docs/content/dev/design_docs/user_profiles.md
docs/content/dev/dev_notes.md
docs/content/dev/docker.md
docs/content/dev/documentation.md
docs/content/dev/getting-started.md
docs/content/dev/setup/frontend.md
docs/content/index.md
docs/content/interface/toolbar.md
docs/content/references/hfm.md
docs/content/setup/getting_started.md
docs/package.json
docs/package.json.license
package.json
turbo.json
yarn.lock

ci
This PR adds a new worklfow to lint markdown files in docs/content

ci: add workflow to lint documentation

---

backend/.eslintrc.js
backend/package.json
backend/src/auth/auth-token.dto.ts
backend/src/auth/auth.module.ts
backend/src/frontend-config/frontend-config.dto.ts
backend/src/history/history-entry.dto.ts
backend/src/identity/identity.module.ts
backend/src/identity/local/login.dto.ts
backend/src/identity/local/register.dto.ts
backend/src/media/media-upload.dto.ts
backend/src/monitoring/server-status.dto.ts
backend/src/notes/note-metadata.dto.ts
backend/src/notes/note-permissions.dto.ts
backend/src/notes/note.dto.ts
backend/src/revisions/edit.dto.ts
backend/src/revisions/revision-metadata.dto.ts
backend/src/revisions/revision.dto.ts
backend/src/users/user-info.dto.ts
yarn.lock

Signed-off-by: David Mehren <git@herrmehren.de>### Component/Part
This PR configures https://github.com/darraghoriordan/eslint-plugin-nestjs-typed to add some NextJS linting rules

build(backend): add nestjs-typed eslint plugin

---

frontend/cypress/e2e/revision.spec.ts
frontend/locales/en.json
frontend/src/components/editor-page/sidebar/specific-sidebar-entries/revisions-sidebar-entry/revision-sidebar-entry.tsx
frontend/src/components/editor-page/sidebar/specific-sidebar-entries/revisions-sidebar-entry/revisions-modal/delete-revision-modal.tsx
frontend/src/components/editor-page/sidebar/specific-sidebar-entries/revisions-sidebar-entry/revisions-modal/revision-list.tsx
frontend/src/components/editor-page/sidebar/specific-sidebar-entries/revisions-sidebar-entry/revisions-modal/revision-modal-body.tsx
frontend/src/components/editor-page/sidebar/specific-sidebar-entries/revisions-sidebar-entry/revisions-modal/revision-modal-footer.tsx
frontend/src/components/editor-page/sidebar/specific-sidebar-entries/revisions-sidebar-entry/revisions-modal/revision-modal.tsx

feat(frontend): delete revision

---

.github/workflows/e2e-tests.yml
.github/workflows/test-and-build.yml
frontend/package.json

CI
This PR adds coverage for the frontend tests
Works on #2945

ci: add coverage for the frontend

---

backend/docker/Dockerfile

Backend => Docker
This PR fixes the docker image of the backend by fixing a copy instruction.

fix(backend): fix target directory of dist directory

---

backend/CHANGELOG.md
backend/src/config/auth.config.ts
backend/src/config/mock/auth.config.mock.ts
backend/src/frontend-config/frontend-config.dto.ts
backend/src/frontend-config/frontend-config.service.spec.ts
backend/src/frontend-config/frontend-config.service.ts
backend/src/identity/identity.entity.ts
backend/src/identity/provider-type.enum.ts
docs/content/concepts/api-auth.md
docs/content/theme/styles/hedgedoc-custom.css
frontend/cypress/support/config.ts
frontend/src/api/config/types.ts
frontend/src/components/login-page/one-click/get-one-click-provider-metadata.ts
frontend/src/components/login-page/one-click/via-one-click.module.scss
frontend/src/pages/api/private/config.ts

login
This PR removes the twitter login

remove dropbox, facebook & twitter login

---

backend/src/config/auth.config.ts
backend/src/config/utils.spec.ts
backend/src/config/utils.ts

config
This PR adds checks to ensure auth names contain no duplicates.

fix: check if auth names contain duplicates

---

frontend/locales/en.json
frontend/src/components/editor-page/editor-pane/tool-bar/tool-bar.module.scss
frontend/src/components/editor-page/editor-pane/tool-bar/tool-bar.tsx
frontend/src/components/editor-page/sidebar/specific-sidebar-entries/delete-note-sidebar-entry/delete-note-sidebar-entry.tsx
frontend/src/components/history-page/history-toolbar/history-toolbar.tsx
frontend/src/components/layout/app-bar/base-app-bar.tsx

interface
This PR fixes sveral things. See single commits.
fixes https://github.com/hedgedoc/hedgedoc/issues/5036
fixes https://github.com/hedgedoc/hedgedoc/issues/5027

Misc fixes for 2.0

---

backend/src/api/private/auth/auth.controller.ts
backend/src/api/public/me/me.controller.ts
backend/src/api/public/monitoring/monitoring.controller.ts
backend/src/app.module.ts
backend/src/config/auth.config.ts
backend/src/config/gitlab.enum.ts
backend/src/frontend-config/frontend-config.service.spec.ts
backend/src/identity/identity.service.ts
backend/src/logger/console-logger.service.ts
backend/src/media/media-upload.dto.ts
backend/src/monitoring/monitoring.service.ts
backend/src/realtime/websocket/websocket.gateway.ts
backend/src/users/users.service.ts
backend/test/app.e2e-spec.ts
backend/test/public-api/me.e2e-spec.ts
frontend/cypress/e2e/linkEmbedder.spec.ts
frontend/src/api/common/api-response.ts
frontend/src/api/notes/index.ts
frontend/src/app/(editor)/n/[noteId]/page.tsx
frontend/src/components/document-read-only-page/document-infobar.tsx
frontend/src/components/document-read-only-page/document-read-only-page-content.tsx
frontend/src/components/editor-page/sidebar/sidebar.tsx
frontend/src/components/editor-page/sidebar/specific-sidebar-entries/export-menu-sidebar-menu.tsx
frontend/src/components/editor-page/sidebar/specific-sidebar-entries/import-menu-sidebar-menu.tsx
frontend/src/components/editor-page/sidebar/specific-sidebar-entries/revisions-sidebar-entry/revisions-modal/revision-modal-footer.tsx
frontend/src/components/history-page/entry-menu/entry-menu.tsx
frontend/src/components/history-page/history-toolbar/import-history-button.tsx
frontend/src/components/render-page/renderers/document/width-based-table-of-contents.tsx
frontend/src/extensions/essential-app-extensions/fork-awesome-html-tag/fork-awesome-html-tag-app-extension.ts

Some TODOs are outdated so they going to be updated or removed.

Remove fixed todos

---

backend/package.json
backend/src/app.module.ts
backend/src/migrations/mariadb-1696756465867-init.ts
backend/src/migrations/postgres-1696756465867-init.ts
backend/src/migrations/sqlite-1696756465867-init.ts
backend/src/ormconfig.ts
backend/src/utils/detectTsNode.ts
backend/test/test-setup.ts

database
This PR adds the initial migration and general migration infrastructure

feat: add initial database migration

---

backend/docker/Dockerfile
frontend/docker/Dockerfile

CI
This PR fixes/adds/improves/...

fic(ci): add git to build containers

---

package.json

chore: set version to 2.0.0-alpha.1

---

.mailmap
AUTHORS

authors file
This PR updates the authors file
none

chore: update authors file

---

frontend/src/components/application-loader/initializers/index.ts
frontend/src/components/common/renderer-iframe/hooks/use-force-render-page-url-on-iframe-load-callback.ts
frontend/src/redux/history/methods.ts

Iframe
This PR removes the test mode condition from the iframe.
Some browsers don't trigger the event correctly.
fixes #5076 #5077

Add iframe load trigger

---

docs/content/tutorials/setup.md
docs/mkdocs.yml

docs
This PR adds a notice about using custom ports.

Docs title + info about ports

---

frontend/src/app/(editor)/new/page.tsx

/new page
This PR fixes the conditional rendering on the /new page
Fixes #5137

fix(newPage): replace show if with inline condition

---

docs/content/guides/auth/azure-ad.md

docs
This PR fixes the docs for azure active directory
#5249

docs: fix azure active directory docs

---

backend/src/history/history.service.spec.ts

History test
This PR fixes linting error
These errors were probably introduced because the PR was open so long

lint: fix error in new test

---

public/js/extra.js

Fixes https://github.com/hedgedoc/hedgedoc/issues/2344

fix: anchor links

---

backend/docker/Dockerfile
frontend/docker/Dockerfile

PR #4368 moved the location of the `docker.md` file. This PR adjusts sources to changes.

fix(docker): update docker documentation reference

---

backend/package.json
docs/content/files/setup-docker/docker-compose.yml
docs/content/how-to/reverse-proxy.md
docs/package.json
frontend/package.json
package.json

release 
This PR makes last minute changes for the release of alpha 3.

Alpha 3 Release

---

backend/src/identity/oidc/oidc.service.ts

SSO OIDC
This PR adds a regular re-fetching of the OIDC well-known discovery documents
fixes #5793

enhancement(oidc): refetch discovery documents regularly

---

html-to-react/src/utils/convertInlineStyleToMap.spec.ts

html-to-react
This PR adds additional test for convertInlineStyleToMap

test: add additional tests for convertInlineStyleToMap

---

AUTHORS
docs/content/dev/openapi.yml
docs/content/setup/docker.md
docs/content/setup/manual-setup.md
package.json
public/docs/release-notes.md

Release 1.10.1
This PR prepares the 1.10.1 release.

Release 1.10.1

---

docs/content/dev/release_checklist.md
docs/mkdocs.yml

docs
This PR adds a release checklist

docs: add release_checklist.md

---

app.js
docs/content/dev/openapi.yml
docs/content/setup/docker.md
docs/content/setup/manual-setup.md
lib/config/index.js
lib/csp.js
package.json
public/css/extra.css
public/docs/features.md
public/docs/release-notes.md
public/js/extra.js
public/js/htmlExport.js
yarn.lock

HedgeDoc
This PR does all release preparations

Release 1.10.3
