hedgedoc/hedgedoc

- public/views/index/body.ejs
@cvladan gave a hint about some minor problems with the capitalization 
of language names.
This patch should fix most of them. and removes some "language" prefix 
and suffixes which are not needed to make clear what people are 
selecting here.
[1]: https://github.com/cvladan
previously: https://github.com/hackmdio/codimd/pull/1180
> Fix capital letters in language selection

- lib/letter-avatars.js
- test/letter-avatars.js
Since libravatar got a default fallback to Gravatar and in generell
allows federated image hosting for avatars this shouldn't break any
existing implementations.
The federation functionality is not added yet. This would require to use
the libravatar library.
Details:
https://wiki.libravatar.org/api/
Previously: https://github.com/hackmdio/codimd/pull/1171
> Use libravatar as drop-in replacement for gravatar

- app.json
- bin/heroku
- package.json
this removes the general `postinstall` call to `bin/heroku` and instead puts it into a heroku-prebuild hook. At the same time, env vars get updated to use the `CMD` prefix. The configured buildpacks were not used. Finally, npm run build is now automatically done by Heroku.
> cleanup of the heroku configuration

- LICENSE
It seems like the license was never correctly filled.
This patch updates the LICENSE file to represent members of the 
community and major code contributors.
> Fix LICENSE content

- public/js/index.js
- public/js/lib/editor/index.js
- public/js/lib/editor/toolbar.html
- public/js/lib/editor/ui-elements.js
- public/views/codimd/header.ejs
Currently we have the odd situation to have two toolbars. One inside the
header and one in the editor.
Since we only show the image upload button when the editor is visible we
should move the upload button into the editor toolbar.
This patch does this by adding the image upload button besides the image
tag button.
Preview:
Previously: https://github.com/hackmdio/codimd/pull/1181
> Move upload button into toolbar

- lib/response.js
Add "both" mode to URLs because I assume most people want to straight away see the code when they click the "edit" button in a published note.
Fixes https://github.com/codimd/server/issues/27
Not tested, followed instructions from @ccoenen , please do review! :)
> change default mode to "both" when clicking edit

- lib/web/imageRouter/minio.js
Continuing work by @Thor77 from https://github.com/hackmdio/codimd/pull/1095
---
With the current state this behaviour is enabled by default and can be disabled by setting
```json
{
"minio": {
"hideDefaultPorts": false
}
}
```
or `CMD_MINIO_HIDE_DEFAULT_PORTS=false`.
> Hide port minio

- config.json.example
- docs/configuration-env-vars.md
- lib/config/default.js
- lib/config/environment.js
- lib/config/hackmdEnvironment.js
- lib/web/auth/saml/index.js
(Continuing work by @nopap from https://github.com/hackmdio/codimd/pull/1097)
disableRequestedAuthnContext: true|false
By default only Password authmethod is accepted, this option allows any other method.
Issue and option described here:
https://github.com/bergie/passport-saml/issues/226
> Added a configuration option for passport-saml:

- package.json
A few days ago the dependency was removed from npm. this causes various
setups to fail and blocks deployments and development.
This patch should fix the dependency and allow CodiMD to move forward.
Fixes #39
> Fix broken dependency js-sequence-diagrams

- .travis.yml
- package.json
Snyk informed us about possible vulnerabilities in meta-marked. It seems
like at least some of them were already [address by HackMD around a year
ago](https://github.com/hackmdio/meta-marked/commit/8b0cf4ce1d0997599c4d2355a281a201a172176d) but never pushed upstream to CodiMD.
This patch provides a fix by using an up-to-date dependency from our own
repository with CI integration.
Details: https://app.snyk.io/vuln/SNYK-JS-JSYAML-174129
> Update meta-marked to fix possible vulnerabilities

- locales/en.json
- public/views/shared/help-modal.ejs
We have a community forum and want to use it for users support and to
bring developers and end-users together. In order to achieve this, it
would be helpful to inform users about its existence.
This patch adds the community forum as resource to the help section and
aligns it along the Matrix channel and GitHub issue tracker.
Here a preview of a new contact section:
> Add community forum to help section

- package.json
- public/js/history.js
- public/js/index.js
- public/views/index/foot.ejs
- webpack.common.js
js-url is outdated and wurl is it's successor. This will fix some possible
vulnerabilities in the dependencies and also optimize the build process 
by removing the external library toward internal tooling.
> Replace js-url with wurl

- docs/setup/docker.md
The docker setup instructions, on the `git clone` step, are missing the name of the directory to clone into that is used in the next step: `cd codimd-container`.
> Add name of directory to clone into

- public/css/extra.css
When people link a section or use the ToC to scroll to it upwards, it
happens that those become hidden behind the navbar.
This patch adds a little hack from StackOverflow[1] in order to fix this
problem. By adding a pseudo element in front of any field that contains
an id, it's possible to add the needed space.
There was no negative impact found except of marking around the header
areas in the rendered view requires a bit preciser work. This needs some
more detailed testing.
[1]: https://stackoverflow.com/a/24298427
Fixes #76
> Fix hidden header on link

- docs/configuration-config-file.md
- docs/configuration-env-vars.md
- lib/config/default.js
- lib/config/environment.js
- lib/web/middleware/tooBusy.js
With very low CPU frequency or bad IO situation, as well as not-loaded
JS CodiMD happens to present unneeded "I'm busy"-messages to users.
This patch allows to configure the lag. The default is taken from the
library but set in our own default configs.
Previously: https://github.com/hackmdio/codimd/pull/1078
> Add config for toobusy middleware

- lib/models/user.js
Currently a problem appears when using OpenID for authentication as
there is no method to add a profile picture right now.
This patch makes sure that all undefined login methods get a profile
picture.
Fixes #36
> Fix missing pictures for OpenID

- public/css/index.css
As it may happens that the codemirror content flows underneath the
status bar, this patch should help to avoid it. It adds the size of the
status bar as margin-bottom so the codemirror window itself is forced
above the statusbar.
Fixes #80
> Fix CodeMirror toolbar hiding content

- public/css/slide-preview.css
- public/js/index.js
As per #79: 
- improved the styling of lists, tables and headings for slides previews.
- made the background of slides preview black, regardless of the day/night mode
Signed-off-by: Toma Tasovac <ttasovac@humanistika.org>
> fixed styling of slides preview

- lib/history.js
- lib/models/revision.js
- lib/realtime.js
- lib/web/auth/ldap/index.js
- lib/web/auth/openid/index.js
- lib/web/auth/saml/index.js
- lib/web/auth/utils.js
- lib/web/imageRouter/azure.js
- lib/web/imageRouter/filesystem.js
- lib/web/imageRouter/imgur.js
- lib/web/imageRouter/index.js
- lib/web/imageRouter/lutim.js
- lib/web/imageRouter/s3.js
- lib/web/statusRouter.js
- lib/workers/dmpWorker.js
We have various places with overly simple if statements that could be
handled by our logging library. Also a lot of those logs are not marked
as debug logs but as info logs, which can cause confusion during
debugging.
This patch removed unneeded if clauses around debug logging statements,
reworks debug log messages towards ECMA templates and add some new
logging statements which might be helpful in order to debug things like
image uploads.
> Rework debug logging

- README.md
- docs/setup/docker-linuxserver.md
- docs/setup/docker.md
As requested by @SISheogorath [here](https://github.com/linuxserver/docker-codimd/issues/4#issue-454332233) and further to discussion about previous PR [here.](https://github.com/codimd/server/pull/110#issuecomment-501214087)
Signed-off-by: chbmb <chbmb@linuxserver.io>
> Add docker image from LinuxServer.io as an install option.

- lib/utils.js
Add simple SVG image detecetion base on the file extension .svg.
This fixes the SVG being delivered as binary/octet-stream and makes it possible to embedd the SVG.
> Add SVG image detection based on file extension

- lib/config/dockerSecret.js
Adds a possibility to read the db URL from a file, that could e.g. be provided by a [Docker secret].(https://docs.docker.com/engine/swarm/secrets/).
See https://github.com/codimd/container/pull/36 too.
> DB URL: Secret File Support

- lib/response.js
- public/views/pretty.ejs
- public/views/shared/ga.ejs
- public/views/slide.ejs
Do Not Track (DNT) is an old web standard in order to notify pages that
the user doesn't want to be tracked. Even while a lot of pages either
ignore this header or even worse, use it for tracking purposes, the
orignal intention of this header is good and should be adopted.
This patch implements a respect of the DNT header by no longer including
the optional Google Analytics and disqus integrations when sending a DNT
header. This should reduce outside resource usage and help to stay more
private.
This should later-on extended towards other document content (i.e.
iframe based content).
The reason to not change the CDN handling is that CDNs will be
deprecated with next release and removed in long term.
> Respect DNT header

- README.md
- docs/setup/docker-linuxserver.md
The current documents might end up confusing people and are not
completely accessible. This minor fixes should clear up the situation
and add alt texts to all badges, explain the links at the end of the
docs, and list LinuxServer.io in the supported provider section of the
README.
Some reasoning on the change in the listing:
Since we maintain an own container image which is for sure kept updated
on release, this is our first listing, as well as general solutions that
are build on that image, like the K8s integration.
The next listings are integrated provides which allow self-hosting, like
Cloudron and I also consider LinuxServer.io as this kind of providers.
Which try to enable people to run CodiMD on their own hardware or rented
servers in a very easy way, but by using their own images. …
> Fix some minor quirks in the LinuxServer.io docs

- README.md
I just noticed that shields.io provides some nice new badges including
one explicitly for Matrix and one for Mastodon. Since those are really
our platforms, let's get them into our README. Just a cosmetic change.
> Update badge icons

- lib/migrations/20171009121200-longtext-for-mysql.js
- lib/migrations/20180209120907-longtext-of-authorship.js
- lib/migrations/20180306150303-fix-enum.js
fixes #126 and https://github.com/hackmdio/codimd/issues/1197
```
ERROR: Migration 20171009121200-longtext-for-mysql.js (or wrapper) didn't return a promise
ERROR: Migration 20180209120907-longtext-of-authorship.js (or wrapper) didn't return a promise
ERROR: Migration 20180306150303-fix-enum.js (or wrapper) didn't return a promise
```
same like https://github.com/hackmdio/codimd/pull/1199
> fix: migration should return promise

- config.json.example
- docs/configuration-config-file.md
- docs/configuration-env-vars.md
- public/docs/yaml-metadata.md
> Slightly improve documentation

- lib/config/dockerSecret.js
Prevents "TypeError: Cannot freeze array buffer views with elements".
> Config: Return String Instead Of Buffer For Docker Secrets

- app.js
- lib/config/default.js
Requests for `/build`, `/uploads` and so on will not result in a redirection loop anymore but respond with an HTTP 404.
Maybe we should add specific routes for these directories that return an HTTP 403?
> Fixed #179 (redirect loop with a trailing slash)

- lib/response.js
- lib/web/noteRouter.js
Added a new endpoint `/new/:noteId` that allows creation of a note by HTTP-POST with the specified alias as noteId.
> Added endpoint for note-creation with given alias

- lib/models/note.js
- lib/response.js
- public/docs/yaml-metadata.md
- public/views/codimd/head.ejs
- public/views/index/head.ejs
- public/views/pretty.ejs
Adds fixed opengraph metadata to the CodiMD index page and modifiable opengraph metadata to the notes. By default, the title and description of the note will be used, but with the YAML frontmatter this can be overridden.
See feature request #40
> Add customizable opengraph metadata for notes (see #40)

- lib/response.js
This regression bug was caused by the error page using the `codimd/head`
template. This resulted in error messages like this:
```
ReferenceError: /codimd/public/views/error.ejs:5
3|
4| <head>
>> 5|     <%- include codimd/head %>
6|     <link rel="stylesheet" href="<%- serverURL %>/css/center.css">
7| </head>
8|
/codimd/public/views/codimd/head.ejs:7
5| <meta name="apple-mobile-web-app-status-bar-style" content="black">
6| <meta name="mobile-web-app-capable" content="yes">
>> 7| <% for (var og in opengraph) { %>
8| <% if (opengraph.hasOwnProperty(og) && opengraph[og].trim() !== '') { %>
9| <meta property="og:<%- og %>" content="<%- opengraph[og] %>">
10| <% }} if (!opengraph.hasOwnProperty('image')) { %>
opengraph is not defined
at eval (eval at compile …
```
> Fix broken error template due to missing opengraph

- docs/dev/api.md
- docs/dev/openapi.yml
Adding documentation for the available REST endpoints in markdown and OpenAPIv3 format.
Some endpoints are not included. These are mainly login (and callbacks)/logout and quite internal things.
See #172
> Add API documentation (#172)

- public/js/render.js
Because sandbox is whitelist attribute, attacker will be able to create iframe that has more permission than default.
Signed-off-by: RyotaK <49341894+ry0tak@users.noreply.github.com>
> Don't accept sandbox attribute

- config.json.example
- lib/config/default.js
- lib/web/statusRouter.js
- public/js/extra.js
- public/js/lib/common/constant.ejs
Allow to generate lower case header references through the config
This makes the references consistent/compatible with GitHub,
GitLab, Pandoc and many other tools.
This behavior can be enabled in _config.json_ with:
```
"linkifyHeaderStyle": "gfm"
```
See [the related issue on HackMd](https://github.com/hackmdio/codimd/issues/1305).
> Allow to generate lower case header references through the config

- package.json
`exports-loader` and `ejs-loader` seem to be not used anywhere, the `uglifyjs` plugins are replaced by the `TerserPlugin` integrated in Webpack 4.
> Remove unused webpack plugins from package.json

- package.json
- webpack.common.js
MathJax 2.7.6 changed their packaging structure and stopped to include `MathJax.js` in the package root. This PR copies the MathJax JS from the `unpacked` folder and the required fonts seperately.
> Fix compatibility with MathJax 2.7.6

- lib/errors.js
- lib/web/auth/dropbox/index.js
- lib/web/auth/email/index.js
- lib/web/auth/facebook/index.js
- lib/web/auth/github/index.js
- lib/web/auth/gitlab/index.js
- lib/web/auth/google/index.js
- lib/web/auth/ldap/index.js
- lib/web/auth/mattermost/index.js
- lib/web/auth/oauth2/index.js
- lib/web/auth/openid/index.js
- lib/web/auth/saml/index.js
- lib/web/auth/twitter/index.js
- lib/web/auth/utils.js
Saving referer into session in SAML auth so passport can redirect correctly after SAML login.
Before this, after the SAML login the user was always redirected to config.serverURL + '/'
Signed-off-by: Ralph Krimmel <rkrimme1@gwdg.de>
> Fixing redirection after SAML login

- config.json.example
- lib/config/default.js
- lib/config/environment.js
- public/js/extra.js
- public/js/lib/common/constant.ejs
more changes (fixes) for the [previous merge with the same goal](https://github.com/codimd/server/pull/205).
In short: The GitHub conform naming did not work right, because of the `deduplicateHeaderId()` method.
These changes and fixes were developed over at:
https://github.com/hackmdio/codimd/pull/1310
> Linkify header style

- docs/setup/manual-setup.md
`yarn start --production` ignores the `--production` flag,
`npm start --production` does not.
> [DOC] Use `npm start`, not `yarn start` to start

- docs/configuration-config-file.md
- docs/configuration-env-vars.md
`manage_user` script defaults to `development` environment.
Add to doc the solution suggested by @SISheogorath in #148 .
> [DOC] Run `manage_users` with `NODE_ENV=production` set.

- public/views/codimd/head.ejs
- public/views/includes/header.ejs
- public/views/includes/scripts.ejs
- public/views/index/head.ejs
- public/views/pretty.ejs
- public/views/slide.ejs
- webpack.common.js
- webpack.htmlexport.js
- webpack.prod.js
Webpack now uses relative paths for resources linked from by static
snippets. A templated <base> tag has been introduced in headers
so app.js can set the base URL at runtime.
EDIT: this fixes #105
> Fix urlPath support, let CodiMD be served from a subpath correctly

- bin/manage_users
Fixes #234 
The manage_users script currently does not work since it compares to undefined. However, the returned variable is null, resulting in crashing of the script. (see #234)
Additionally, I changed a return code in the createUser() function. This allows other scripts to distinguish between the failure reasons.
This pull request was created a couple days ago on the other CodiMD project: https://github.com/hackmdio/codimd/pull/1370
> Fix #234 - make manage_users work again

- public/js/cover.js
When the login dialog is opened, the focus will be set to either the LDAP-username field, the email field or the OpenID field in this order.
> Fix #249 - Focus user field after opening login modal

- public/docs/privacy.md.example
Very tiny PR: In #173 the documentation was updated regarding the usage of Libravatar instead of Gravatar. This PR does the update for the privacy template document.
Btw: The privacy statement at demo.codimd.org still refers to Gravatar too.
> Changed Gravatar to Libravatar in privacy-template

- docs/configuration-config-file.md
- lib/config/default.js
As we noticed in our poll about CDN usage, that most people
intentionally turn it off, but very little intetionally turn it on or
leave it on. https://community.codimd.org/t/poll-on-cdn-usage/28
There is also strong indicators that CDNs don't really provide any
benefits in loading time and due to the small deployments of CodiMD,
there is no big savings due to CDNs either. https://csswizardry.com/2019/05/self-host-your-static-assets/
Therefore this patch changes the CDN default settings to off in order to
reduce the exposed user data.
> Update CDN defaults

- public/js/index.js
The revision view had a bug that clicking on a list entry would redirect
the user back to the index page instead of providing the revision diff.
This was cased by the baseurl which is now used as reference for hrefs.
Therefore when clicking on the `href="#"` this was actually pointing at
`<baseurl>#` which is usually the index page.
This patch simply removes the href from the list items and therefore the
link functionality. This fixes the whole problem by removing 9
characters from our source code
> Fix revision redirect to index page

- docs/configuration-env-vars.md
`CMD_ALLOW_ANONYMOUS_EDITS` is only applied when `CMD_ALLOW_ANONYMOUS` is `false`, see [here](https://github.com/codimd/server/blob/9c1665ae5bf3cf38210ffd862d10de9b13bfacdd/lib/config/index.js#L71-L73).
> Adjust description of CMD_ALLOW_ANONYMOUS_EDITS

- lib/app.js
Database migrations should be in charge of changing and modifying the
database schema. Therefore this breaking change removes the automatic
model synchronisation from the application startup, that we have
practised way too long and that always caused problems for us.
> Limit DB schema changes to migrations

- lib/config/default.js
- lib/web/auth/ldap/index.js
- package.json
This makes it possible to use StartTLS by passing the starttls option through to the passport-ldapauth library. This resolves Issue #329
> Pass through ldap starttls option

- public/js/lib/editor/index.js
Several of the last travis-ci builds failed due to a useless blank line being detected by eslint.
This PR is just to make eslint happy again - so that new builds run without problems.
> Fixed eslint error introduced by 2d3ea1f

- docs/configuration-config-file.md
- lib/app.js
- lib/config/default.js
- lib/config/index.js
The locales search path needs to be updated because the main app.js was moved into a sub-directory (/lib).
> Fixed wrong locales search path after app.js move

- lib/web/note/util.ts
> findNoteOrCreate: Create new note with empty string instead of `null`

- docs/url-scheme.md
As suggested in the [Matrix chat](https://matrix.to/#/!ybaSlrrMNLeuoQuUuR:matrix.org/$15876820269305rLVBT:chat.weho.st?via=shivering-isles.com&via=matrix.org&via=chat.weho.st), here an overview of the different URLs that CodiMD uses for notes.
> Add document explaining different URLs

- lib/letter-avatars.ts
- lib/models/user.ts
- lib/web/auth/dropbox/index.ts
- test/auth.ts
This PR fixes a bug in the Dropbox auth middleware (broken import) and adds tests to make sure we avoid this type of bug in the future.
It also removes the custom handling of the Dropbox profile object in `parsePhotoByProfile`. The mail-address is now unwrapped in the `DropboxMiddleware` and `Profile.mail` is always a `string[]`.
Finally as `email` is always a string, we can get rid of a (broken) check in `generateAvatarURL`.
I tried to follow @SISheogorath s example and wrote longer commit messages to explain the changes :wink:
> Tests and Fixes for Auth Middlewares

- app.js
While HSTS should take care of most of this, setting cookies to be
secure, and only applied on same site helps to improve situations where
for whatever reason, downgrade attacks are still a thing.
This patch adds the `sameSite` and `secure` to the session cookie and
this way prevent all accidents where a browser may doesn't support HSTS
or HSTS is intentionally dropped.
Reference:
https://www.npmjs.com/package/express-session#cookiesecure
> Ensure session cookies are secure

- app.js
- public/js/index.js
- public/js/lib/common/login.js
- public/js/lib/editor/index.js
- public/js/locale.js
This disables the unneeded `io` cookie from socket.io and enables `sameSite: strict` for all cookies.
> Cookie cleanups

- docs/configuration-config-file.md
- docs/configuration-env-vars.md
The default is false and the option only matters if allowAnonymous is false
> Fix allow anonymous edit documentation

- package.json
This removes npm dependency, and fixes warnings about `npm` and `yarn` using different copies of `node`.
> Fully dedicate our soul to yarn

- src/lib/models/note.ts
When a logged in user creates a note, the `ownerId` is property is set,
but `owner` is not. Thus, the default note permission is always
`freely`, regardless of the `defaultPermission` setting. By checking
`ownerId` instead, this correctly uses the `defaultPermission` config
when the user is logged in.
This is especially an issue when `allowAnonymous` is `false`, since this
would allow the user to create a note with `freely` permission when it
should not be allowed.
It is unclear to me when `owner` is set, if at all. So this patch might
not be the "correct" fix of the problem. Nevertheless, it does fix the
problem.
> Fix default permission

- src/lib/app.ts
- src/lib/config/default.ts
- src/lib/config/environment.ts
This allows configuring the group and mode of the unix socket after it
has been created to allow reverse proxies to access it. Fixes #317.
I decided to call `chown` and `chgrp` directly to change the owner and
group (the former will almost definitely not be called; only root can
chown a file to another user, and you are not running codimd as root. It
is included for consistency).
The nodejs chown/chgrp functions only accepts uid and gid, not the names
of the user or group. The standard way to convert a group name into a gid
is the `uid-number` package. The way this package works is that
1. It spawns a new nodejs process
2. The new nodejs process calls nodejs' setgid function, which *does*
accept both the group name and gid
3. It then calls getuid to retrieve the uid of the process, and …
> Add option for socket permissions

- src/lib/web/auth/oauth2/oauth2-custom-strategy.ts
OAuth2 allows the user to only consent to a subset of the scopes
requested. Previously, the Generic Oauth2 implementation assumes that
the `username`, `email` and `displayName` attributes are supplied, and
may crash if they are not defined.
This commit allows for `email` and `displayName` to not be defined,
either through the user refusing consent or the OAuth2 configuration
not asking for them in the first place (by not setting
`userProfile*Attr`).
If `email` is not provided, the `emails` property is simply left empty.
If `displayName` is not provided, it is left undefined, and CodiMD uses
the `username` whenever the `displayName` is expected.
This does not deal with the case where `username` is not provided. Since
usernames are not unique in CodiMD, it is possible to deal with this by …
> Allow for undefined email and displayName

- README.md
browser logos switched to use main as their default branch which breaks the direct links.
> Fix browser logo links

- src/lib/web/auth/oauth2/index.ts
The OAuth2 specification RECOMMENDS setting the state to protect against
CSRF attacks. Some OAuth2 providers (e.g. ORY Hydra) refuse to
authenticate without the state set.
Signed-off-by: Dexter Chua <dalcde@yahoo.com.hk>
> Generic OAuth2: Set state: true

- src/lib/app.ts
- src/lib/realtime.ts
- src/lib/utils/functions.ts
Previously, upon receiving a termination signal, the process tries to
flush all changes to the database, retrying every 0.1s until it
succeeds. However, if the database is not set up properly, this always
fails, and spams the terminal/logging with the error message 10 times a
second.
If the user sends another termination signal, the handleTermSignal
function is called once again, and we get twice the number of error
messages.
This commit changes the behaviour in various ways.
(1) It lowers the retry rate to 0.5s, and aborts after 30 seconds.
(2) If the write to the database errored, the error message explains
that this is due to us flushing the final changes.
(3) We replace realtime.maintenance with realtime.state, which is an
Enum with three possible states --- Starting, Running, and …
> Improve handling of termination signals

- public/docs/yaml-metadata.md
In the yaml-metadata docs, the example for the 'lang' attribute had an invalid key 'langs'.
> Fix yaml-metadata docs example for lang

- lib/models/note.js
- lib/web/note/util.js
- public/views/pretty.ejs
This PR fixes the problem that published CodiMD notes have a hardcoded `lang=en` html-attribute and therefore won't be correctly identified by external parsers or translation browser extensions.
If you set the `lang` [yaml-metadata](https://demo.codimd.org/yaml-metadata#lang), that value will be used instead of 'en' with this PR.
> Set lang-metadata from yaml as document language

- src/lib/models/revision.ts
- src/lib/workers/dmpWorker.ts
dmpWorker is run as a childProcess, which is a completely separate
nodejs instance. As such, the `logger` it obtains is a separate instance
than the one in the parent. The parent reads the config file to
determine the log level, but the childProcess does not. So the log level
used in dmpWorker is always `debug`, regardless of the configuration
options.
In addition to polluting the logs, this is potentially a privacy issue,
because `dmpWorker` logs the diffs of notes at the `debug` level, which
will then enter the system logs.
This commit fixes this by making `dmpWorker` send any messages back to
the parent, who is responsible for logging. This also avoids any
potential race conditions between the two loggers writing to the same
output.
Fixes #433
> Fix dmpWorker logging

- package.json
- yarn.lock
This is a forward-port of d6ce60c.
The old pg version doesn't work with node version 14 due to
an undocumented API change in the `readyState` in the socket API.
This patch updates the required dependency and this way resolves the
issue.
> [2.0] Upgrade pg package to fix node version 14 compatibility

- package.json
- src/lib/app.ts
- src/lib/migrations/20150504155329-create-users.js
- src/lib/migrations/20150508114741-create-notes.js
- src/lib/migrations/20150515125813-create-temp.js
- src/lib/migrations/20150702001020-update-to-0_3_1.js
- src/lib/migrations/20150915153700-change-notes-title-to-text.js
- src/lib/migrations/20160112220142-note-add-lastchange.js
- src/lib/migrations/20160420180355-note-add-alias.js
- src/lib/migrations/20160515114000-user-add-tokens.js
- src/lib/migrations/20160607060246-support-revision.js
- src/lib/migrations/20160703062241-support-authorship.js
- src/lib/migrations/20161009040430-support-delete-note.js
- src/lib/migrations/20161201050312-support-email-signin.js
- src/lib/migrations/20180306150303-fix-enum.js
- src/lib/migrations/20180326103000-use-text-in-tokens.js
- src/lib/migrations/20180525153000-user-add-delete-token.js
- src/lib/models/index.ts
- yarn.lock
Instead of using sequelize-cli and ensure migrations by shellscript,
this patch automates database migrations properly to the umzug library.
The sequelize CLI becomes a dev dependencies as it's still useful for
generating migrations.
This should eliminate the need for crude generating of database config
files and alike. Instead we utilize the pre-configured sequelize
connection that CodiMD will use anyway.
> Run database migrations automatically on startup

- package.json
- webpack.common.js
- yarn.lock
This PR updates copy-webpack-plugin, css-loader, html-webpack-plugin, style-loader, webpack and webpack-cli, mainly to fix a warning about an insecure version of `serialize-javascript`, that was used by them.
`copy-webpack-plugin` needed a major update, but the necessary config changes are relatively simple.
> Update Webpack dependencies

- README.md
This commit adds a short documentation detailing how to backup one's instance.
It looks obvious, but I'm still wondering whether I forgot something or not. This PR is a mean to answer this question for me and others in the future.
Thanks!
> Document the backup process

- docs/dev/db-schema.plantuml
Previously, single dashes were used for associatons, which makes PlantUML layout all of them in an horizontal line. I changed that to two dashes so that PlantUML uses normal layouting. I think that is far clearer.
(See https://plantuml.com/class-diagram for more on layouting.)
> Update db schema UML layouting

- lib/csp.js
- public/js/index.js
- test/csp.js
The lack of a 'preventDefault' on the click event handlers resulted in the dropbox links being unclickable.
Furthermore, because of a missing CSP rule, the dropbox script couldn't be loaded. The dropbox origin is now added to the CSP script sources if dropbox integration is configured.
Fixes #484
> [1.x] Fix dropbox import/export buttons not working

- test/jest-e2e.json
- test/public-api/notes.e2e-spec.ts
This PR also adds the Jest config that was still missing (taken from a default NestJS project).
> Add E2E tests for /notes route

- src/api/public/me/me.controller.spec.ts
- src/api/public/me/me.controller.ts
- src/api/public/media/media.controller.spec.ts
- src/api/public/media/media.controller.ts
- src/api/public/notes/notes.controller.spec.ts
- src/api/public/notes/notes.controller.ts
- src/api/public/public-api.module.ts
- src/app.module.ts
- src/history/history.module.ts
- src/history/history.service.spec.ts
- src/history/history.service.ts
- src/logger/console-logger.service.ts
- src/logger/logger.module.ts
- src/logger/nest-console-logger.service.ts
- src/main.ts
- src/monitoring/monitoring.module.ts
- src/notes/notes.module.ts
- src/notes/notes.service.spec.ts
- src/notes/notes.service.ts
- src/permissions/permissions.module.ts
- src/revisions/revisions.module.ts
- src/revisions/revisions.service.spec.ts
- src/revisions/revisions.service.ts
- src/users/users.module.ts
- src/users/users.service.spec.ts
- src/users/users.service.ts
- test/public-api/notes.e2e-spec.ts
Depends on #500
[The Nest docs](https://docs.nestjs.com/techniques/logger#use-external-logger) recommend using an external logging module for production.
Pino is a JSON-based logger, that allows for structured logging in production and pretty logging during development. `nestjs-pino` automatically configures `pino-http` to intercept requests and adds a unique id to every request, which aids traceability.
As we currently have no config system, pretty printing and other settings are hardcoded.
> Use custom logger

- src/logger/nest-console-logger.service.ts
The current implementation of `NestConsoleLoggerService` missed propagating the stack trace to the underlying `ConsoleLoggerService`. This PR fixes this bug.
> Fix stack trace logging

- public/docs/features.md
Pull request that resolves issue #196
> Add revisions documentation - Issue #196

- docs/dev/public_api.yml
- src/history/history.service.ts
- src/notes/note-metadata.dto.ts
- src/notes/note-permissions.dto.ts
- src/notes/notes.service.ts
This PR fixes a few inconsistencies in our public API specification.  
The `/notes/{note}/permissions` and `/notes/{note}/metadata` routes were split and are now only responsible for updating permissions and note metadata (title, description, tags) respectively.
> Updates for the public API

- public/js/extra.js
Fixes #545
Basic auth-regex from https://gist.github.com/dperini/729294
Co-authored-by: Yannick Bungers <git@innay.de>
Signed-off-by: David Mehren <git@herrmehren.de>
> Use URL constructor instead of regex to check for valid URL

- lib/web/note/util.js
Currently, when creating a note with content via the API, a title is only saved to the database after visiting the note with the browser. This commit makes sure that a title is saved at creation time.
Closes #306
Signed-off-by: David Mehren <git@herrmehren.de>
> Save note title to database when creating a note

- app.js
This PR fixes the HSTS deprecation warning for "includeSubdomains"
Fixes #74
> Fix deprecation warning of "includeSubDomains"

- lib/utils.js
If you upload images like .JPG, this fails without this fix.
> Makes the mime also work with upper case extension

- docs/setup/manual-setup.md
- Updated Node.js requirement
- Added warning for older Mysql and MariaDB versions
- changed npm commands to yarn commands
- changed occurrences of CodiMD to HedgeDoc for easier merging
> Fixed inconsistencies in documentation

- public/css/cover.css
This PR fixes the width of the hedgedoc logo on the front page.
> Fix image width on mobile view for front page

- bin/setup
There are some distros out there, shipping quite outdated packages with
them, which results in weird issues. Let's check that we have a more or
less up to date version of node and yarn installed.
This patch adds those checks and this way should provide some helpful
error messages to people who try to install CodiMD.
Previously: https://github.com/hackmdio/codimd/pull/1075
> Add some version checks to setup script

- README.md
Currently the mastodon button still points to the old account. This
patch fixes this problem by using the new account id.
> Update account ID for mastodon icon

- .github/workflows/node.js.yml
Github Actions CI
As you can see in some PRs(e.g. #596), the CI executes every check twice. This is because the current CI config runs for every push to every branch and every pull request. 
This PR limits the CI runs to pushes to the master branch and pull requests against master.
> Limit CI runs to pushes to master and pull requests against master

- public/views/hedgedoc/head.ejs
- public/views/html.hbs
- public/views/index/head.ejs
- public/views/pretty.ejs
- public/views/slide.ejs
HTML-templates
This PR fixes the URLs of the shortcut icons ("favicons") in the HTML templates. Especially the read-only-view ("published") and the slide-view didn't had any correct icons, the editor itself at least had both old and new icons. Now they all include the favicon-partial if possible.
Thanks to @omia for reporting this issue.
none
> Fix shortcut icon urls pointing to old (nonexistent) files

- package.json
- yarn.lock
Package AWS SDK
It bumps AWS SDK from 2.345.0 to 2.521.0
Tested locally executed an insert image.
Executed as:
```
CMD_S3_BUCKET="my-bucket" CMD_S3_REGION="eu-west-1" CMD_IMAGE_UPLOAD_TYPE="s3" CMD_S3_BUCKET="my-bucket" CMD_S3_REGION="eu-west-1" node app.js
```
#600
> chore: bump AWS SDK from 2.345.0 to 2.521.0

- docs/dev/openapi.yml
- package.json
- public/docs/release-notes.md
- yarn.lock
```
We have renamed to HedgeDoc! :tada:
Many thanks to [Éric Gaspar](https://github.com/ericgaspar/) who designed our new logo!
Have a look at our new website (which also explains the reasoning behind the renaming) at https://hedgedoc.org
This is probably the last release in the 1.x series. Stay tuned for 2.0, scheduled for release next year.
**Please note:** This release dropped support for Node 8, which is end-of-life since January 2020. You now need at least Node 10.13 to run HedgeDoc, but we recommend running [the latest LTS release](https://nodejs.org/en/about/releases/).
- Our release tarballs now contain the frontend bundle. This saves users from building the frontend themselves, which was an issue on memory-constrained systems.
- Add OIDC scopes for email & profile retrieval (#278 …
```
> Release 1.7 RC1

- renovate.json
Renovate config
This PR changes the label that is used by renovate.
#589
> Change label used by renovate to "type: maintenance"

- lib/migrations/20150702001020-update-to-0_3_1.js
- lib/migrations/20160112220142-note-add-lastchange.js
- lib/migrations/20160420180355-note-add-alias.js
- lib/migrations/20160515114000-user-add-tokens.js
- lib/migrations/20160607060246-support-revision.js
- lib/migrations/20160703062241-support-authorship.js
- lib/migrations/20161009040430-support-delete-note.js
- lib/migrations/20161201050312-support-email-signin.js
- lib/migrations/20180525153000-user-add-delete-token.js
- lib/migrations/20200321153000-fix-account-deletion.js
Migration `20150702001020-update-to-0_3_1`
This PR adds a new variant of the "duplicate column name" error to the catch block. The solution is as hacky as the rest of the catch block, but I don't think that we need a more complex solution. 1.7 is the last 1.x version and 2.0 gets a new database layout.
Closes #607
> [Migrations] Add variant of error message to catch block

- lib/web/auth/oauth2/index.js
OAuth2
If the optional config options `config.oauth2.userProfileIdAttr` or `config.oauth2.rolesClaim` were not set, `String.split` was called on `undefined`, triggering a crash.
This commit adds handling of these cases and improves error logging in `checkAuthorization`.
Fixes #608
> Fix crash when OAuth2 config parameters are missing

- docs/setup/reverse-proxy.md
docs
As we found out in #616, Apache does not set the `X-Forwarded-Proto` header, which is now required because we switched to secure cookies in 383d791a50919bb9890a3f3f797ecc95125ab8bf.
#616
> Document reverse proxy config for Apache

- public/docs/features.md
features page
This PR replaces the example PDF with one not having an `X-Frame-Options` header and adds a hint to our FAQ page which explains the embedding problems.
#631
> Fix broken PDF embed in features page & explain embedding problems 

- webpack.common.js
Webpack config
Previously, .css files always had the same name, which can lead to caching problems.
In our case, the new CSS for the HedgeDoc logo was not loaded when Chrome had the 1.6.0 CSS in the cache, leading the HedgeDoc logo filling the whole screen.
This PR adds the contenthash to the .css files generated by webpack, which ensures that changed files are always loaded.
References:
https://github.com/webpack-contrib/mini-css-extract-plugin#filename
https://webpack.js.org/configuration/output/#outputfilename
> Generate CSS filenames with contenthash

- docs/setup/docker-linuxserver.md
Update badges and info to point to the newly published [linuxserver HedgeDoc image](https://github.com/linuxserver/docker-hedgedoc)
just readme/docs update
This PR improves documentation
N/A
N/A
> update linuxserver docker info

- README.md
docs
Apparently we have stopped supporting IE11. It shows a syntax error for our JS. I have spent half an hour trying to add IE11 to our Babel config, but that did not resolve the issue. It seems bigger changes to our Webpack config might be necessary to support IE11 again, which I don't think is worthwhile. It's probably reasonable to just remove IE from the list of supported browsers.
Closes #645
> Remove IE11 support from README

- CONTRIBUTING.md
- README.md
readme & contribution docs
This PR updates the readme and contribution docs with information about the ongoing 2.0 development.
I cherry picked the restructuring of `CONTRIBUTING.md` from `master` and added a note about 2.0 afterwards.
> Update docs for 2.0 development

- jest-e2e.json
CI
For some reason Jest sometimes times out when running in GitHub Actions.
This tries to mitigate that error.
> E2E tests: Increase timeout & set concurrency to 1

- renovate.json
Renovate config
This option makes Renovate refresh yarn.lock once per week
See https://docs.renovatebot.com/configuration-options/#lockfilemaintenance
> Renovate: Maintain lock files once per week

- .idea/copyright/hedgedoc.xml
copyright template idea
This PR fixes the template to always use the current year.
> fixed copyright template for idea

- src/api/public/notes/notes.controller.ts
- test/public-api/notes.e2e-spec.ts
NotesController
This PR adds proper error handling and returns 404 when a note does not exist.
Previously, we leaked the `NotInDBError` and sent a 500 status code.
> NotesController: Do not crash on nonexistent notes

- src/api/utils/markdownbody-decorator.ts
Custom decorator `MarkdwonBody`
As explained in https://github.com/nestjs/swagger/issues/32#issuecomment-716169471, it's possible to register swagger metadata in custom decorators by providing an array of `enhancers`.
We now add metadata with the `MarkdownBody` decorator: The request needs a `body` with content-type `text/markdown`.
> MarkdownBody: Register swagger metadata

- src/notes/notes.service.ts
- src/revisions/revisions.service.ts
- test/public-api/notes.e2e-spec.ts
NotesService
This PR improves the `NotesService` to get the note creation time from database.
> Get note creation time from database

- public/css/index.css
editor
This PR fixes a problem that the last line of code becomes covered by statusbar and can't be moved without changing the note.
Thanks to @mhdrone for reporting this and suggesting the fix
fixes #724
> fixed last line statusbar cover problem

- public/js/reveal-markdown.js
- public/js/slide.js
slideOptions
This PR adds sanitation to the slideMode in frontmatter 
Specifically left out are
- dependency (user can't really include anything anyway, because CSP forbids most domains)
- autoSlideMethod (nothing our users should be able to change as they won't write JS to be affected by this)
- keyboard (this let's users write arbitrary code and seems therefore to problematic)
https://github.com/hakimel/reveal.js/blob/3.9.2/README.md#configuration
https://github.com/hackmdio/codimd/issues/1648
> added sanitation to the slideMode in frontmatter

- public/js/slide.js
Reveal.js
Reveal.js doesn't set the default value of an option in the provided config object
if the key is set with "undefined" as value. This leads to a broken slide mode,
because some critical settings are missing.
> Delete slide options that are not defined

- docs/content/dev/public_api.yml
- src/api/public/notes/notes.controller.ts
- src/notes/notes.service.ts
- test/public-api/notes.e2e-spec.ts
Notes API
This PR improves spec compliance of the note API by returning the changed note on `PUT` requests to `/notes/{noteid}`.
It also moves the route to update note permissions under the `metadata` path. That location seems more sensible, as the metadata object includes the permissions.
Fixes #702
> Notes API: Improve spec compliance

- docs/content/setup/index.md
Documentation
This PR adds a index page to the setup namespace in the docs to make it easier to link to this section.
> Add page to setup namespace

- docs/content/setup/manual-setup.md
Documentation
This PR fixes a wrong link in the documentation
#747
> [Documentation] Fix link in manual setup

- CONTRIBUTING.md
Same needs to be done in `master` branch.
> Fix link to DCO in contributing docs

- nest-cli.json
- src/history/history-entry-update.dto.ts
- src/history/history-entry.dto.ts
- src/notes/note-authorship.dto.ts
- src/notes/note-metadata.dto.ts
- src/notes/note-permissions.dto.ts
- src/notes/note.dto.ts
- src/revisions/revision-metadata.dto.ts
- src/revisions/revision.dto.ts
- src/users/user-info.dto.ts
Various data transfer objects
This PR adds JSDoc comments to various DTOs and enables comment introspection for the swagger plugin, so the docs get displayed in the Swagger UI.
> Add JSDoc comments to DTOs

- src/main.ts
- src/utils/swagger.ts
Swagger config
This PR splits the Swagger docs into the public and private API.
The docs for the public API continue to be available under `/apidocs`, the docs for the private API are now separated under `/private/apidocs`.
Fixes #759
> Swagger: Split public and private API

- public/css/markdown.css
CSS of markdown renderer
This PR fixes several readability issues with diagrams/embeddings in night-mode.
- Sequence diagrams and flow-charts are now properly white-on-dark.
- Graphviz diagrams were previously hard to read, therefore they're now not inverted anymore.
- GitHub Gist embeddings have each second line in a different color, they're now in a more similar color to not distract readers that much anymore.
- ABC.js sheets are now black-on-white again as that's easier to read.
fixes #773
> Improved CSS in night-mode

- src/auth/auth.service.ts
- src/auth/token.strategy.ts
auth
This PR catches all NotInDbErrors and TokenNotValidError and transform them to UnauthorizedException with the correct message.
This prevents nest from telling the api user that an internal server error has happened and instead display the correct http error code 401.
fixes #775
> auth: Fix handling of internal server errors

- .github/ISSUE_TEMPLATE/config.yml
- .reuse/dep5
GitHub
This patch adds a Issue template config, which can be used to link to
the forum for support requests as well as community discussions.
https://docs.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
> Add issue config to add external links to the community forum

- src/api/public/me/me.controller.ts
- src/api/public/media/media.controller.ts
- src/api/public/monitoring/monitoring.controller.ts
- src/api/public/notes/notes.controller.ts
- src/auth/mock-auth.guard.ts
- src/media/media-upload-url.dto.ts
- src/media/media.service.ts
- src/notes/notes.service.ts
- src/revisions/revisions.service.ts
- test/public-api/media.e2e-spec.ts
- test/public-api/notes.e2e-spec.ts
DTO should only be used for sending information to and from user.
Services now have methods which return normal internal objects and
methods which convert them to DTOs. This conversion is done in the
controlers
This PR fixes/adds/improves/...
> Refactoring of controllers and service interfaces

- CONTRIBUTING.md
Contribution docs
To ensure maintainability,
commit guidelines are added to our contribution documentation.
They include notes on commit structure and the commit message,
which evolved from issues that were encountered while developing.
> Add commit guidelines to contribution docs

- .github/pull_request_template.md
- CONTRIBUTING.md
- README.md
docs
To further reduce confusion between the `develop` and `master` branches,
this PR adds more information about them in the README
and the contribution docs.
> Docs: Emphasize the difference between branches

- renovate.json
Currently renovatebot only cares about the default branch, which is
currently develop. In order to keep everything up-to-date we should
configure it, to also make sure that the master branch for 1.x will be
updated.
Therefore this patch adds the `baseBranches` config option, which allows
to define an array of branches to update.
Reference:
https://docs.renovatebot.com/configuration-options/#basebranches
> renovatebot: Configure renovatebot to update 1.x and 2.x branches

- src/api/public/notes/notes.controller.ts
- src/auth/auth.service.ts
- src/notes/notes.service.ts
Logging
Our custom logger supports providing the name of the function that
calls the logger, this PR adds this context string where it
was previously missing.
> Add missing logging context at various places

- .env.example
- docs/content/dev/config.md
- docs/mkdocs.yml
Dev Docs
This PR adds developer documentation about the configuration code.
This explains how the configuration code works and give some hints on what do look out for while working on the configuration code.
fixes #752
> Dev Docs: Add configuration documentation

- test/public-api/me.e2e-spec.ts
e2e tests
This PR fixes the GET /me e2e test.
Since the /me route does work now, we should reactivate (and fix) this test, too.
> Tests: Fix GET /me e2e test

- lib/models/note.js
Note creation
As explained in #391, the previous note creation logic didn't handle the case "alias is set, but it's not a file on disk". The fix introduces a separate if-statement for this scenario at the cost of a doubled filesystem read access.
Fixes #391
> Fix note creation in FreeURL-mode does not apply default template

- config.json.example.license
Licensing
config.json.example was deleted, but the license file was not. This
removes the leftover file.
> Remove license of deleted file

- src/api/public/notes/notes.controller.ts
- test/public-api/notes.e2e-spec.ts
notes e2e tests
This PR
- splits success and fail cases in separate tests for better readability
- adds the correct user to all notes created by service (instead of api) to make the permissions checks viable.
- extracts test content of notes to a global variable.
> NotesE2E: Fix e2e test 

- lib/web/note/controller.js
- lib/web/note/util.js
Note retrieval logic
When FreeURL mode is enabled and you called the /download route, the note was created and the user redirected to the blank note.
This is caused because the findNote method automatically creates a note when no existing one is found.
This commit adds a new parameter to the findNote method which allows to disable this behaviour. In that case a HTTP 404 error will be returned.
Fixes #370
> Add HTTP 404 error on actions for non-existent notes

- docs/content/dev/2.0.md
Docs
This PR improves the 2.0 development documentation:
- document what the file is for
- list the supported databases (closes #447)
#447
> Document supported databases

- src/api/public/notes/notes.controller.ts
- src/notes/notes.service.spec.ts
- src/notes/notes.service.ts
- test/public-api/notes.e2e-spec.ts
This PR deletes the unused `getNoteContentByIdOrAlias` and changed name of `getNoteContentByNote` to `getNoteContent` to make it uniform with other methods.
> NoteService: Rename getNoteContentByNote

- src/api/public/media/media.controller.ts
- src/errors/errors.ts
- src/media/backends/filesystem-backend.ts
- src/media/media-backend.interface.ts
- src/media/media.service.ts
media service
This PR adds the MediaBackendError.
This will then be rebased on #947 and #942 
> MediaService: Add MediaBackendError

- src/media/backends/filesystem-backend.ts
- src/media/media-backend.interface.ts
media backend interface
This PR removed the gitFileUrl method from media backend interface.
closes #957
> MediaBackendInterface: Remove getFileURL

- app.js
- docs/content/guides/migration-troubleshooting.md
- docs/mkdocs.yml
- lib/models/index.js
- package.json
- yarn.lock
Database-handling and docs.
This PR removes the need for separate migrations with the sequelize-cli
by running them with umzug on application startup.
It also adds documentation around troubleshooting migrations.
#384
> [1.x] Run database migrations automatically on startup

- .sequelizerc.example
- bin/heroku
- bin/setup
- docs/content/setup/manual-setup.md
- public/docs/release-notes.md
Config, setup scripts, release notes
After https://github.com/hedgedoc/hedgedoc/pull/969 was merged,
a separate configuration file for the sequelize-cli is no longer
required.
This PR updates the docs and setup scripts accordingly.
> Documentation updates after #969

- src/api/public/me/me.controller.spec.ts
- src/api/public/notes/notes.controller.spec.ts
- src/api/public/notes/notes.controller.ts
- src/config/app.config.mock.ts
- src/config/app.config.ts
- src/errors/errors.ts
- src/history/history.module.ts
- src/history/history.service.spec.ts
- src/media/media.service.spec.ts
- src/notes/notes.module.ts
- src/notes/notes.service.spec.ts
- src/notes/notes.service.ts
- src/permissions/permissions.service.spec.ts
- src/revisions/revisions.module.ts
- src/revisions/revisions.service.spec.ts
- test/public-api/me.e2e-spec.ts
- test/public-api/media.e2e-spec.ts
- test/public-api/notes.e2e-spec.ts
config, notesService
This PR adds the forbiddenNoteIds to the AppConfig.
Also uses this config in the notes service and the appropriate tests.
fixes #519
> Config: Add forbiddenNoteIds to AppConfig

- src/config/app.config.ts
AppConfig
This PR fixes bug in the schema of forbiddenNoteIds
> AppConfig: Fix bug in the schema of forbiddenNoteIds

- docs/content/dev/public_api.yml
- src/media/media.service.ts
This PR removes the allowedMimeType 'application/pdf'.
Uploading PDFs does not work with imgur and therefore HedgeDoc should not offer this uploading.
See #533
> MediaService: Remove allowedMimeType application/pdf

- public/views/hedgedoc.ejs
- public/views/html.hbs
- public/views/index.ejs
- public/views/pretty.ejs
- public/views/slide.ejs
render templates
Since the interface is not always in english, we mostly removed the lang attribute from all html tags. Since the error messages in error.ejs are not translated, but always in english, there the global lang="en" should be kept.
Also in the slide and editor template the div, which contains the user generated text, has the attribute translate="no" now, to avoid unwanted translations.
Since on the publish view (pretty.ejs) only the user generated content is shown, we set the lang to the language defined in yaml (or 'en') as a default, but that was also moved to the corresponding markdown div instead of html.
Fixes #881
See also #437
> [1.x] Templates: Remove lang and add translation parameter

- docs/content/dev/2.0.md
Dev documentation
This PR adds dev docs about deleting notes & revisions
Closes #560
> Add dev docs about deleting notes & revisions

- docs/content/dev/documentation.md
This PR fixes the dev doc 'documentation'.
Specific changes include:
- Fix typos
- Rewrite 'Deployment' paragraph. We currently don't and probably won't use Messor Structor.
> Docs: Fix dev doc 'documentation'

- src/api/private/notes/notes.controller.spec.ts
- src/api/private/notes/notes.controller.ts
- src/api/private/private-api.module.ts
- test/private-api/notes.e2e-spec.ts
private api
This PR adds the private api routes for /notes.
see #987
> PrivateAPI: Add notes controller

- docs/content/dev/authentication.md
- docs/mkdocs.yml
Dev documentation
This PR adds dev docs about user profiles and authentication
#451
> Add dev docs about user profiles and authentication

- app.js
term signal handler
`file.unlink` requires a callback, which we didn't set.
This PR adds a callback with (error) logging, enabling HedgeDoc
to properly clean up the socket.
Closes #784
> Properly clean up socket on exit

- lib/errors.js
- lib/web/note/util.js
Note controller
Previously one could override notes in FreeURL-mode by sending multiple POST requests to the /new/<alias> endpoint. This PR adds a check for an already existing note with the requested alias and returns a HTTP 409 Conflict error in case that happens.
fixes #371
> Check for existing notes on POST and don't override them

- lib/config/index.js
- lib/web/imageRouter/index.js
- package.json
- yarn.lock
Image upload
This PR checks all files that claim to be an svg (by their extension) that they really are and defines the typeFromMagic accordingly
Files that got identified as jpg, but have the extension .jpeg get their extension fixed.
The files extensions will work in all cases now.
fixes #744
> ImageUpload: Fix errors with .jpeg and .svg 

- lib/csp.js
Default CSP rules
This PR removes the yahoo domain from the default CSP rules.
closes #923
> CSP: Remove yahoo domain from defaults

- public/docs/features.md
features.md
This PR explains tags in the features.md with yaml metadata, instead of the
heading syntax.
> Features.md: Change tag explanation

- docs/content/references/hfm.md
- docs/mkdocs.yml
Documentation
This PR cherry-picks the HFM documentation page from #1066 to the master branch. I didn't change the content.
> [Docs] Add "HedgeDoc flavored markdown" page

- docs/content/guides/auth/saml.md
SAML Documentation
This PR fixes a wrong emoji replacement in the SAML documentation
> Fix emoji replacement in SAML docs

- docs/content/references/hfm.md
- docs/mkdocs.yml
Documentation
This PR:
- Adds the missing footnote plugin to the mkdocs configuration
- Replaces the unicode character for checkmarks with the twemoji shortcode.
> Add missing mkdocs plugin + Replace unicode character

- .gitignore
- src/config/mock/media.config.mock.ts
- src/media/backends/filesystem-backend.ts
media config mock
This PR changes the upload path of the media config mock to 'test_uploads' to ensure no real uploads are lost.
Also a bug in the filesystem media backend was fixed. All urls generated by this backend should be of the form `uploads/<filename>.<extension>` regardless of what the uploadDirectory is, because the backend proxies all locally uploaded files.
> MediaConfigMock: Change upload path

- docs/content/setup/getting-started.md
Docs
This PR replaces a codimd.org link with hedgedoc.org in the docs.
none
> Replace codimd.org link with hedgedoc.org

- README.md
readme
This PR switches paragraphs in the readme around.
With this change our support chat is mentioned before our dev chat. Hopefully that should direct people in the correct chat for them…
> README: Change order of paragraphs

- src/utils/serverVersion.spec.ts
- src/utils/serverVersion.ts
This PR fixes the getServerVersionFromPackageJson utility function.
The cache is never null, because it defaults to undefined, and therefore this function always returns undefined.
> Utils: Fix getServerVersionFromPackageJson

- src/api/private/me/history/history.controller.ts
- src/history/history-entry-import.dto.ts
- src/history/history.service.spec.ts
- src/history/history.service.ts
- test/private-api/history.e2e-spec.ts
private api
This PR improves the private apis `HistoryEntryCreationDto` by
1. renaming it to `HistoryEntryImportDto` as it is used to import a whole list of history entries rather than creating a single history entry
2. adding the `pinStatus` field to allow the frontend to maintain the pinStatus of historyEntries through the POST
3. adding the `lastVisited` for the same reason
> PrivateAPI: Rename HistoryEntryCreationDto to HistoryEntryImportDto

- README.md
docs
This PR improves the README by adding clear 'getting started' instructions, replacing some other parts with a clear itemized list.
#1125
> Add clear getting started instructions to README

- src/notes/note.entity.ts
- src/notes/notes.service.ts
- src/permissions/note-group-permission.entity.ts
- src/permissions/note-user-permission.entity.ts
- test/public-api/notes.e2e-spec.ts
permissions
This PR adds cascade to permissions on creation and deletion, so permissions can be created from the note and are deleted when either the note, user or group is deleted.
> Permissions: Add cascade to creation and deletion

- docs/content/setup/manual-setup.md
docs
This reverts the documentation changes of bf0a7eb. This is necessary as the omitted remarks about `.sequlizerc` can't be omitted until 1.8 is released.
> Docs: Revert changes to manual setup

- .github/workflows/node.js.yml
CI
This PR adds Node.js 16 to our CI pipeline
> CI: Run tests with Node.js 16 [master]

- test/private-api/media.e2e-spec.ts
- test/public-api/media.e2e-spec.ts
- test/utils.ts
E2E tests
Previously, `fs.rmdir` was called multiple times on the same path,
even when the path was already deleted.
This causes test failures in Node 16.
This PR extracts the cleanup code into a utility function
and ensures that no error is thrown when the given path is already deleted.
> Media E2E tests: Add error handling for upload cleanup

- src/config/mock/app.config.mock.ts
app config mock
Until now the app config mock used ts-loader's LogLevel instead of our own Loglevel, which is obviously wrong. This PR fixes that.
> AppConfigMock: Use correct loglevel

- src/media/backends/filesystem-backend.ts
FilesystemBackend
This PR adds a few missing `functionContext` parameters in calls to
`this.logger` and fixes a copy-paste error in `ensureDirectory`
> FilesystemBackend: Fix functionContext logging

- lib/web/imageRouter/imgur.js
- package.json
- public/docs/release-notes.md
- yarn.lock
Imgur media upload
This PR replaces the dependency `node-imgur`.
We use a hackmd fork of "node-imgur" for no reason. The upstream lib is way more advanced and modern.
> Use upstream imgur library

- src/api/private/notes/notes.controller.ts
- src/api/public/notes/notes.controller.ts
- src/media/media-upload.entity.ts
- src/media/media.service.spec.ts
- src/media/media.service.ts
- src/notes/note.media-deletion.dto.ts
- test/private-api/notes.e2e-spec.ts
- test/public-api/notes.e2e-spec.ts
public api, private api
This PR adds a body to the route DELETE /notes/{note} of the public and private api to specify if the associated media uploads of the note should be kept or deleted.
fixes #1065
> API: Add option keep media to DELETE /notes/{note}

- .github/workflows/node.js.yml
- bin/setup
- docs/content/setup/manual-setup.md
- package.json
- public/docs/release-notes.md
package metadata, docs, setup script, CI
As Node 10 will be EOL at April 30th, we should stop supporting
and/or promoting the usage of that version.
See also https://endoflife.date/nodejs
> Raise minimum required Node.js version to 12 [master]

- app.js
- docs/content/dev/api.md
- lib/prometheus.js
- package.json
- public/docs/release-notes.md
- yarn.lock
Metrics
This PR adds a `/metrics` Prometheus endpoint using https://github.com/PayU/prometheus-api-metrics.
The custom stats currently available at `/status` are also available as gauges.
I quickly build this for my internal monitoring, but thought it might be nice to have upstream as well.
I never created any Prometheus metrics before, so feedback on the naming/structure is welcome!
> Add Prometheus endpoint

- src/history/history.service.ts
- src/notes/notes.service.ts
- test/public-api/notes.e2e-spec.ts
services
This PR changes some toDto methods to replace null or undefined with an empty string.
> Services: Ensure null is replaced with an empty string

- docs/content/dev/documentation.md
docs
This PR fixes the mkdocs link the `dev/documentation.md`.
> Docs: Fix mkdocs link

- .gitignore
`.gitignore`
Because the new config is done via the file `.env`, it should not be possible to include it in the git repository.
> Gitignore: Add .env

- .gitignore
- src/frontend-config/frontend-config.dto.ts
- src/frontend-config/frontend-config.service.spec.ts
- src/frontend-config/frontend-config.service.ts
- src/main.ts
Frontend config api call
This PR:
- adds serving of static assets under the relative URL '/public'
- removes the banner fields from the frontend config
- NestJS adds the headers "Last Modified" and "ETag" to asset serving responses.
Therefore all the information we need for the banner are already given by the
file content or the file meta data.
> Remove banner from frontend config

- README.md
README
This PR fixes the broken logo link in README.md
> Fix logo link in README.md

- lib/models/user.js
- package.json
- yarn.lock
password hashing for user accounts
This PR removes the `async-scrypt` polyfill. This polyfill was added because node versions less than 10.5.0 didn't include scrypt support. As we now raised the minimum required version to 12.0.0, this polyfill isn't needed anymore.
> [1.x] Remove unneeded polyfill

- src/config/app.config.ts
- src/frontend-config/frontend-config.service.spec.ts
- src/frontend-config/frontend-config.service.ts
config
As we only use rendererOrigin in the frontend config service, where domain will be used if it is not defined, it makes more sense to move this default behavior to the app config directly. That makes it easier to understand what this variable contains and that it defaults to domain.
> AppConfig: Move default for rendererOrigin to config file

- package.json
- src/seed.ts
seed db
This PR adds a seed script, which invokes src/seed.ts to create a sqlite DB. The DB already contains some objects to manual test with. This ensures that devs easily can spin up a test instance of HedgeDoc and don't need to fumble around with the DB file.
See https://github.com/typeorm/typeorm#creating-a-connection-to-the-database
fixes #1183
> [Project] Add seed script

- .eslintrc.js
- src/api/private/me/history/history.controller.spec.ts
- src/api/private/me/history/history.controller.ts
- src/api/private/notes/notes.controller.spec.ts
- src/api/public/me/me.controller.spec.ts
- src/api/public/notes/notes.controller.spec.ts
- src/history/history.service.spec.ts
- src/history/history.service.ts
- src/notes/notes.service.ts
- test/private-api/history.e2e-spec.ts
history service
This PR reimplements the business logic of the history controllers setHistory method (of the private api) in the history serivce in  a transactional way. This should prevent the problem that the history gets deleted, but a later error in the handling of the list of HistoryEntryImportDto let's the call fail.
fixes #1126
> HistoryService: Add setHistory method 

- public/js/extra.js
markdown renderer / editor
The regex for task lists in 1.x didn't include upper-case x/X letters nor ordered lists (`1. [ ] abc`).
This PR changes the regex to allow both.
For testing, I took this content:
```markdown
+ [ ] abc
+ [x] def
+ [X] ghi
1. [ ] abc
2. [x] def
3. [X] ghi
1) [ ] abc
2) [x] def
3) [X] ghi
```
Fixes #1220
> Fix click handler for numbered task lists

- public/js/lib/editor/utils.js
Editor
A bug in insertOnStartOfLines lead to duplicated text,
if the cursor was not at the start of a line.
This fixes the behaviour of insertOnStartOfLines to always use
the complete first and last line of the selection,
even if they were only partially selected.
Fixes #1231
#1231
> Fix insertOnStartOfLines behaviour

- lib/csp.js
csp.js
The `upgradeInsecureRequests` option of Helmets CSP middleware
was a boolean in Helmet 3, but with Helmet 4,
everything changed to lists.
This PR adjusts the addUpgradeUnsafeRequestsOptionTo
function accordingly.
Closes #1221
See also https://github.com/helmetjs/helmet/tree/v4.6.0/middlewares/content-security-policy
#1221
> Fix upgradeInsecureRequests CSP directive

- lib/config/index.js
config
This makes the behavior consistent with the docs and
saves the user from having to both set
`useSSL` and `protocolUseSSL`.
> Automatically enable protocolUseSSL when useSSL is set

- .babelrc
- package.json
- webpack.prod.js
- yarn.lock
Webpack config
This PR switches the minifier in Webpack from https://github.com/terser/terser to https://esbuild.github.io. esbuild is written in Go and reduces the build time from `54s wall/198s user` to `12s wall/21s user` on my machine. 
> Use esbuild to minify frontend JS

- bin/setup
- docs/content/setup/manual-setup.md
docs
This PR changes the 
Before `yarn build` can be succesfully run, we need to install the devDependencies.
This is necessary, because `bin/setup` does not install the devDependencies…
> Docs: Add mention to install devDependencies

- bin/heroku
Heroku setup script
The connection to Heroku's Postgres instances must use SSL,
but not check the certificate.
This adds the necessary configuration to the Heroku setup script.
Fixes #1245
> Ignore Postgres SSL errors on Heroku

- src/auth/auth-token.dto.ts
- src/auth/auth-token.entity.ts
- src/auth/auth.service.spec.ts
- src/auth/auth.service.ts
AuthToken entity/DTO
As all tokens are valid for a maximum of 2 years, the
validUntil attribute is always populated.
This updates the database schema and the DTO to reflect that.
#1256
> AuthTokenEntity: Make validUntil not nullable

- .eslintrc.js
- eslint-local-rules.js
- package.json
- src/api/private/media/media.controller.ts
- src/api/public/media/media.controller.ts
- src/media/backends/imgur-backend.ts
- src/media/backends/s3-backend.ts
- src/media/backends/webdav-backend.ts
- yarn.lock
This PR adds the custom rule 'correct-logger-context', which ensures, that the correct context is given in any logger statements.
> ESLint: Add custom rule 'correct-logger-context'

- docs/content/dev/db-schema.plantuml
- package.json
- src/notes/note.entity.ts
- src/seed.ts
- yarn.lock
note
This PR removes the shortid form the note.
This is a 1.x relict and isn't used anymore in 2.x. All 1.x shortids will be converted to aliases on migration of 1.x to 2.x.
fixes #1268
> Refactor(note): Remove shortid from note

- public/js/extra.js
Vimeo embedding
Vimeo deprecated the v2 api and recommends to use https://developer.vimeo.com/api/oembed/videos
This PR replaces the used API.
Fixes #1281
> Replace vimeo meta data api

- src/api/public/media/media.controller.ts
- src/api/public/notes/notes.controller.ts
- src/api/utils/fullapi-decorator.ts
Backend
This PR adds a `FullApi` decorator for convenience's sake.
Fixes #1063.
> Add API decorator to reduce clutter

- src/notes/note.entity.ts
- src/notes/notes.service.ts
- src/notes/utils.ts
Note entity
Before this PR, `Note.create()` did not return a complete object,
as the `publicId` property was missing.
This adds the generation of the property to the `create` method and moves the
actual generation code from the `NotesService` to a utility method.
> Move publicId creation to Note.create

- src/api/private/me/history/history.controller.spec.ts
- src/api/private/me/me.controller.spec.ts
- src/api/private/media/media.controller.spec.ts
- src/api/private/notes/notes.controller.spec.ts
- src/api/public/me/me.controller.spec.ts
- src/api/public/media/media.controller.spec.ts
- src/api/public/notes/notes.controller.spec.ts
- src/authors/author.entity.ts
- src/history/history.service.spec.ts
- src/media/media.service.spec.ts
- src/notes/note.dto.ts
- src/notes/notes.service.spec.ts
- src/notes/notes.service.ts
- src/permissions/permissions.service.spec.ts
- src/revisions/edit.dto.ts
- src/revisions/edit.entity.ts
- src/revisions/revision.entity.ts
- src/revisions/revisions.module.ts
- src/revisions/revisions.service.spec.ts
- src/seed.ts
Authorship entity
As we now have a separate Author entity, which holds information
about an author (the color), the Authorship name became confusing.
Edit seems to be a better name, as the entity saves information
about a change in a note.
> Rename Authorship entity to Edit

- docs/content/guides/reverse-proxy.md
Documentation
This PR adds a warning to the reverse proxy documentation regarding cloudflare.
Fixes #1337
> Add Cloudflare warning to the docs

- docs/content/guides/reverse-proxy.md
Reverse Proxy Documentation
The Cloudflare warning has "Requirements on your server" as it's title which is wrong.
This PR removes the explicit title so the theme falls back to "Warning"
> Remove explicit title from cloudflare warning

- CONTRIBUTING.md
CONTRIBUTING.md
This PR fixes the links in CONTRIBUTING.md.
https://community.hedgedoc.org/t/broken-link-in-contributing-md-poeditor/404
> docs: fix links in CONTRIBUTING.md

- docs/content/dev/openapi.yml
This PR fixes the link for more documentation in the OpenAPI spec file.
The old link points to a location in our GitHub repo that doesn't exist anymore.
none
> Fix link in openapi doc

- webpack.prod.js
Webpack config
This PR improves the Webpack config by enabling production source maps (only loaded when the client requests them) and the SplitChunksPlugin. This automatically splits duplicated imports across different entrypoints into their own chunks.
See also https://v4.webpack.js.org/guides/code-splitting/#prevent-duplication
> Webpack: production source maps & split chunks

- lib/csp.js
- webpack.dev.js
Content-Security-Policy
As our webpack config does not use `eval` anymore, after #1368 is merged, we can remove
`unsafe-eval` from our CSP config.
> Remove unsafe-eval from default CSP

- src/notes/utils.spec.ts
- src/notes/utils.ts
public id
This PR fixes the generation of publicIds. It uses 128-bit instead of 128-byte values now.
fix #1386
> fix(publicId): generate 128-bit instead of 128-byte value

- docs/mkdocs.yml
Docs
This PR adds the mattermost guide to the navbar, so that it can be found without using the search xD
> [Docs] Add Mattermost guide to navigation

- public/js/extra.js
Slide example
This PR make anchor links base uri independent by adding the window location to the link URL.
Fixes #1476
> Don't open anchor links in new tabs

- .github/workflows/nest.js.yml
CI config
Node 15 is EOL since 01 Jun 2021.
See https://endoflife.date/nodejs
> CI: Stop running tests with Node.js 15

- app.js
- lib/utils.js
express middlewares
This PR fixes the problem that sessions were created for requests to `/metrics` and `/status`. This is caused by the express-session middleware which is applied to every request going through HedgeDoc.
As the express-session middleware does not have any option to disable session initialization for specific routes, I created a helper middleware that accepts a list of blocked routes and another middleware. If a request matches one of the blocked routes, nothing happens. Otherwise the other middleware is applied to the request.
Fixes #1446
> [1.x] Exclude /metrics and /status routes from session initialization

- lib/models/index.js
migration runtime
This PR improves the error message on failed migrations to include a link to the troubleshooting guide.
Closes #1419
> [1.x] Add help link and short explanation for failing migrations

- lib/web/imageRouter/s3.js
s3 endpoint
According to the AWS documentation there is no situation that there is a dash in `s3-<region>.amazonaws.com`, the correct way is with a dot `s3.<region>.amazonaws.com`
Source: https://docs.aws.amazon.com/general/latest/gr/s3.html
P.S.: Small change, big headache to debug.
> fix(s3): replace dash with dot for s3 endpoint

- docs/content/index.md
docs
This PR fixes some typos in the docs that geeked pointed out in the forum
https://community.hedgedoc.org/t/couple-spelling-errors-on-your-docs-home-page/453
>  docs: fix typos 

- lib/web/imageRouter/filesystem.js
image-upload/filesystem
This patch fixes the swallowing of the actual error message that appears
when a file fails to move, after being uploaded to Hedgedoc on an
instance that is using the upload-method `filesystem` active.
This became apparent when the error messages provided by some users,
where less than helpful.
As a solution the error message of the copy command was added to the
error that is output to the console.
https://community.hedgedoc.org/t/image-upload-fail-docker/439
> fix(image-upload): Fix swallowing of errors for filesystem

- lib/config/utils.js
- public/docs/release-notes.md
git parsing in config utilities
HedgeDoc crashed with
`uncaughtException: ENOENT: no such file or directory`
on startup, when `.git/ref/heads` did not contain
a file for the current branch. This seems to happen
regularly with current Git versions.
This fixes the crash by first trying to use the `git` executable for
getting the current commit SHA (before running our own parsing code)
and introducing a separate check to prevent accessing a nonexistent
file in `.git/ref/heads`.
> Fix crash while getting current git commit

- docs/content/setup/docker.md
Docs
After https://github.com/hedgedoc/container/pull/181 has been merged,
we should now also use PG 13 in the example snippet.
> Docs: Use Postgres 13 in Docker example

- app.js
- public/docs/release-notes.md
DB handling
This is a cherry-pick from https://github.com/hedgedoc/hedgedoc/pull/1228 and needed by https://github.com/hedgedoc/container/pull/186.
This adds retry logic to the initial DB connection on startup.
HedgeDoc now tries connecting to the database up to 30 times, waiting
one second after each try.
This gives a database that was simultaneously started (e.g. via
docker-compose) enough time to get ready to accept connections.
> Automatically retry DB connection on startup

- .github/workflows/node.js.yml
CI config
This PR is best reviewed commit-by-commit.
- It removes Node 15 (EOL)
- Migrates the cache feature to the one integrated into `actions/setup-node`
- Switches to Node 16 for non-matrix jobs
> Various CI updates

- app.js
- public/docs/release-notes.md
Shutdown handler
The shutdown handler calls `checkAllNotesRevision` on a 100 ms
interval. If the database connection is broken, this will return
an error. Previously, this error was effectively ignored and resulted
in an endless loop printing out the error message every 100 ms.
This improves the error handling by terminating the process with a
nonzero exit code when an error was encountered.
> Fix endless loop on shutdown when DB can't be reached

- lib/config/utils.js
Git parsing
The command output contains a line break at the end, which confuses the browser.
This removes that linebreak.
> Fix unescaped line break in `git` output

- public/docs/release-notes.md
- public/js/index.js
- public/js/lib/common/login.js
- public/js/lib/editor/index.js
- public/js/locale.js
Cookie handling in the frontend
This adds the secure flag to all cookies that are set
in the frontend for storing various settings.
If `SameSite=none` is set (like when embedding the instance is allowed),
the `secure` flag is necessary to set any cookie.
> Set secure flag for non-session cookies

- .eslintrc.js
ESLint config
This removes unneeded quotation marks and resets all
rules to their default error state.
Treating them only as warnings is not necessary anymore,
as all warnings fail the CI since 4da68597.
> Cleanup ESLint config

- .github/pull_request_template.md
- CONTRIBUTING.md
Contribution guidelines
To make life easier for the release manager (me),
this introduces changelog snippets to the contribution docs
and the PR template.
> Introduce changelog snippets

- docs/content/faq.md
- docs/content/index.md
- docs/mkdocs.yml
Docs
As more and more technical questions needed to be added to the FAQ, the hedgedoc.org homepage felt like the wrong place for it. This PR moves the technical questions into the documentation and adds some more Q&As. Having the FAQ on the docs page has the added benefit of the FAQ being included in the search.
Closes #1115
> Port over the FAQ page from hedgedoc.org to docs.hedgedoc.org

- public/css/font.css
- public/docs/release-notes.md
font loading
There were several reports([1](https://matrix.to/#/!oaRMJImPLfUnnXzwnN:shivering-isles.com/$aHMBKJA2QiGIkiQwad_9TQR53alK2DvFmvYkg-oNC0w?via=matrix.org&via=kif.rocks&via=matrix.michelson.eu))([2](https://community.hedgedoc.org/t/firefox-no-text-colors-in-editor/437)) of HedgeDoc not looking correctly when having some variants of fonts locally installed which HedgeDoc uses. The only way to fix this for the users was to remove the locally installed font or update them to another variant.
This PR removes the directive to load fonts from the local user's machine when they have the same name. Instead  always the font files from the server will be used.
As we use woff font files which aren't very heavy in terms of file-size, it seems acceptable to fetch them always from the server …
> Ignore local installed fonts

- docs/content/references/hfm.md
HFM Documentation
This PR replaces "HedgeDocMark" in some table headers with "HFM" to match the other tables.
Fixes #1608
> Fix usage of "HFM" in table headers

- README.md
README
This PR updates the link to the demo instance to the page which explains the constraints of the demo (not for production use, cloudflare, ...).
#1532 and hedgedoc/hedgedoc.github.io#149
> Update readme link to explanation page

- src/api/private/notes/notes.controller.ts
- src/revisions/revisions.service.spec.ts
- src/revisions/revisions.service.ts
- test/private-api/notes.e2e-spec.ts
Signed-off-by: Abhilasha Sinha <abhisinha662000@gmail.com>
Backend
This PR adds a new API to purge the history of a note. 
The API deletes all the revisions of a note except the latest one.
#1064
> Add new API to purge note history

- docs/content/dev/private-api-auth.md
docs
This PR adds documentation on private api authentication
> docs: add documentation on private api authentication

- lib/config/buildDomainOriginWithProtocol.js
- lib/config/index.js
- lib/csp.js
- public/docs/release-notes.md
CSP
This PR adds the configured domain to the connect-src csp directive.
> Refactor existing code to add the configured domain to connect-src

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/enhancement_request.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
issue templates
This PR fixes the issue templates by adding a title to each template
> Add missing title property to issue templates

- SECURITY.md
repository documentation
The renaming from CodiMD to HedgeDoc was done before the default branch was changed to develop.
Therefore, the updated security policy only resides in master branch, but not in develop branch.
This PR updates the security policy to match the one in master branch.
none
> Update security.md to match state in master branch

- src/api/private/auth/auth.controller.ts
- test/private-api/auth.e2e-spec.ts
- test/private-api/register-and-login.e2e-spec.ts
- test/test-setup.ts
E2E tests
This is the first PR in a series to replace our current API-route-based E2E-test approach with user-journey-based tests.
This adds E2E tests for creating and managing local accounts.
> Add E2E tests for login and registration

- package.json
- src/config/mock/media.config.mock.ts
E2e tests
This PR implements a simple fix to allow the E2E tests to run concurrently.
Fixes #1644
> Run E2E tests concurrently

- renovate.json
renovate config
This PR changes the Renovate config:
- renovate only runs on weekends
- renovate creates separate PRs for major updates
> Update RenovateBot config

- test/public-api/alias.e2e-spec.ts
alias e2e test
This PR fixes a typo in the alias e2e test
> test: fix test name in alias.e2e-spec.ts

- src/permissions/permissions.service.ts
Permissions Service
The parameters of the permission checking methods were missing a null value for not set user. This is the case if user is not logged in and operating as guest.
> Add missing null in type in permissions service

- app.js
- public/docs/release-notes.md
session handling
Because of seemingly undocumented changes in passport 0.5.0,
passport now crashes on requests to paths without session data.
This removes the session middleware from /status and /metrics, which are
excluded from sessions since 90c5ab08332cf57bc43022c90b0d93bd9c1a9cc7.
Fixes https://github.com/hedgedoc/container/issues/270
> Exclude /status, /metrics from session middleware

- codecov.yml
Codecov config
This should stop Codecov from complaining about low
coverage after only half the tests have finished.
See https://docs.codecov.com/docs/notifications#section-preventing-notifications-until-after-n-builds
> Codecov: Wait for 2 builds to be submitted

- src/identity/session.guard.ts
SessionGuard
express-session always creates an `request.session` object, so only
checking if that exists is not sufficient.
> Correctly check for missing session

- docs/content/dev/2.0.md
- src/auth/auth.service.spec.ts
- src/auth/auth.service.ts
- test/private-api/tokens.e2e-spec.ts
Auth Tokens
Bcrypt hashes are too slow to be validated on every request.
As our tokens are random and have a fixed length, it is reasonable
to use SHA-512 instead.
SHA-512 is recommended by the BSI:
https://www.bsi.bund.de/SharedDocs/Downloads/EN/BSI/Publications/TechGuidelines/TG02102/BSI-TR-02102-1.pdf?__blob=publicationFile
Fixes https://github.com/hedgedoc/hedgedoc/issues/1881
> fix(auth): use sha-512 for auth tokens

- docs/content/dev/2.0.md
- docs/content/dev/getting-started.md
documentation
This PR adds documentation for how to set up HedgeDoc 2.0 for local development.
> Add Docs for getting started with 2.0

- src/frontend-config/frontend-config.dto.ts
- src/frontend-config/frontend-config.service.spec.ts
- src/frontend-config/frontend-config.service.ts
private API -> Frontend-Config
This PR removes the customAuthNames property and redefines the authProviders property of the frontend-config DTO. Instead of a map from auth providers to their enabled-state (boolean), there is now an array that just includes the configured auth providers while also having the identifier and providerName of custom auth providers.
This makes the implementation in the frontend a lot easier.
Closes #1884 
Regarding the "internal" vs "local" see here: https://github.com/hedgedoc/hedgedoc/issues/1515#issuecomment-917688118
> Frontend-Config: Array of enabled auth providers

- src/api/private/auth/auth.controller.ts
- src/identity/identity.service.spec.ts
- src/identity/identity.service.ts
- src/identity/local/local.strategy.ts
- src/identity/local/update-password.dto.ts
- test/private-api/auth.e2e-spec.ts
- test/private-api/register-and-login.e2e-spec.ts
Auth -> internal / "local"
This PR adds a check for the "old" password of the user when requesting a password change.
By checking the "old" password of the user prior to a password change, the password change function is more secured against abuse.
none
> Auth: Require old password for password change

- app.js
logger
This patch disables logging of HTTP requests containing health-check UA from the local IP address. These logs can take up a lot of disk space but are of little use.
#1933
> Fix(logger): Ignore docker health check requests

- CONTRIBUTING.md
CONTRIBUTING.md
This PR adds a sign-off guide to CONTRIBUTING.md
Fixes #1919
> docs: added sign-off guide to CONTRIBUTING.md

- src/api/private/auth/auth.controller.ts
- src/errors/errors.ts
- src/identity/identity.service.spec.ts
- src/identity/identity.service.ts
- src/identity/local/local.strategy.ts
`identityService`
This PR changes error types in `checkLocalPassword` and `updateLocalPassword` to `InvalidCredentialsError` and `NoLocalIdentityError`.
#1936
> Change error types in checkLocalPassword and updateLocalPassword

- lib/letter-avatars.js
- lib/models/user.js
- lib/web/auth/oauth2/index.js
- public/docs/release-notes.md
- test/letter-avatars.js
user avatars
This PR fixes user avatars for OAuth2 which were not based on the email address.
It also adds libravatar's fallback to identicons.
See the commit messages for more details.
https://community.hedgedoc.org/t/oauth2-gravatar-avatars-not-showing-up/544
> Use libravatar image if email address is defined

- src/notes/note-metadata.dto.ts
- src/notes/note-permissions.dto.ts
- src/notes/notes.service.spec.ts
- src/notes/notes.service.ts
- test/public-api/me.e2e-spec.ts
- test/public-api/notes.e2e-spec.ts
API
This PR removes embedded user and group objects from the API
> Do not embed User/Group objects

- .eslintrc.js
- package.json
- src/history/history.service.spec.ts
- test/test-setup.ts
CI, code style
This PR enables ESLint's "strict mode", which fails CI if ESLint returns warnings.
It also fixes the remaining style-issues that caused warnings.
> CI: Do not allow ESLint warnings

- docs/content/guides/auth/authelia.md
Documentation
This PR adds documentation and a working example for setting up OAuth SSO with Authelia ([www.authelia.com](https://github.com/authelia/authelia))
> Documentation & working example for Authelia OAuth SSO

- test/private-api/notes.e2e-spec.ts
- test/public-api/me.e2e-spec.ts
- test/public-api/notes.e2e-spec.ts
- test/utils.ts
e2e tests
fs.rmdir(path, { recursive: true}) is deprecated and
is replaced by fs.rm(path, { recursive: true}).
> Replace fs.rmdir recursive by fs.rm recursive

- app.js
- public/docs/release-notes.md
Logging
This PR adds the specific error message to the log if the database cannot be reached.
> Add error message to log if database cannot be reached

- src/api/private/alias/alias.controller.ts
- src/api/private/auth/auth.controller.ts
- src/api/private/me/history/history.controller.ts
- src/api/private/me/me.controller.ts
- src/api/private/media/media.controller.ts
- src/api/private/notes/notes.controller.ts
- src/api/private/tokens/tokens.controller.ts
- src/api/public/alias/alias.controller.ts
- src/api/public/me/me.controller.ts
- src/api/public/media/media.controller.ts
- src/api/public/monitoring/monitoring.controller.ts
- src/api/public/notes/notes.controller.ts
- src/api/utils/descriptions.ts
- src/api/utils/get-note.interceptor.ts
- src/errors/error-mapping.ts
- src/errors/http-exception-object.ts
- src/identity/identity.service.ts
- src/main.ts
- src/notes/alias.service.ts
- src/notes/notes.service.spec.ts
- src/notes/notes.service.ts
- test/private-api/alias.e2e-spec.ts
- test/private-api/history.e2e-spec.ts
- test/private-api/media.e2e-spec.ts
- test/private-api/notes.e2e-spec.ts
- test/public-api/alias.e2e-spec.ts
- test/public-api/media.e2e-spec.ts
- test/public-api/notes.e2e-spec.ts
- test/test-setup.ts
public and private api
This PR adds an error mapping from internal HedgeDoc Error to HttpExceptions. While doing this I noticed that some error codes are not documented in the openapi docs and added the appropriate annotations. 
Fixes #1983
Fixes #1640
> Add error mapping

- src/errors/error-mapping.ts
- src/main.ts
- test/app.e2e-spec.ts
exception mapping
The constructor of an exception filter must be given
an instance of HttpAdapterHost, otherwise it will crash at runtime.
This can be reproduced by GETing /.
> Correctly initialize exception mapping

- CHANGELOG.md
- LICENSE
- docs/content/dev/public_api.yml
changelog file, license file
This PR changes CodiMD to HedgeDoc on some places where it hasn't been done yet.
none
> Use 'HedgeDoc' instead of 'CodiMD' in changelog and license

- src/api/utils/openapi.decorator.ts
openapi decorator
This now correctly returns the dto if it is provided. Previously it would return () => undefined, when the dto was not defined, which crashed some internal logic in nestjs.
> fix: openapi decorator

- src/utils/session.ts
session middleware
The cookie expiration is taken from the config,
but the expiration date of session data in the database was hardcoded.
This removes the hardcoded value, so TypeormStore defaults
to cookie.maxAge.
References:
https://github.com/nykula/connect-typeorm#options
https://github.com/expressjs/session#cookiemaxage
> fix(session-middleware): don't hardcode database TTL

- src/api/private/groups/groups.controller.ts
- src/api/private/me/me.controller.ts
- src/api/private/private-api.module.ts
- src/api/private/users/users.controller.ts
- src/api/public/me/me.controller.ts
- src/users/user-info.dto.ts
- src/users/users.service.spec.ts
- src/users/users.service.ts
- test/private-api/groups.e2e-spec.ts
- test/private-api/me.e2e-spec.ts
- test/private-api/users.e2e-spec.ts
- test/public-api/me.e2e-spec.ts
- test/test-setup.ts
Private API
This PR adds routes that allow to fetch information about users and groups given their respective names.
> Add APIs to fetch info about Users and Groups

- src/utils/setup-pipes.ts
Validation
For some reason, 2021-me did not send the exact validation error to the client.
I now don't see any reason to not do that, so this PR changes the implementation.
> feat(validation): send error message to client

- src/config/note.config.spec.ts
- src/config/note.config.ts
note config
This PR adds unit tests for the note config.
> test: note config

- .github/workflows/docker-cleanup.yml
- .github/workflows/docker.yml
CI
This PR adds new workflows performing these steps:
- A development docker image is built and pushed to GHCR as
'hedgedoc-ci' labeled with the commit hash
- Tests are run with the image
- If the tests are successful, a production image is built and
pushed to GHCR as 'hedgedoc' labeled with the branch and the version tag if available
- Every day, 'hedgedoc-ci' images older than one day are deleted.
At a later time, the built dev image could also be used to run E2E tests
with the other supported databases. Currently, this is not yet possible,
as the database is always expected to run on localhost, not other hosts.
> CI: build and test docker image

- bin/manage_users
- public/docs/release-notes.md
`bin/manage_users`
This PR fixes #1945 by telling [minimist](https://github.com/substack/minimist) to always treat the `pass` command line option as a string.
It also adds a check for empty passwords and minor code-style improvements.
#1945
> bin/manage_users: Always treat pass argument as string

- public/views/hedgedoc/header.ejs
View mode toggles
This PR tries to improve the screen reader visibility of the view mode toggles by adding some html attributes.
Probably fix https://github.com/hedgedoc/hedgedoc/issues/2125
> Improve aria tags for view mode labels

- public/docs/release-notes.md
- public/js/cover.js
- public/js/fix-aria-hidden-for-modals.js
- public/js/index.js
Modals
This PR fixes the usability of modals when using screen readers by adjusting the `aria-hidden` attribute correctly.
Fixes https://github.com/hedgedoc/hedgedoc/issues/2126
> Force change of aria-hidden when modal shows or hides

- public/.eslintrc.js
- public/docs/release-notes.md
- public/js/index.js
- public/vendor/ot/hex2rgb.js
Frontend JS
The `hex2rgb` function seems to previously have been available globally.
It probably got lost in the great Webpack refactoring and nobody noticed
that.
This copies the function into its own file (to make importing it easy)
and adds an import in index.js.
Fixes https://github.com/hedgedoc/hedgedoc/issues/2248
(https://github.com/hedgedoc/hedgedoc/issues/2248)
> Fix missing inline authorship colors

- lib/csp.js
- lib/response.js
- public/docs/release-notes.md
- public/js/index.js
- test/csp.js
editor -> GitLab snippet export
This PR fixes the GitLab snippet export.
The snippet export broke due to two reasons.
First of all, the request to GitLab fail in the default configuration due to the CSP not being set properly. This commit adds the configured GitLab base url to the connect-src directives. The second problem is a change in the GitLab API spec. Instead of `code` and `file_name` the GitLab API now requires an `files` array with `content` and `file_path` entries per snippet.
Fixes #2208
> Fix GitLab snippet export

- bin/setup
- docs/content/setup/manual-setup.md
Documentation
This patch adds `--frozen-lockfile` to our regular `yarn install` calls
during manual set up. This should ensure people get the expected
versions and not any newer or older versions that might behave
unexpectedly.
References:
https://github.com/yarnpkg/yarn/issues/5847#issuecomment-537521943
https://classic.yarnpkg.com/en/docs/cli/install#toc-yarn-install-frozen-lockfile
> docs(manual): Adjust instructions to use only pinned dependencies

- src/logger/console-logger.service.ts
logging
2467b125 mistakenly applied the sanitize function
to the log messages *after* the color was applied.
This PR reverses the order to un-break colored logs.
> fix(console-logger): don't sanitize colors away

- src/notes/notes.service.ts
notes metadata API
The primaryAddress field of a note contained the internal UUID of the note when no primary alias was defined instead of the public note id.
This PR fixes that by changing the exposed field.
none
> fix(notes): primaryAddress reveals internal UUID

- src/notes/notes.service.spec.ts
This PR moves common mocking code into one function and adds a new test `toNoteMetadataDto`, checking that it returns the publicId when no aliases are present.
> Refactor NoteService unit tests

- docs/content/config/index.md
- src/app.module.ts
- src/config/database-type.enum.ts
- src/config/database.config.ts
- src/config/mock/database.config.mock.ts
- src/logger/console-logger.service.ts
- src/logger/logger.module.ts
- src/logger/typeorm-logger.service.ts
- src/utils/session.ts
- test/app.e2e-spec.ts
AppModule, logging, db config
This PR
- Uses the database from the config in `AppModule`
- Adapts our config options to follow TypeORM terminology
- Adds a logging adapter for TypeORM, which logs queries on the DEBUG level
> Actually use configured database

- .github/workflows/node.js.yml
- bin/setup
- docs/content/setup/manual-setup.md
- package.json
- public/docs/release-notes.md
package metadata, setup script, docs
This PR drops support for Node 12
> [1.x] Drop Node 12

- docs/content/setup/pikapods.md
- docs/mkdocs.yml
Docs/install methods
This PR adds [PikaPods.com](https://www.pikapods.com/) as additional deployment option.
About PikaPods: Our mission is to make great open source apps, like HedgeDoc more accessible and easier to get started with. We already offer HedgeDoc in our “[app store](https://www.pikapods.com/apps#documentation)” after it was requested by users.
So I'm suggesting to add PikaPods as additional install option to run HedgeDoc. This would help an even wider audience to benefit from the project.
- My commits are signed-off to accept the DCO. (cached a wrong name)
None
> Add PikaPods as additional deployment option.

- app.json
Docs -> Setup -> Heroku
This PR fixes the wrong HedgeDoc logo URL in the heroku deployment and ensures that CMD_DOMAIN is set.
closes #2293
> [Docs] Fix heroku missing logo and non-required env var

- lib/migrations/20200321153000-fix-account-deletion.js
- public/docs/release-notes.md
migrations
This patch removes the call of `/usr/bin/env` when calling the migration
script in favour of using the processes own nodejs invocation path.
This should drop the requirement for `/usr/bin/env` to exist on a
system/in a container that runs hedgedoc.
Required for https://github.com/hedgedoc/container/pull/313
> [1.x] fix(migrations): Remove unexpected shell call

- src/revisions/revisions.service.spec.ts
- src/revisions/revisions.service.ts
RevisionService
`getRevisionUserInfo` returned an incorrect list of usernames,
as users who edited a note at multiple places appeared multiple times.
This PR fixes this behavior by deduplicating the author
objects using a Set.
Closes #2180
> fix(revision-service): fix count of duplicate authors

- src/frontend-config/frontend-config.service.spec.ts
FrontendConfig tests
This PR speeds up the FrontendConfig tests by splitting the loops into two parts (testing the auth providers separately) and removing some irrelevant variables.
> Speed up FrontendConfig tests

- .github/workflows/nest.js.yml
CI
This PR removes Node 12 from the CI matrix, as that is EOL since about a month.
> ci: drop Node.js 12

- src/api/private/media/media.controller.ts
- src/api/public/media/media.controller.ts
- src/api/utils/note-header.interceptor.ts
Media APIs routes (both private and public)
This PR is a refactor in the upload file routes. I have followed the issue comments (https://github.com/hedgedoc/hedgedoc/issues/1594#issuecomment-942629384) so I added a guard to find the related note to a new uploaded file and call it in both routes.
Its my first contribution in this project so please help me if I am doing something in a wrong way.
https://github.com/hedgedoc/hedgedoc/issues/1594
> refactor(media-apis): Implement a decorator to convert header to Note instance

- test/app.e2e-spec.ts
E2E test of the `AppModule`
Debug logging seems to have been left enabled accidentally
and is very spammy.
> test(e2e/app): disable debug logging

- src/app-init.ts
- src/main.ts
- test/test-setup.ts
App bootstrap/E2E tests
This allows the E2E tests and the real app to share the same setup.
Fixes #2083
> Extract common app setup code

- docs/content/index.md
docs.
This PR fixes the link on the start page of the docs.
> docs: fixed link to history writeup on index page

- public/docs/release-notes.md
- public/views/hedgedoc/header.ejs
editor view
This PR adds a dark mode toggle for the mobile editor view.
Fixes #2534
> Add dark mode toggle in mobile view

- lib/web/auth/ldap/index.js
- public/docs/release-notes.md
LDAP authentication
Since https://github.com/vesse/node-ldapauth-fork/commit/741a648df98d789856b3301d65103b74872fdeea, ldapauth-fork calls `push` on the attributes array.
Since we deep-freeze our config object in https://github.com/hedgedoc/hedgedoc/blob/master/lib/config/index.js#L200, this causes a crash when the config includes custom `searchAttributes`.
This commit fixes the crash by creating a mutable clone of the LDAP
config and passing that to the LDAP strategy.
Fixes https://github.com/hedgedoc/hedgedoc/issues/2561
https://github.com/hedgedoc/hedgedoc/issues/2561
> Fix crash in LDAP authentication

- public/docs/release-notes.md
- public/js/extra.js
Regex for short code detection of embeddings
This PR replaces embedding shortcode regexes with more specific ones to safeguard against xss attacks.
I used the regex from the new frontend.
> Replace embedding regex with more specific ones

- src/api/private/notes/notes.controller.ts
- test/private-api/notes.e2e-spec.ts
- test/public-api/notes.e2e-spec.ts
private api
This PR adds a get note metadata call to the private api.
fixes #2478
> feat(private-api): add get note metadata call

- src/api/private/tokens/tokens.controller.ts
- src/auth/auth-token.entity.ts
- src/auth/auth.service.spec.ts
- src/auth/auth.service.ts
- test/test-setup.ts
> refactor: Split methods `getAuthTokenAndValidate` and `createTokenForUser`

- src/history/history-entry.entity.ts
- src/history/history.service.spec.ts
- src/history/history.service.ts
- src/history/utils.ts
- src/notes/notes.service.spec.ts
- src/notes/notes.service.ts
- src/permissions/note-group-permission.entity.ts
- src/permissions/note-user-permission.entity.ts
- src/permissions/permissions.service.spec.ts
- src/permissions/permissions.service.ts
- test/private-api/history.e2e-spec.ts
- test/public-api/me.e2e-spec.ts
- test/public-api/notes.e2e-spec.ts
Entities and callers
TypeORM promises to support composite primary keys,
but that does not work in reality.
This replaces the composite key used in the permission entities with
a single generated primary key and
a unique index on the relation columns.
See typeorm/typeorm#8513
> Remove composite primary keys

- docs/content/config/index.md
- docs/content/dev/config.md
- src/config/default-access-permission.enum.ts
- src/config/guest_access.enum.ts
- src/config/mock/note.config.mock.ts
- src/config/note.config.spec.ts
- src/config/note.config.ts
- src/frontend-config/frontend-config.dto.ts
- src/frontend-config/frontend-config.service.spec.ts
- src/frontend-config/frontend-config.service.ts
- src/groups/groups.service.spec.ts
- src/groups/groups.service.ts
- src/notes/notes.service.spec.ts
- src/notes/notes.service.ts
- src/permissions/note-group-permission.entity.ts
- src/permissions/permissions.enum.ts
- src/permissions/permissions.service.spec.ts
- src/permissions/permissions.service.ts
- test/private-api/notes.e2e-spec.ts
- test/public-api/notes.e2e-spec.ts
note services
This PR adds the default permissions to newly created notes.
> feat: add default and create permissions to newly created notes 

- lib/migrations/20220901102800-convert-history-to-longtext.js
- lib/models/user.js
- public/docs/release-notes.md
Database scheme
This PR changes the data type of the history attribute in the user table to long text.
When using mysql the normal text attribute has a fixed size. When this size is reached then the json will be cut off and becomes invalid. The problem doesn't occur when using postgres or sqlite because they already have variable length.
Fixes #2623
> Convert history attribute in user table to long text

- docs/content/setup/manual-setup.md
Docs
Node 18 is not supported because of dependency problems. It's already covered by the package.json but not by the docs.
This PR fixes the docs.
Fixes #2695
> fix(docs): Add a note that node 18 is not supported

- docs/content/dev/events.md
- package.json
- src/app.module.ts
- src/events.ts
- src/history/history.service.spec.ts
- src/media/media.service.spec.ts
- src/notes/alias.service.spec.ts
- src/notes/notes.service.spec.ts
- src/notes/notes.service.ts
- src/permissions/permissions.module.ts
- src/permissions/permissions.service.spec.ts
- src/permissions/permissions.service.ts
- src/realtime/realtime-note/realtime-note.service.ts
- src/realtime/websocket/websocket.gateway.spec.ts
- src/revisions/revisions.service.spec.ts
- test/test-setup.ts
- yarn.lock
event system
This PR adds an event system to HedgeDoc to send events, through the app without the need for tightly coupled services and modules. For now this is used to notify the realtime components of HedgeDoc about note permission changes or deletion.
> feat: introduce event system

- docs/content/dev/getting-started.md
Getting started docs
This PR improves the documentation about getting started with development.
Closes #1669
> docs: correct getting started dev documentation

- .github/workflows/codeql-analysis.yml
CI
This PR skips unnecessary GitHub actions via paths command.
> ci: add paths command to skip unnecessary GitHub actions

- src/api/private/notes/notes.controller.ts
- src/api/public/notes/notes.controller.ts
- src/api/utils/descriptions.ts
- src/api/utils/openapi.decorator.ts
- src/errors/error-mapping.ts
- src/errors/errors.ts
- src/notes/notes.service.spec.ts
- src/notes/notes.service.ts
- test/private-api/notes.e2e-spec.ts
- test/public-api/notes.e2e-spec.ts
note service
This PR adds a note length check on note creation.
> feat: add note length check on note creation 

- src/api/private/notes/notes.controller.ts
note service
This PR fixes the permissions needed to purge all revisions in a note in the public api.
> fix(note): permissions of purgeNoteRevisions

- src/realtime/websocket/utils/extract-note-id-from-request-url.spec.ts
- src/realtime/websocket/utils/extract-note-id-from-request-url.ts
realtime/websocket
This PR fixes the error handling when the url is "/realtime?noteId=".
> Throw error if noteId is empty

- src/config/mock/app.config.mock.ts
- src/config/mock/auth.config.mock.ts
- src/config/mock/customization.config.mock.ts
- src/config/mock/database.config.mock.ts
- src/config/mock/external-services.config.mock.ts
- src/config/mock/media.config.mock.ts
mock configs
This PR changes the mock configs to use a create and register function. This makes it easier to change the config in tests. 
> fix(config-mocks): adapt all mock config to use create and register functions

- src/auth/auth.service.spec.ts
- src/auth/auth.service.ts
- src/history/history.service.spec.ts
- src/history/history.service.ts
- src/media/media.service.spec.ts
- src/media/media.service.ts
- src/utils/test-utils/mockSelectQueryBuilder.ts
Services
Remove all `Equal` in where Clause in `find` to fix #2467.
#2467
> fix: Remove all `Equal` in where Clause in `find`

- docs/content/guides/auth/keycloak.md
Docs
Since Keycloak version 20.0.0 it's needed to explicitly request the openid scope. Since we define it anyway, why not request all the scopes hedgedoc needs to function.
This patch should help to fix people's HedgeDoc deployments.
References:
https://github.com/keycloak/keycloak/pull/14237
https://shivering-isles.com/fixing-hedgedoc-profile-info-keycloak-20
> docs: Fix keycloak guide

- .github/workflows/backend-docker.yml
- .github/workflows/backend-e2e-tests.yml
- .github/workflows/backend-tests.yml
- .github/workflows/frontend-docker.yml
- .github/workflows/frontend-e2e-tests.yml
- .github/workflows/frontend-lint.yml
- .github/workflows/frontend-netlify-deploy-main.yml
- .github/workflows/frontend-netlify-deploy-pr.yml
- .github/workflows/frontend-test-and-build.yml
Github Action
This PR adds a checkout action to the check-changes jobs because otherwise the filter action fails.
> fix(ci): add checkout action into check-changes job

- .github/workflows/backend-docker.yml
CI
The CI runner can't pull an image that doesn't exist because it hasn't been built if no changes have been made to the backend.
This PR changes the workflow to skip the test jobs if no changes have been made. This should be okay because the jobs aren't marked as necessary.
> fix(ci): prevent job run instead of step run

- lib/web/userRouter.js
- package.json
- public/docs/release-notes.md
- yarn.lock
User export
This PR fixes the generation of the user export zip file containing all notes.
Previously, only slashes were replaced but other invalid characters were still kept. This change introduces the `sanitize-filename` package as we don't need to reinvent the wheel for such things.
Fixes #2830
> [1.x] Fix sanitization of filenames in export zip

- backend/src/revisions/revisions.service.spec.ts
- backend/src/revisions/revisions.service.ts
Signed-off-by: Philip Molares <philip.molares@udo.edu>
revsision
This PR fixes the creation of the patch field in the revision.
closes #2857
> feat: add note specific filename for unidiff format in revision patch

- .github/workflows/frontend-e2e-tests.yml
- .github/workflows/frontend-netlify-deploy-pr.yml
CI
This PR fixes a condition in the PR deploy workflow.
> fix(ci): fix conditions in netlify workflow

- .github/workflows/frontend-e2e-tests.yml
- .github/workflows/frontend-netlify-deploy-pr.yml
CI
If a CI run is triggered by `pull_request_target` then `github.ref` is set to the target branch instead of the pull request branch. This causes that CI runs of parallel pull requests are cancelling each other because they have the same concurrency group.
This PR fixes this behaviour by using the pull request meta data for the concurrency group.
> fix(ci): fix concurrency of ci runs if triggered by pull_request_target

- .github/workflows/backend-docker.yml
- .github/workflows/backend-e2e-tests.yml
- .github/workflows/backend-tests.yml
- .github/workflows/frontend-docker.yml
- .github/workflows/frontend-e2e-tests.yml
- .github/workflows/frontend-netlify-deploy-main.yml
- .github/workflows/frontend-netlify-deploy-pr.yml
- .github/workflows/frontend-test-and-build.yml
CI
This PR fixes workflows by:
- Adding pull_request_target event to the backend docker workflow
- Adding the job name to the concurrency groups to prevent accidental cancellation of workflow runs
> Fix workflows

- package.json
- yarn.lock
package.json
This PR adds a package resolution for `@codemirror/autocompletion`
> chore: Add resolution for codemirror/autocompletion

- frontend/src/components/common/links/translated-external-link.tsx
- frontend/src/components/common/links/translated-internal-link.tsx
- frontend/src/components/common/links/types.d.ts
- frontend/src/components/notifications/ui-notification-boundary.tsx
Frontend
This PR fixes type errors in some components that use i18n
> fix(frontend): Fix i18n types

- commons/src/y-doc-message-transporter.ts
- frontend/src/components/editor-page/renderer-pane/hooks/use-send-scroll-state.ts
- frontend/src/components/render-page/window-post-message-communicator/window-post-message-communicator.ts
Frontend & Backend
This PR fixes two crashes. 
- One in the frontend when changing pages which can result in sending the scroll state if the iframe has already been unloaded
- One in the backend that is caused by weird nodejs errors that have worked before :shrug: .
Fixes #3091
> Fix frontend and backend crashes

- frontend/src/components/common/async-loading-boundary/__snapshots__/async-loading-boundary.test.tsx.snap
- frontend/src/components/common/async-loading-boundary/__snapshots__/custom-async-loading-boundary.test.tsx.snap
- frontend/src/components/common/async-loading-boundary/async-loading-boundary.test.tsx
- frontend/src/components/common/async-loading-boundary/async-loading-boundary.tsx
- frontend/src/components/common/async-loading-boundary/custom-async-loading-boundary.test.tsx
- frontend/src/components/common/async-loading-boundary/custom-async-loading-boundary.tsx
- frontend/src/components/common/note-loading-boundary/hooks/use-load-note-from-server.ts
- frontend/src/components/common/note-loading-boundary/note-loading-boundary.tsx
- frontend/src/components/common/user-avatar/user-avatar-for-username.tsx
- frontend/src/components/editor-page/document-bar/revisions/revision-list.tsx
- frontend/src/components/editor-page/document-bar/revisions/revision-viewer.tsx
- frontend/src/components/intro-page/intro-custom-content.tsx
- frontend/src/extensions/extra-integrations/abcjs/abc-frame.tsx
- frontend/src/extensions/extra-integrations/flowchart/flowchart.tsx
- frontend/src/extensions/extra-integrations/graphviz/graphviz-frame.tsx
- frontend/src/extensions/extra-integrations/highlighted-code-fence/highlighted-code.tsx
- frontend/src/extensions/extra-integrations/vega-lite/vega-lite-chart.tsx
- frontend/src/pages/new.tsx
Async Loading Boundary
This PR splits the async loading boundary into one that shows an alert on error and one that shows a custom error.
It also tightens the conditions for components where the async loading boundary is used to prevent race conditions and flakiness of rendering.
> Fix flakiness for async loaded components

- frontend/CHANGELOG.md
- frontend/locales/en.json
- frontend/src/components/editor-page/editor-pane/editor-pane.tsx
Signed-off-by: Lukas Mertens <git@lukas-mertens.de>
Editor
This PR changes the default placeholder to be more user-friendly. As a new user 
> fix(i18n): clarify where to find /features for new users

- backend/src/api/private/media/media.controller.ts
- backend/test/private-api/media.e2e-spec.ts
- dev-reverse-proxy/Caddyfile
- frontend/src/api/media/index.ts
The upload stack™
This PR fixes image uploads by
- improving error handling on empty uploads slightly
- not sending the `Content-Type` header, which confuses multer
- configuring Caddy to proxy the uploads route to the backend
> Fix image uploads

- backend/src/api/private/auth/auth.controller.ts
api/private/auth/local
This PR fixes https://github.com/hedgedoc/react-client/issues/2524
though I have no idea how the auth things work
1. Clear your cookies
2. Visit /register and fill in the form
3. Click "Register"
4. No redirection, just an error message ← problem
5. Visit /login and see you can sign in
With this patch,
4. You will be redirected to /intro and you will see you have signed in
https://github.com/hedgedoc/react-client/issues/2524
> Set the session cookie after registering

- .github/workflows/scorecard.yml
Continuous Integration 
This patch enables a new GitHub action that runs on each commit and updates the HedgeDoc OpenSSF scorecard score, which is a combination of various project best practices that are actively worked on. This should help to stay on top of current best practices and provide transparency for users of HedgeDoc.
> ci: Add OpenSSF scorecard setup

- frontend/src/components/editor-page/editor-pane/tool-bar/formatters/replace-selection.test.ts
frontend test imports
This PR fixes the type import in the `replace-selection.test.ts`.
> fix(frontend): import type from the correct file

- .github/actions/setup-node/action.yml
- .github/workflows/backend-docker-cleanup.yml
- .github/workflows/backend-docker.yml
- .github/workflows/backend-e2e-tests.yml
- .github/workflows/backend-tests.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/commons-lint.yml
- .github/workflows/commons-tests.yml
- .github/workflows/frontend-docker.yml
- .github/workflows/frontend-e2e-tests.yml
- .github/workflows/frontend-lint.yml
- .github/workflows/frontend-netlify-deploy-main.yml
- .github/workflows/frontend-netlify-deploy-pr.yml
- .github/workflows/frontend-test-and-build.yml
- .github/workflows/njsscan-analysis.yml
- .github/workflows/reuse.yml
CI
This PR pins the dependencies of the GitHub actions we use. This is recommended by the OpenSSF and mentioned in numerous alerts of the scorecard tool.
Changes were generated using [StepSecurity SecureWorkflow](https://app.stepsecurity.io/secureworkflow/).
numerous "Code scanning" alerts by scorecard
> misc(ci): pin dependencies of GitHub actions

- frontend/src/components/editor-page/hooks/use-update-local-history-entry.ts
Redux -> History update
When updating the data of a note in the redux, the old state element gets manipulated and will be dispatched again into the state. Redux is not optimized for external state-mutations and has some weird side-effects in that case and sometimes throws an error.
This commit fixes the problem by using a clone of the entry.
none
> fix(redux): avoid state mutation in history redux

- backend/src/logger/console-logger.service.spec.ts
Tests
This PR fixes a wrongly defined loop in the tests for the sanitize method of the console logger.
https://github.com/hedgedoc/hedgedoc/security/code-scanning/20
> fix(tests): syntax for loop in console-logger service

- backend/src/api/private/auth/auth.controller.ts
- backend/src/api/utils/registration-enabled.guard.ts
- backend/src/errors/error-mapping.ts
- backend/src/errors/errors.ts
- backend/test/private-api/auth.e2e-spec.ts
- frontend/locales/en.json
- frontend/src/api/auth/local.ts
- frontend/src/api/auth/types.ts
- frontend/src/components/register-page/register-error/register-error.tsx
backend: error mapping of RegistrationDisabledError
frontend: handling of RegistrationDiabledError and PasswordtToWeakError
This PR fixes/adds/improves/...
fixes #3134
> Frontend does not handle PasswordTooWeakError

- backend/src/api/private/auth/auth.controller.ts
- backend/src/identity/identity.service.ts
- backend/test/private-api/auth.e2e-spec.ts
auth router
This PR fixes the problem that accounts linger when they can't be created probably
fixes #3135
> refactor(backend): don't create local user if password is too weak 

- backend/src/app-init.ts
- backend/src/monitoring/server-status.dto.ts
- backend/src/utils/serverVersion.ts
- backend/src/utils/swagger.ts
- dev-reverse-proxy/Caddyfile
API documentation (Swagger UI)
This PR adds the real version number from the backend to the API docs. To accomplish this easily, the `ServerVersion` class is extended by a new field `fullString` that contains a pre-calculated string representation of the version parts.
Next, the paths of the API docs were slightly changed to be more similar to the actual API base URLs. The new routes are `/apidoc/v2` (for `/api/v2`) and `/apidoc/private` (for `/api/private`).
Finally, the Caddyfile has been extended to proxy the API docs from the backend server.
none
> API documentation (Swagger): Version number + paths

- frontend/src/components/common/note-loading-boundary/create-non-existing-note-hint.test.tsx
- frontend/src/components/common/note-loading-boundary/create-non-existing-note-hint.tsx
frontend test
This PR fixes the create-non-existing-note-hint.test.tsx.
> fix: create-non-existing-note-hint.test.tsx

- frontend/CHANGELOG.md
- frontend/locales/en.json
- frontend/src/components/editor-page/editor-pane/linter/single-line-regex-linter.ts
- frontend/src/extensions/extra-integrations/fork-awesome/fork-awesome-app-extension.ts
- frontend/src/extensions/extra-integrations/optional-app-extensions.ts
Linter
This PR adds a new linter that will tell users that their fork awesome icon is deprecated and will stop working in the future and that they should replace it with a new bootstrap icon.
#2929
> feat(frontend): add fork awesome linter

- SECURITY.md
SECURITY.md
This PR fixes some typos in SECURITY.md and also moves the link to the end of the file for easier reading and changing of urls 
> fix: typo in SECURITY.md

- docs/content/setup/community.md
docs
This PR adds the install method freebsd ports.
Thanks to Dave Cottlehuber.
> docs(setup): add freebsd ports to Community -> Distribution Packages

- SECURITY.md
SECURITY.md
This patch adjust the SECURITY.md to follow a new workflow, which results in reports ending up on GitHub without going through my mailbox, this frees resources on my side as well as reducing the bus factor.
Since most of the time, I do an editorial copy of the content of the E-Mail into GitHub's vulnerability template, this should help to reduce manual processes.
> docs(SECURITY): Shift vulnerability reporting directly to GitHub

- frontend/src/components/common/fields/fields.ts
- frontend/src/components/common/fields/new-password-field.tsx
- frontend/src/components/common/fields/password-again-field.tsx
- frontend/src/pages/register.tsx
Signed-off-by: Avinash <avinash.kumar.cs92@gmail.com>
This PR fixes style for password input error when there is an weak password error
[Fixes issue 3163](https://github.com/hedgedoc/hedgedoc/issues/3163)
> fix(frontend): add error prop to password input

- commons/.eslintrc.cjs
- commons/jest.config.json
- commons/tsconfig-eslint.json
- commons/tsconfig-eslint.json.license
- commons/tsconfig.json
Commons
This PR removes the redundant tsconfig for linting
> fix(commons): remove redundant tsconfig for eslint

- frontend/CHANGELOG.md
- frontend/src/extensions/extra-integrations/asciinema/__snapshots__/asciinema-frame.test.tsx.snap
- frontend/src/extensions/extra-integrations/asciinema/__snapshots__/asciinema-markdown-extension.test.tsx.snap
- frontend/src/extensions/extra-integrations/asciinema/asciinema-app-extension.ts
- frontend/src/extensions/extra-integrations/asciinema/asciinema-frame.test.tsx
- frontend/src/extensions/extra-integrations/asciinema/asciinema-frame.tsx
- frontend/src/extensions/extra-integrations/asciinema/asciinema-markdown-extension.test.tsx
- frontend/src/extensions/extra-integrations/asciinema/asciinema-markdown-extension.ts
- frontend/src/extensions/extra-integrations/asciinema/replace-asciinema-link.test.ts
- frontend/src/extensions/extra-integrations/asciinema/replace-asciinema-link.ts
- frontend/src/extensions/extra-integrations/optional-app-extensions.ts
- frontend/src/extensions/extra-integrations/vimeo/__snapshots__/vimeo-frame.test.tsx.snap
- frontend/src/extensions/extra-integrations/vimeo/vimeo-frame.tsx
- frontend/src/extensions/extra-integrations/youtube/__snapshots__/youtube-frame.test.tsx.snap
- frontend/src/extensions/extra-integrations/youtube/youtube-frame.tsx
Frontend
This PR:
- fixes the ratio calculation of vimeo and youtube embedding
- readds asciinema embeddings
> Fix video embeddings + Add asciinema

- frontend/cypress/e2e/opengraph.spec.ts
- frontend/src/components/editor-page/editor-page-content.tsx
- frontend/src/components/editor-page/opengraph-head/opengraph-head.tsx
Editor page
This PR adds support for the opengraph protocol. Opengraph tags defined in the frontmatter will be inserted into the HTML head.
Closes #2906
> feat(opengraph): add opengraph support

- .github/workflows/frontend-docker.yml
CI
This PR adds the necessary permissions for the CI to push the frontend docker image to GHCR.
> fix(ci): Add write permissions for push of frontend image to ghcr

- frontend/src/extensions/extra-integrations/asciinema/replace-asciinema-link.test.ts
- frontend/src/extensions/extra-integrations/asciinema/replace-asciinema-link.ts
Frontend
This PR simplifies the asciinema regex
> fix(frontend): simplify asciinema regex

- .github/workflows/docker.yml
CI
This PR fixes the docker build-args in the CI workflow.
> fix(ci): fix docker build args

- .github/workflows/docker.yml
Docker image build in CI
This PR separates the docker build into two jobs to speed it up and prevent problems with the github token.
> fix(docker): Separate docker builds into two jobs

- backend/src/realtime/realtime-note/websocket-doc.ts
- commons/src/constants/markdown-content-channel-name.ts
- commons/src/index.ts
- commons/src/y-doc-message-transporter.test.ts
- frontend/src/components/editor-page/editor-pane/hooks/yjs/mock-connection.ts
- frontend/src/components/editor-page/editor-pane/hooks/yjs/use-markdown-content-y-text.ts
Commons, Backend, Frontend
This PR extracts the name of the markdown content yjs channel into the commons package.
> fix(commons): extract name of markdown content yjs channel into the commons package

- .yarn/patches/eventemitter2-npm-6.4.9-ba37798a18.patch
- backend/src/events.ts
- backend/src/notes/notes.service.ts
- backend/src/permissions/permissions.service.ts
- backend/src/realtime/realtime-note/realtime-note.ts
- backend/src/realtime/realtime-note/test-utils/mock-realtime-note.ts
- frontend/src/components/common/note-loading-boundary/hooks/use-load-note-from-server.ts
- frontend/src/components/editor-page/app-bar/help-button/cheatsheet-line.tsx
- frontend/src/components/markdown-renderer/extensions/base/markdown-renderer-extension.ts
- frontend/src/components/markdown-renderer/hooks/use-extension-event-emitter.tsx
- frontend/src/components/render-page/iframe-markdown-renderer.tsx
- frontend/src/components/render-page/window-post-message-communicator/window-post-message-communicator.ts
- frontend/src/extensions/base/app-extension.ts
- frontend/src/extensions/extra-integrations/task-list/task-list-checkbox-app-extension.ts
- package.json
- yarn.lock
Dependencies
This PR adds a yarn patch for eventemitter2 to add generic types.
EventEmitter2 has types, but they're very basic and not very type safe.
I created this patch, because my improved types haven't been merged into the official package.
> Typed event emitter

- renovate.json
Renovate config
Save CI resources by not rebasing unnecessarily
> ci: disable renovate auto-rebase

- backend/src/config/default-access-level.enum.ts
- backend/src/config/mock/note.config.mock.ts
- backend/src/config/note.config.spec.ts
- backend/src/config/note.config.ts
- backend/src/frontend-config/frontend-config.service.spec.ts
- backend/src/notes/notes.service.spec.ts
- backend/src/notes/notes.service.ts
- backend/src/permissions/permissions.service.spec.ts
DefaultAccessLevel & NotesService
This PR contains two refactorings extracted from my WIP E2E-tests branch:
- The `DefaultAccessPermission` enum is renamed to `DefaultAccessLevel`, to reduce confusion between the Permission class and the enum
- `NoteService.createNote` is rejiggled to make it easier to understand, comments are added
> Refactor DefaultAccessLevel & NotesService

- lib/web/imageRouter/index.js
Image Router
This PR fixes the usage of rimraf
> fix(image-router): correct usage of rimraf

- webpack.prod.js
webpack config
Beginning with esbuild-loader 3 it uses iife for web bundles to avoid pollution of the "window" object.
However, this broke our prod (and only the prod!) bundle because some variables should go into the global namespace.
See https://github.com/esbuild-kit/esbuild-loader/releases/tag/v3.0.0
It is important to delete the `public/build` directory before compiling again to see an effect.
> fix(bundle): force esbuild-loader to use cjs instead of iife

- .github/actions/setup-node/action.yml
- .github/workflows/cleanup-cache.yml
- .github/workflows/docker.yml
- LICENSES/CC-BY-4.0.txt
CI / caches
This is concerning:
As we cache the yarn cache and not node_modules, we can safely ignore the node version in the cache key. Furthermore, we probably shouldn't do "max" caching on the docker buildx builds when our space is limited like this.
Because GitHub isolates caches per branch, we also don't need to include a hash of the yarn.lock in the key.
> Improve caching in the CI

- public/docs/release-notes.md
- public/js/index.js
- public/js/lib/appState.js
Night mode toggle
This PR fixes the night-mode toggle by cleaning-up the messy old code a bit.
fixes #3334
> fix(night-mode): migrate cookie solution to store only and simplify code

- frontend/src/components/common/modals/__snapshots__/common-modal.test.tsx.snap
- frontend/src/components/common/modals/__snapshots__/deletion-moadal.test.tsx.snap
- frontend/src/components/common/modals/common-modal.test.tsx
- frontend/src/components/common/modals/common-modal.tsx
- frontend/src/components/common/modals/deletion-modal.tsx
- frontend/src/components/common/motd-modal/motd-modal.tsx
- frontend/src/components/editor-page/app-bar/help-button/help-modal.tsx
- frontend/src/components/editor-page/document-bar/aliases/aliases-modal.tsx
- frontend/src/components/editor-page/document-bar/note-info/note-info-modal.tsx
- frontend/src/components/editor-page/document-bar/permissions/permission-modal.tsx
- frontend/src/components/editor-page/document-bar/revisions/revision-modal.tsx
- frontend/src/components/editor-page/document-bar/share/share-modal.tsx
- frontend/src/components/editor-page/editor-pane/max-length-warning/max-length-warning-modal.tsx
- frontend/src/components/editor-page/editor-pane/tool-bar/table-picker/custom-table-size-modal.tsx
- frontend/src/components/editor-page/sidebar/delete-note-sidebar-entry/delete-note-modal.tsx
- frontend/src/components/history-page/history-toolbar/clear-history-button.tsx
- frontend/src/components/landing-layout/footer/version-info/version-info-modal.tsx
- frontend/src/components/layout/settings-dialog/settings-modal.tsx
- frontend/src/components/markdown-renderer/extensions/image/image-lightbox-modal.tsx
- frontend/src/components/profile-page/access-tokens/access-token-created-modal.tsx
- frontend/src/components/profile-page/access-tokens/access-token-deletion-modal.tsx
- frontend/src/components/profile-page/account-management/account-deletion-modal.tsx
common modal
This PR changes the common modal title via titleI18nKey or title prop
This is mainly needed because we use the common modal to show image light boxes and the title is then the title or alt text of the image
> refactor(frontend): title for common modal via titleI18nKey or title prop

- frontend/global-styles/variables.dark.scss
- frontend/src/components/editor-page/document-bar/revisions/revision-list-entry.module.scss
- frontend/src/components/editor-page/document-bar/revisions/revision-list-entry.tsx
Frontend - Revision list
This PR sets the "action" prop for the revision entry list in the revisions modal. This indicates that the entries should be clickable. This causes that react-bootstrap styles them correctly and uses buttons.
> fix(frontend): use "action" prop in revisions list

- backend/docker/Dockerfile
- frontend/docker/Dockerfile
Dockerfiles
This PR adds and updates the OCI labels for the 2.0 docker images.
Brought to attention by hedgedoc/container#402
> Update OCI labels in 2.0 docker images

- docs/content/references/hfm.md
Documentation
This PR reformats the HFM.md
> fix(docs): reformat hfm.md

- package.json
- yarn.lock
package.json
This PR changes the dependency of codemirror to the master branch because master shouldn't depend on a release branch.
> deps: change codemirror git link to master

- frontend/src/components/editor-page/editor-pane/editor-pane.tsx
- frontend/src/components/editor-page/editor-pane/hooks/code-mirror-extensions/use-code-mirror-spell-check-extension.ts
Editor
This PR extracts the codemirror spell check extension into a separate hook.
> feat(editor): extract the spell check codemirror extension into separate hook

- package.json
Repository
This PR adds a npm task for `test:ci` to the root package.json
> fix(turbo): add npm task for test:ci

- frontend/src/components/common/wait-spinner/wait-spinner.tsx
frontend wait spinner component
This PR adds a size prop to the wait spinner component
Extracted from #3270 to make the PR easier to read.
> feat(frontend): add size property to wait spinner component

- dev-reverse-proxy/package.json
Dev reverse proxy
This PR fixes the reverse proxy start command to prioritize a global caddy over a local.
https://asciinema.org/a/gzQ3DLjU7yj8rAjSin47CuwH3
> fix(dev-reverse-proxy): try to run global caddy first

- .github/workflows/e2e-tests.yml
CI
This PR updates the cypress/browser image in the e2e workflow.
Sadly renovate can't handle this because the image doesn't follow a scheme.
> chore(ci): update cypress/browsers image in e2e workflow

- frontend/next.config.js
Next config
Currently, frontend stack traces are unhelpful in production builds, because they only include minified code.
By enabling source maps for production builds, we enhance debuggability and error-reports.
Ref: https://nextjs.org/docs/advanced-features/source-maps
> build: enable frontend source maps

- frontend/src/components/markdown-renderer/extensions/headline-anchors-markdown-extension.ts
Renderer
This PR fixes the display of the headline link icon
> fix: replace bootstrap icon html with utf-8 icon

- app.js
- lib/web/statusRouter.js
- public/docs/release-notes.md
Healthcheck / status router
This PR adds a dedicated /_health endpoint. This endpoint returns the internal readiness state used by the realtime code to indicate whether HedgeDoc is performing properly. As it only returns the state of a variable, it is less resource hungry compared to a call to /status for checking the health of HedgeDoc.
By prepending the route with an underscore, it should not be conflicting with already created pads in FreeURL mode.
Another PR for the container repository will follow.
#3421
> [1.x] Add /_health endpoint

- backend/src/api/private/auth/auth.controller.ts
- backend/src/api/utils/session-authprovider.decorator.ts
- backend/src/identity/session.guard.ts
- backend/src/realtime/websocket/websocket.gateway.ts
- backend/src/session/session.service.spec.ts
- backend/src/session/session.service.ts
Backend - Session management
This PR changes the type of the session state to prevent unset values when not logged in..
> fix: change sessionstate type to prevent unset values

- frontend/global-styles/markdown-tweaks.scss
- frontend/src/components/markdown-renderer/hooks/use-extract-first-headline.ts
Frontend rendering
This PR fixes the first heading extraction.
> fix: exclude the link icon from the first heading extraction text

- frontend/src/components/editor-page/splitter/splitter.module.scss
- frontend/src/components/editor-page/splitter/splitter.tsx
Frontend splitter
This PR fixes a bug that made it possible to select content while the splitter handle was dragged.
Fixes #3605
> fix: prevent splitter panels from being selected when resizing

- backend/src/api/private/notes/notes.controller.ts
NotesController Private API
This PR fixes a problem in the private permissions api, which was introduced by copy and pasting from the public api
> fix(backend): fix permission routes in NotesController

- frontend/src/components/landing-layout/navigation/user-dropdown.tsx
Landing layout
This PR fixes the links in the user dropdown.
We use a custom component for rendering the link (Dropdown.Item), therefore we need to set both passHref and legacyBehavior
See: https://nextjs.org/docs/api-reference/next/link#if-the-child-is-a-custom-component-that-wraps-an-a-tag
none
> fix(landing-layout): links in the user-dropdown not working

- backend/src/realtime/realtime-note/realtime-user-status-adapter.spec.ts
- backend/src/realtime/realtime-note/realtime-user-status-adapter.ts
- commons/src/message-transporters/message.ts
- frontend/src/components/editor-page/editor-pane/codemirror-extensions/remote-cursors/receive-remote-cursor-view-plugin.ts
- frontend/src/components/editor-page/editor-pane/hooks/yjs/use-receive-realtime-users.ts
- frontend/src/redux/realtime/methods.ts
- frontend/src/redux/realtime/reducers.ts
- frontend/src/redux/realtime/types.ts
Realtime users
This PR adds the own style index when receiving the realtime user state.
> feat: submit own user data on realtime user state set

- frontend/locales/en.json
- frontend/src/components/editor-page/editor-pane/autocompletions/basic-completion.ts
- frontend/src/components/editor-page/editor-pane/autocompletions/regex-completion.ts
- frontend/src/components/editor-page/editor-pane/editor-pane.tsx
- frontend/src/components/editor-page/editor-pane/hooks/codemirror-extensions/use-code-mirror-autocompletions-extension.ts
- frontend/src/components/markdown-renderer/extensions/basic-markdown-syntax/basic-markdown-syntax-app-extension.ts
- frontend/src/components/markdown-renderer/extensions/bootstrap-icons/bootstrap-icon-app-extension.ts
- frontend/src/components/markdown-renderer/extensions/emoji/emoji-app-extension.ts
- frontend/src/components/markdown-renderer/extensions/emoji/mapping.ts
- frontend/src/components/markdown-renderer/extensions/image-placeholder/image-placeholder-app-extension.ts
- frontend/src/components/markdown-renderer/extensions/table-of-contents/table-of-contents-app-extension.ts
- frontend/src/extensions/base/app-extension.ts
- frontend/src/extensions/extra-integrations/abcjs/abcjs-app-extension.ts
- frontend/src/extensions/extra-integrations/alert/alert-app-extension.ts
- frontend/src/extensions/extra-integrations/blockquote/blockquote-app-extension.ts
- frontend/src/extensions/extra-integrations/csv/csv-table-app-extension.ts
- frontend/src/extensions/extra-integrations/flowchart/flowchart-app-extension.ts
- frontend/src/extensions/extra-integrations/graphviz/graphviz-app-extension.ts
- frontend/src/extensions/extra-integrations/highlighted-code-fence/highlighted-code-fence-app-extension.ts
- frontend/src/extensions/extra-integrations/mermaid/mermaid-app-extension.ts
- frontend/src/extensions/extra-integrations/plantuml/plantuml-app-extension.ts
- frontend/src/extensions/extra-integrations/spoiler/spoiler-app-extension.ts
- frontend/src/extensions/extra-integrations/vega-lite/vega-lite-app-extension.ts
Editor -> CodeMirror -> autocompletion extension
This PR adds support for basic autocompletion suggestions in the CodeMirror editor.
closes #2942
> CodeMirror autocompletion

- frontend/src/components/editor-page/sidebar/users-online-sidebar-menu/own-user-line.tsx
- frontend/src/components/editor-page/sidebar/users-online-sidebar-menu/users-online-sidebar-menu.tsx
UsersOnlineSidebarMenu
This PR adds the own user in the UsersOnlineSidebarMenu
> feat(frontend): show own user in UsersOnlineSidebarMenu

- frontend/src/components/editor-page/editor-pane/hooks/use-handle-upload.tsx
- frontend/src/components/layout/settings-dialog/settings-modal.tsx
- frontend/src/components/notifications/ui-notification-boundary.tsx
frontend -> various places
This PR fixes the imports of the t method to use the react-i18next hook in react components.
none
> fix: useTranslation hook in react components

- backend/.eslintrc.js
- eslint-local-rules.js
ESLint
TypeORMs Equal constructor is buggy and should not be used. This introduces a ESLint rule that checks for that.
> build: add eslint rule forbidding TypeORM Equal constructor

- backend/src/api/private/notes/notes.controller.ts
- backend/src/permissions/permissions.service.ts
Backend permission
This PR fixes an error in the private permissions controller
> Fix permission api

- backend/package.json
- backend/tsconfig.json
- yarn.lock
tsconfig
Because of https://github.com/typeorm/typeorm/pull/9884, we need to manually disable useDefineForClassFields
> build: use node18 tsconfig preset

- backend/tsconfig.json
backend dev mode
This PR instructs typescript / nestjs to keep the log output and not clear the terminal.
> fix(backend): keep log output in dev mode

- frontend/src/components/editor-page/editor-pane/codemirror-extensions/remote-cursors/remote-cursor-marker.ts
- frontend/src/components/editor-page/editor-pane/codemirror-extensions/remote-cursors/style.module.scss
frontend -> editor -> remote cursors
This PR fixes the cursor text not being visible when the cursor is at the start of the line.
Additionally, the cursor's font was not defined and therefore was styled in the browser's default font
none
> fix(cursor): cursor text being hidden when at start of line

- backend/src/realtime/realtime-note/realtime-user-status-adapter.ts
- commons/src/message-transporters/message.ts
- frontend/locales/en.json
- frontend/src/components/editor-page/editor-pane/editor-pane.tsx
- frontend/src/components/editor-page/editor-pane/hooks/yjs/use-send-realtime-activity.ts
- frontend/src/components/editor-page/head-meta-properties/hooks/use-has-markdown-content-been-changed-in-background.spec.tsx
- frontend/src/components/editor-page/head-meta-properties/hooks/use-has-markdown-content-been-changed-in-background.ts
- frontend/src/components/editor-page/head-meta-properties/note-and-app-title-head.tsx
- frontend/src/components/editor-page/sidebar/user-line/user-line.module.scss
- frontend/src/components/editor-page/sidebar/user-line/user-line.tsx
- frontend/src/components/editor-page/sidebar/users-online-sidebar-menu/active-indicator.module.scss
- frontend/src/components/editor-page/sidebar/users-online-sidebar-menu/active-indicator.tsx
- frontend/src/components/editor-page/sidebar/users-online-sidebar-menu/own-user-line.tsx
- frontend/src/hooks/common/use-is-document-visible.spec.tsx
- frontend/src/hooks/common/use-is-document-visible.ts
Frontend
This PR adds an indicator to the window title that is visible if the document has been changed while the tab was inactive.
Fixes #3652
> feat(frontend): show indicator in document title for background changes

- frontend/cypress/e2e/intro.spec.ts
- frontend/locales/en.json
- frontend/src/components/editor-page/app-bar/help-button/links-tab-content.tsx
- frontend/src/components/intro-page/cover-buttons/cover-buttons.tsx
- frontend/src/components/landing-layout/navigation/user-dropdown.tsx
frontend
This PR removes the buttons for the "features" page as it won't be part of HedgeDoc 2 anymore. It has been replaced by the cheat sheet and the features page in the docs (#3655).
> misc: remove features page buttons

- frontend/src/components/landing-layout/navigation/sign-out-dropdown-button.tsx
login/logout
This PR adds the missing redirect back to the login page after clicking log out.
none
> fix(logout): redirect to login page

- turbo.json
Turbo
This PR excludes the next.js webpack cache from the turbo output
> fix(turbo): ignore webpack cache

- frontend/src/components/markdown-renderer/extensions/base/event-markdown-renderer-extension.ts
- frontend/src/components/markdown-renderer/extensions/base/markdown-renderer-extension.ts
- frontend/src/components/markdown-renderer/extensions/table-of-contents/table-of-contents-markdown-extension.ts
- frontend/src/components/markdown-renderer/hooks/use-markdown-extensions.ts
- frontend/src/extensions/base/app-extension.ts
- frontend/src/extensions/extra-integrations/task-list/task-list-markdown-extension.ts
Renderer
This PR adds an intermediate class for markdown renderer extensions that require event emitters
> feat(renderer): Add intermediate class for markdown renderer extensions with event emitter

- frontend/src/extensions/extra-integrations/task-list/set-checkbox-in-cheatsheet.tsx
Frontend 
This PR fixes a bug in the checkbox editor component that receive events and should prevent unnecessary run of the effect.
> fix: use callback hook in checkbox editor component to cache function

- .yarn/patches/yjs-npm-13.5.52-a5c64d9068.patch
- package.json
- yarn.lock
YJS Import
This warning should indicate that you mix cjs and mjs imports. While this is a nice feature it has a weird side effect: Jest triggers this check and floods the console every time a test imports yjs.
This happens between all test suites and every time you call `jest.resetModules()`.
Nothing breaks here. Jest does what it should.
Therefore this PR suppresses this warning in test mode.
> fix: suppress yjs double import warning

- .github/workflows/frontend-netlify-deploy-main.yml
- .github/workflows/frontend-netlify-deploy-pr.yml
- renovate.json
Netlify deployment
This PR fixed the netlify deployment by manually installing the nextjs plugin.
> fix deprecated netlify plugin

- frontend/src/components/editor-page/editor-pane/hooks/yjs/use-realtime-connection.ts
Frontend
If you leave the editor without reloading the page then the connection isn't closed properly.
This PR fixes this.
> Disconnect message transporter on editor leave

- backend/src/config/media.config.spec.ts
- backend/src/config/media.config.ts
- backend/src/media/backends/s3-backend.spec.ts
- backend/src/media/backends/s3-backend.ts
- docs/content/config/media/s3.md
S3 backend
The minio lib already handles port fallbacks.
It also expects "endpoint" to be a single host instead of a path. (see https://github.com/minio/minio-js/blob/master/src/main/minio.js#L269)
> improve S3 backend

- .github/workflows/e2e-tests.yml
Frontend e2e Test
Something in our CI setup lets turbo believe that the environment has
changed so much that the build can't be restored from the cache.
Therefore all the cypress jobs are rebuilding the frontend on their own.
It probably has something to do with the fact that the cypress jobs are not
running with the ubuntu image but with the cypress docker image.
I couldn't find out how to fix this, so I changed the CI to use a GitHub
actions artifact.
> fix caching of e2e test

- frontend/locales/en.json
- frontend/src/components/editor-page/document-bar/revisions/revision-list-entry.tsx
Frontend
Only show non-guest users in the sidebar
- This PR targets the correct branch: develop for 2.x
- Signed-off-by: Shan Michel <yuplasmas@gmail.com>
#2953
I was trying to squash all my push and commits with git reset methods and since It reversed all my changes thus my pull request got automatically closed, I'm sorry last pull request got closed: https://github.com/hedgedoc/hedgedoc/pull/3813.
> Only show non-guest users in the sidebar #2953

- frontend/src/components/render-page/renderers/document/document-toc-sidebar.tsx
Renderer
This PR fixes a bug in the TOC button that caused a crash of the application if no TOC was available.
> fix: render toc button only if toc is available

- frontend/global-styles/index.scss
- frontend/src/components/render-page/renderers/document/document-toc-sidebar.tsx
- frontend/src/components/render-page/renderers/document/markdown-document.module.scss
- frontend/src/components/render-page/renderers/document/width-based-table-of-contents.tsx
Frontend
This PR fixes the sticky position of the toc sidebar
> fix: sticky position of toc sidebar

- frontend/src/components/application-loader/application-loader.module.scss
- frontend/src/components/application-loader/loading-screen/loading-screen.tsx
Frontend Loading screen
This PR fixes the loading screen height.
> fix: height of loading screen

- backend/src/api/private/notes/notes.controller.ts
- backend/src/api/public/notes/notes.controller.ts
- frontend/src/api/permissions/index.ts
- frontend/src/api/permissions/types.ts
Backend permission controllers
This PR fixes the body value extraction in the permission controllers
> fix(backend): fix extraction body values in permission controllers

- backend/src/permissions/permissions.service.spec.ts
- backend/src/permissions/permissions.service.ts
- backend/test/private-api/notes.e2e-spec.ts
Backend permissions api
This PR adds e2e tests to the permissions api 
> Permissions e2e tests

- backend/package.json
- backend/src/identity/identity.service.ts
- renovate.json
- yarn.lock
Renovate
This PR updates the zxcvbn packages and adds a new renovate group for them.
> Zxcvbn renovate group

- frontend/src/components/common/custom-branding/__snapshots__/custom-branding.spec.tsx.snap
- frontend/src/components/common/custom-branding/branding.module.scss
- frontend/src/components/common/custom-branding/custom-branding.spec.tsx
- frontend/src/components/common/custom-branding/custom-branding.tsx
- frontend/src/components/editor-page/app-bar/branding.module.scss
- frontend/src/components/editor-page/app-bar/navbar-branding.tsx
- frontend/src/pages/intro.tsx
Branding
This PR refactors the custom branding component to use CSS for the delimiter and adds a test.
> Refactor Custom branding

- frontend/src/components/editor-page/head-meta-properties/note-and-app-title-head.tsx
Note title
This PR removes the parenthesis around `•`, if the note was edited while the user worked in another tab.
This was the way it was in HedgeDoc 1. It was deemed to be better than the parenthesis version in a debug session.
> fix(frontend): remove parenthesis around •

- docs/content/config/media/imgur.md
Docs
This PRi mproves the documentation for the imgur media backend.
Because imgur will delete images 6 month after the last access, we should tell our users about this change to help them make a informed decision about their media backend choice…
see #3942
> docs(imgur): add warning about new imgur policy

- frontend/src/components/editor-page/editor-pane/hooks/yjs/use-on-metadata-updated.ts
Editor
This PR catches an error that can occur when refreshing the note metadata.
> fix(editor): catch error when refreshing note metadata

- backend/src/realtime/realtime-note/realtime-connection.spec.ts
- backend/src/realtime/realtime-note/realtime-connection.ts
- backend/src/realtime/realtime-note/realtime-user-status-adapter.ts
- backend/src/realtime/realtime-note/test-utils/mock-connection.ts
- commons/src/y-doc-sync/y-doc-sync-adapter.spec.ts
- commons/src/y-doc-sync/y-doc-sync-server-adapter.ts
Realtime
This PR makes some changes in the realtime connection class and the y-doc-sync-server-adapter:
- refactors displayName to be readonly because it is set but never changed
- turns the acceptEdits property of the sync adapter into a function and lets it read the value from the realtime connection. This makes the sync adapter a bit more stateless and reduces the number of values for accept edits to the one in the connection class.
- makes acceptEdits in the realtime connection readonly in preparation of #3701
> replace acceptEdits field with function

- .github/workflows/e2e-tests.yml
CI
This PR updates the tag of the used cypress docker image in the CI.
> chore(ci): update cypress browsers image

- backend/src/realtime/realtime-note/realtime-user-status-adapter.spec.ts
- backend/src/realtime/realtime-note/realtime-user-status-adapter.ts
- commons/src/message-transporters/realtime-user.ts
- frontend/src/components/editor-page/editor-pane/codemirror-extensions/remote-cursors/receive-remote-cursor-view-plugin.ts
Realtime
This PR changes the realtime status behavior to show all users in the online list.
> fix(realtime): allow realtime user status updates from users that have read-only access

- docs/content/config/media/imgur.md
docs
This PR fixes the imgur documentation.
> docs: indent imgur warning correctly

- frontend/src/components/layout/settings-dialog/settings-modal.tsx
settings modal
This way the button don't look so strange and this is more like the class is intended.
> fix(frontend): use tabs instead of pills for settings modal

- frontend/src/components/common/new-note-button/new-note-button.tsx
- frontend/src/components/common/redirect.tsx
- frontend/src/pages/new.tsx
new note button
This led to problems, if user clicked the back button in their browser. This implementation doesn't add functional routes in between new notes, but pushes the new note directly in the history.
> fix(frontend): new note button doesn't use /new anymore

- package.json
- yarn.lock
Dependencies
This reverts commit f97cfa6a18abb8b273db0d36f63c26890f71f2a9 because of https://github.com/vercel/turbo/issues/4925 .
> Revert "chore(deps): update dependency turbo to v1.9.4"

- frontend/src/components/application-loader/loading-screen/loading-animation.tsx
- frontend/src/components/common/custom-branding/custom-branding.tsx
- frontend/src/components/common/highlighted-code/__snapshots__/highlighted-code.spec.tsx.snap
- frontend/src/components/common/highlighted-code/highlighted-code.tsx
- frontend/src/components/common/icon-button/__snapshots__/icon-button.spec.tsx.snap
- frontend/src/components/common/icon-button/icon-button.tsx
- frontend/src/components/common/icons/ui-icon.tsx
- frontend/src/components/common/modals/__snapshots__/common-modal.spec.tsx.snap
- frontend/src/components/common/modals/__snapshots__/deletion-moadal.spec.tsx.snap
- frontend/src/components/common/modals/common-modal.tsx
- frontend/src/components/common/renderer-iframe/renderer-iframe.tsx
- frontend/src/components/editor-page/editor-pane/codemirror-extensions/remote-cursors/remote-cursor-marker.ts
- frontend/src/components/editor-page/sidebar/sidebar-button/sidebar-button.module.scss
- frontend/src/components/editor-page/sidebar/sidebar-button/sidebar-button.tsx
- frontend/src/components/editor-page/sidebar/sidebar-menu/sidebar-menu.module.scss
- frontend/src/components/editor-page/sidebar/sidebar-menu/sidebar-menu.tsx
- frontend/src/components/editor-page/sidebar/specific-sidebar-entries/pin-note-sidebar-entry/pin-note-sidebar-entry.tsx
- frontend/src/components/editor-page/sidebar/specific-sidebar-entries/users-online-sidebar-menu/online-counter.module.scss
- frontend/src/components/editor-page/sidebar/specific-sidebar-entries/users-online-sidebar-menu/users-online-sidebar-menu.tsx
- frontend/src/components/editor-page/table-of-contents/__snapshots__/table-of-contents.spec.tsx.snap
- frontend/src/components/editor-page/table-of-contents/table-of-contents.module.scss
- frontend/src/components/editor-page/table-of-contents/table-of-contents.tsx
- frontend/src/utils/concat-css-classes.spec.ts
- frontend/src/utils/concat-css-classes.ts
Frontend utilities
This PR adds a new helper method that creates a css class string from parameters.
> feat: add concat-css-classes helper method

- frontend/src/components/render-page/renderers/slideshow/slideshow-markdown-renderer.tsx
- frontend/src/components/render-page/renderers/slideshow/slideshow.module.scss
Slideshow
This PR fixes the height of the reveal renderer.
> fix: height of reveal rendering

- lib/realtime.js
- public/docs/release-notes.md
Backend (realtime)
This PR fixes that `interruptConnection()` cleans up note state without first checking if other clients are still connected to the note.
The call to `interruptConnection()` in case of a permission error causes the behavior described in #3894. Since `failConnection()` is also called in this case and since it performs the same cleanup as `interruptConnection()`, but with properly checking for other clients, I removed the call to `interruptConnection()`.
It took me some time to understand why the other call to `interruptConnection()` was added in the first place, whether/when it is executed and if it could cause the same problem as the other call:
```js
function finishConnection (socket, noteId, socketId) {
// if no valid info provided will drop the client
if (!socket || …
```
> Fix premature note cleanup on error

- public/docs/release-notes.md
- webpack.common.js
Webpack config
I really don't know why this breaks only in a production build, but this
evil hack makes the script work again.
Closes https://github.com/hedgedoc/hedgedoc/issues/3862
> fix(webpack): give reveal.js's marked.js a 'exports' variable

- .github/workflows/build-and-test.yml
- .github/workflows/lint.yml
- bin/setup
- docs/content/setup/manual-setup.md
- package.json
- public/docs/release-notes.md
- webpack.common.js
Webpack config
Node 18 and newer switched to OpenSSL 3, which does not support the MD4 hash algorithm.
Unfortunately, Webpack 4 hardcodes the use of MD4 at various places. This leaves us no other option than to monkey-patch node to transform calls to the MD4 hash to use SHA256.
References:
https://github.com/webpack/webpack/issues/14532
https://stackoverflow.com/questions/69394632/webpack-build-failing-with-err-ossl-evp-unsupported/69691525#69691525
> Make our Webpack config compatible with Node 18+

- frontend/src/components/render-page/hooks/use-on-height-change.ts
- frontend/src/components/render-page/renderers/document/document-markdown-renderer.tsx
- frontend/src/components/render-page/renderers/simple/simple-markdown-renderer.tsx
Frontend
This PR extracts the common height monitor code from the document and simple markdown renderer into a separate hook.
> refactor: extract height monitor hook

- frontend/cypress/e2e/fileUpload.spec.ts
- frontend/src/components/editor-page/editor-pane/tool-bar/buttons/bold-button.tsx
- frontend/src/components/editor-page/editor-pane/tool-bar/buttons/check-list-button.tsx
- frontend/src/components/editor-page/editor-pane/tool-bar/buttons/code-fence-button.tsx
- frontend/src/components/editor-page/editor-pane/tool-bar/buttons/collapsible-block-button.tsx
- frontend/src/components/editor-page/editor-pane/tool-bar/buttons/comment-button.tsx
- frontend/src/components/editor-page/editor-pane/tool-bar/buttons/header-level-button.tsx
- frontend/src/components/editor-page/editor-pane/tool-bar/buttons/highlight-button.tsx
- frontend/src/components/editor-page/editor-pane/tool-bar/buttons/horizontal-line-button.tsx
- frontend/src/components/editor-page/editor-pane/tool-bar/buttons/image-link-button.tsx
- frontend/src/components/editor-page/editor-pane/tool-bar/buttons/italic-button.tsx
- frontend/src/components/editor-page/editor-pane/tool-bar/buttons/link-button.tsx
- frontend/src/components/editor-page/editor-pane/tool-bar/buttons/ordered-list-button.tsx
- frontend/src/components/editor-page/editor-pane/tool-bar/buttons/quotes-button.tsx
- frontend/src/components/editor-page/editor-pane/tool-bar/buttons/strikethrough-button.tsx
- frontend/src/components/editor-page/editor-pane/tool-bar/buttons/subscript-button.tsx
- frontend/src/components/editor-page/editor-pane/tool-bar/buttons/superscript-button.tsx
- frontend/src/components/editor-page/editor-pane/tool-bar/buttons/underline-button.tsx
- frontend/src/components/editor-page/editor-pane/tool-bar/buttons/unordered-list-button.tsx
- frontend/src/components/editor-page/editor-pane/tool-bar/emoji-picker/emoji-picker-button.tsx
- frontend/src/components/editor-page/editor-pane/tool-bar/formatter-toolbar-button.tsx
- frontend/src/components/editor-page/editor-pane/tool-bar/table-picker/table-picker-button.tsx
- frontend/src/components/editor-page/editor-pane/tool-bar/table-picker/table-picker.module.scss
- frontend/src/components/editor-page/editor-pane/tool-bar/table-picker/table-size-picker-popover.tsx
- frontend/src/components/editor-page/editor-pane/tool-bar/toolbar-button.tsx
- frontend/src/components/editor-page/editor-pane/tool-bar/upload-image-button/upload-image-button.tsx
Editor toolbar
This PR refactors the toolbar. It extracts the visual part of the toolbar buttons so the buttons that dont use a formatter can use it too.
> refactor: extract visual part of the toolbar-button component and use it in all buttons components

- renovate.json
Renovate config
The `config:base` preset does not pin versions in package.json. This switches to the `config:js-app` preset, which enables this feature.
See https://docs.renovatebot.com/presets-config
> Configure Renovate to pin versions

- webpack.common.js
- webpack.prod.js
Webpack config
https://github.com/hedgedoc/hedgedoc/pull/4114
did not properly fix the missing speaker notes.
It turns out that by just excluding `reveal.js/plugin/markdown/marked.js`
from esbuild processing, we can stop invalid JS from being generated.
> fix(esbuild): exclude reveal.js marked plugin

- bin/setup
- public/docs/release-notes.md
setup script
After carefully studying the man pages of GNU sort and BSD sort, we concluded that the `version_lt` function should also work on macOS.
Fixes https://github.com/hedgedoc/hedgedoc/issues/2482
> fix: macOS compatibility for bin/setup

- public/docs/release-notes.md
Release notes
Mention the arm64 image in the release notes
> doc: add note about arm64 to the release notes

- frontend/src/components/common/motd-modal/__snapshots__/motd-modal.spec.tsx.snap
- frontend/src/components/common/motd-modal/motd-modal.tsx
- frontend/src/components/common/renderer-iframe/renderer-iframe.tsx
- frontend/src/components/editor-page/app-bar/cheatsheet/cheatsheet-entry-pane.tsx
- frontend/src/components/editor-page/app-bar/slide-mode-button.tsx
- frontend/src/components/intro-page/intro-custom-content.tsx
- frontend/src/components/render-page/hooks/use-transparent-body-background.ts
- frontend/src/components/render-page/renderers/document/document-markdown-renderer.tsx
- frontend/src/components/render-page/renderers/simple/simple-markdown-renderer.tsx
- frontend/src/components/slide-show-page/slide-show-page-content.tsx
- frontend/src/pages/render.tsx
Mostly just the renderer iframe component
This PR:
- fixes the theme support for slideshows
- fixes the text color for the slideshow button
- adds a prop that indicates if the page load animation OR the wait spinner should be shown in the render iframe.
> Renderer improvements

- .github/workflows/e2e-tests.yml
- renovate.json
CI
The mariadb for e2e tests seems to time out pretty easily which causes multiple CI jobs to just fail. Probably because of the flakiness of github actions.
This PR increases the timeout values.
> ci: pin database docker image versions

- renovate.json
Packages
This PR instructs renovate to also adjust the patched version of yjs.
> chore: adjust patched yjs version

- .github/workflows/reuse.yml
- backend/src/realtime/realtime-note/realtime-note.service.spec.ts
- backend/src/realtime/realtime-note/realtime-note.service.ts
- backend/src/revisions/revisions.service.spec.ts
- backend/src/revisions/revisions.service.ts
Revision persistence
This PR fixes the realtime-note save process. After c25c0fac922facd288e661d2b1de343e0d18bad8 we forgot to adjust the realtime service.
> fix: save created revision on realtime note destroy

- frontend/src/components/common/icons/additional/icon-discourse.tsx
- frontend/src/components/common/icons/additional/icon-gitlab.tsx
- frontend/src/components/common/icons/additional/icon-matrix-org.tsx
- frontend/src/components/editor-page/app-bar/help-button/links-tab-content.tsx
- frontend/src/components/editor-page/sidebar/specific-sidebar-entries/export-menu-sidebar-menu.tsx
- frontend/src/components/editor-page/sidebar/specific-sidebar-entries/import-menu-sidebar-menu.tsx
- frontend/src/components/landing-layout/footer/social-links.tsx
- frontend/src/components/login-page/auth/utils/get-one-click-provider-metadata.ts
Frontend
This PR replaces the placeholder icons for gitlab, matrix.org and discourse with the correct ones.
> feat: replace placeholder icons of gitlab, matrix and discourse

- frontend/src/components/common/icons/additional/icon-discourse.tsx
- frontend/src/components/common/icons/additional/icon-gitlab.tsx
- frontend/src/components/common/icons/additional/icon-matrix-org.tsx
frontend
This PR modifies the additional icon components to forward the remaining SVG properties.
> fix: forward remaining properties in additional icon component

- .github/ISSUE_TEMPLATE/bug_report.yml
Github Issue Template
This PR makes the description in the bug report template into a textarea
> chore(github): make description in bug report use a textarea

- backend/src/main.ts
app init
While the DI and database initialization is running, NestJSs default logger is normally used. Our custom logger was only being initialized after DI setup is complete.
Errors encountered during DI setup were buffered and only printed after DI init was complete, or the app exited on error.
This led to the app not printing anything for a minute in certain cases.
This commit replaces the initial logger with our ConsoleLoggerService that logs everything.
After DI init is complete, that logger is replaced with a normal instance of ConsoleLoggerService that uses the real config from DI.
Fixes https://github.com/hedgedoc/hedgedoc/issues/4306
> fix(backend): immediately use our custom logger

- frontend/src/utils/logger.spec.ts
- frontend/src/utils/logger.ts
Frontend
This PR removes the debug message if the build is running in prod mode.
> fix(frontend): dont log debug messages in production build

- frontend/next.config.js
- frontend/package.json
- frontend/src/utils/test-modes.js
frontend -> analyze flag
When running `yarn analyze`, the produced build will now contain the react profiling metrics to be used with the [react-profiler](https://legacy.reactjs.org/blog/2018/09/10/introducing-the-react-profiler.html#profiling-an-application).
It further enhances the `ANALYZE` env variable to be evaluated less strictly (with our `isPositiveAnswer` matcher).
none
> enhancement: add profiling flag to analyze run

- backend/src/realtime/websocket/websocket.gateway.ts
Backend websocket
The setAdapter function checks if the websocket is closed. If this is the case then an error is thrown and the whole process will be canceled. If the adapter isn't set before the realtime connection object is prepared then the connection will subscribe to all the events and THEN the process will be canceled. Because the MessageTransporter has no adapter (and won't get one), the connection will never get a disconnect event and clean up.
This causes the flood of "cant send message over closed websocket" messages. 
> fix(backend): prevent zombie realtime connections

- frontend/src/components/editor-page/editor-pane/editor-pane.tsx
> fix(frontend): readOnly permits codemirror select text

- .github/workflows/frontend-netlify-deploy-main.yml
CI
This PR fixes a possible command injection in the netlify deployment by manipulating commit messages.
> fix(ci): remove possible command injection in netlify deployment

- dev-reverse-proxy/package.json
- frontend/src/components/common/html-to-react/html-to-react.tsx
- frontend/src/components/markdown-renderer/markdown-to-react/markdown-to-react.tsx
- frontend/src/components/render-page/render-page-content.tsx
- frontend/src/utils/measure-performance.spec.ts
- frontend/src/utils/measure-performance.ts
- package.json
- turbo.json
Renderer
This PR increases the performance of the frontend by using `useDeferredValue`. It's a new hook in React 18 and renders a state change in the background and only renders the result if the browser can handle it right now. If the value changes quickly and often then the result is that not every change is visible.
It also adds performance markers to measure how long the frontend needs to render a markdown text.
> Increase Frontend Performance

- frontend/src/components/register-page/register-infos.tsx
frontend register page
This PR fixes the register page links.
#4416
> fix(frontend): use correct translations for privacy and term of use links

- docs/content/references/yaml-metadata.md
- docs/mkdocs.yml
Documentation
This PR add yaml-metadata documentation to hedgedoc documentaion from public/docs.
https://github.com/hedgedoc/hedgedoc/issues/1427
> doc: Added yaml-metadata doc into hedgedoc frontend

- public/views/index/body.ejs
- public/views/index/head.ejs
Translations
This PR replaces the old slogan with the new one.
https://community.hedgedoc.org/t/and-the-new-slogan-is/1082
> fix: add new slogan

- lib/web/note/controller.js
- lib/web/note/util.js
Router
This PR fixes a bug that creates notes in the presentation router if they dont exist instead of returning a 404.
> fix: don't create notes if not found in presentation route

- lib/web/note/controller.js
- lib/web/note/util.js
Note creation
This PR fixes a bug in the note creation that causes the overwrite of existing notes by using a proper duplication check.
> fix: use better already-exist check in note creation

- backend/src/config/auth.config.spec.ts
- backend/src/config/auth.config.ts
- docs/content/config/index.md
- docs/content/dev/auth/ldap.md
backend
This PR renames `HD_AUTH_LDAPS` to `HD_AUTH_LDAP_SERVERS`
This was done as LDAPS us both the plural of LDAP and the common abbreviation for secure LDAP connections.
Fixes #4460
> refactor: rename HD_AUTH_LDAPS to HD_AUTH_LDAP_SERVERS

- commons/.eslintrc.cjs
- commons/build.sh
- commons/jest.config.json
- commons/package.json
- commons/tsconfig.base.json
- commons/tsconfig.base.json.license
- commons/tsconfig.cjs.json
- commons/tsconfig.cjs.json.license
- commons/tsconfig.esm.json
- commons/tsconfig.esm.json.license
- commons/tsconfig.json.license
- commons/tsconfig.test.json
- commons/tsconfig.test.json.license
- frontend/src/components/editor-page/editor-pane/hooks/yjs/frontend-websocket-adapter.ts
- yarn.lock
Building of commons package
This PR fixes the package generation of the commons package.
The commons package ships wrong types because it is refering to the same files for the ESM and the CJS build.
See https://arethetypeswrong.github.io/?p=%40mrdrogdrog%2Foptional%401.1.0
This happens because microbundle can handle the generation of `.mjs` and `.cjs` from files itself but delegates the generation of types entirely to typescript by running it once. Microbundle uses the "type" field from the package.json to know if a `.js` file is meant to be mjs or cjs and generates the other type by using the specific file extension `.cjs` and `.mjs` (so if your package is a `type: module`, then `.js` file are interpreted as ECMAModule and if you have a commonjs file you need to name it `.cjs`).  But …
> fix(commons): replace microbundle with bash based compile script

- frontend/src/extensions/essential-app-extensions/blockquote/__snapshots__/blockquote-extra-tag-markdown-extension.spec.tsx.snap
- frontend/src/extensions/essential-app-extensions/blockquote/blockquote-color-extra-tag-replacer.tsx
extra color tags
This PR removes the extra color tag in a way that still makes us able to use the color tag in the blockquote
#3734
> fix(blockquote): remove extra color tag

- frontend/src/app/(editor)/[id]/page.tsx
- frontend/src/app/(editor)/layout.tsx
- frontend/src/app/(render)/layout.tsx
- frontend/src/middleware.ts
- frontend/src/utils/base-url-from-env-extractor.spec.ts
- frontend/src/utils/base-url-from-env-extractor.ts
This reverts commit 59bca4a81f668032febba9302b746db556fb7ff8.
The commit in #4155 was only a test and wasn't meant to be included in the final PR.
> Revert "fix: replace class BaseUrlFromEnvExtractor"

- .github/workflows/e2e-tests.yml
- .github/workflows/frontend-netlify-deploy-main.yml
- .github/workflows/frontend-netlify-deploy-pr.yml
- .github/workflows/lint.yml
- .github/workflows/test-and-build.yml
- backend/docker/Dockerfile
- frontend/docker/Dockerfile
- package.json
Turbo
This PR limits the parallel execution of the turbo test tasks. This is necessary to prevent the frontend and backend tests to run in parallel and take a lot of RAM at once.
> Limit test concurrency

- commons/src/utils/deep-partial.ts
- commons/src/utils/index.ts
- frontend/src/test-utils/mock-app-state.ts
- frontend/src/test-utils/mock-note-permissions.ts
Deep Partial type in commons
The deep partial type from redux had the problem that it could only be applied to records. This caused problems with primitive types and arrays.
This PR fixes the type.
> fix: improve deep partial type used in tests

- frontend/src/app/(editor)/@appBar/n/[noteId]/editor-app-bar.tsx
Frontend app bar
This PR fixes the reconnect alert.
The alert is only shown if a note has been loaded.
> fix(frontend): show reconnect alert only if note has been loaded

- .github/workflows/test-and-build.yml
CI
This PR removes Node 16 from the CI.
Fixes https://github.com/hedgedoc/hedgedoc/issues/4788
> ci: remove node 16

- frontend/cypress/support/config.ts
- frontend/src/api/config/types.ts
- frontend/src/components/login-page/guest/guest-card.tsx
- frontend/src/pages/api/private/config.ts
frontend-config
This PR fixes an outdated type in the frontend-config.
none
> fix(frontend-config): use guest access level instead of allowAnonymous

- frontend/cypress/e2e/signInButton.spec.ts
- frontend/src/components/landing-layout/navigation/sign-in-button.tsx
sign-in button
This PR adds the redirectBackTo parameter to the sign-in button
> enhancement(login): add redirectBackTo parameter to login button

- frontend/src/components/common/renderer-iframe/hooks/use-force-render-page-url-on-iframe-load-callback.ts
- frontend/src/components/common/renderer-iframe/renderer-iframe.tsx
- frontend/src/components/render-page/window-post-message-communicator/editor-to-renderer-communicator.ts
- frontend/src/components/render-page/window-post-message-communicator/renderer-to-editor-communicator.ts
- frontend/src/components/render-page/window-post-message-communicator/window-post-message-communicator.ts
- frontend/src/hooks/common/use-timeout-fn.ts
Iframe loading
This PR fixes a double load issue with the renderer iframes.
> Prevent double load of iframes

- backend/src/main.ts
Startup logging
The default log level is 'warning', so we log the final startup message as warning to ensure it is visible by default.
> fix: ensure successful startup is logged

- frontend/locales/en.json
- frontend/src/app/(editor)/login/page.tsx
- frontend/src/components/common/new-note-button/new-note-button.tsx
- frontend/src/components/history-page/entry-menu/entry-menu.tsx
- frontend/src/components/history-page/history-toolbar/history-toolbar.tsx
- frontend/src/components/history-page/history-toolbar/import-history-button.tsx
- frontend/src/components/layout/app-bar/app-bar-elements/user-element.tsx
- frontend/src/components/login-page/guest/guest-card.tsx
- frontend/src/hooks/common/use-is-logged-in.ts
login page, app bar
This PR shows the new note button only when being logged in or guests have the permission to create notes. Also the continue as guest button is now always available to get to the explore page (guests may also read notes).
none
> fix: show new note button only dependent on guest access

- backend/src/config/auth.config.ts
- backend/src/config/csp.config.ts
- backend/src/config/external-services.config.ts
- docs/content/references/config/integrations.md
config
This PR adds error messages for not yet supported config options
> feat(config): warn user about not yet supported config

- frontend/src/components/history-page/entry-menu/entry-menu.module.scss
- frontend/src/components/history-page/history-table/history-table-row.tsx
- frontend/src/components/history-page/pin-button/pin-button.module.scss
history table view
This PR fixes the history table view buttons
> fix: height and width of history table button

- frontend/src/components/editor-page/sidebar/sidebar-button/sidebar-button.module.scss
- frontend/src/components/editor-page/sidebar/sidebar-button/sidebar-button.tsx
- frontend/src/components/editor-page/sidebar/specific-sidebar-entries/export-menu-sidebar-menu.tsx
- frontend/src/components/editor-page/sidebar/specific-sidebar-entries/import-menu-sidebar-menu.tsx
editor sidebar
This PR indicated which feature are not yet supported in the sidebar
> fix(sidebar): indicate that some feature are not yet supported

- frontend/src/components/common/user-avatar/hooks/use-avatar-url.ts
identicon
This PR fixes the import for the identicon module.
none
> fix: use correct import for identicon

- frontend/locales/en.json
- frontend/src/components/editor-page/editor-pane/editor-pane.tsx
editor
This PR shows a notification if user is not allowed to edit note.
> feat(editor): show notification if user is not allowed to edit note

- frontend/src/components/login-page/redirect-to-param-or-history.tsx
logo redirect
This PR fixes the UX when clicking the logo in the editor
> fix: clicking the logo let's the user get back to the note

- frontend/src/components/login-page/local-login/register/local-register-form.tsx
With the previous redirect to the root page, there were some problems when having no other routes in the route history.
This PR fixes this by redirecting to the history page instead.
none
> fix: redirect to history page after register to avoid problems

- docs/content/guides/reverse-proxy.md
Docs
This PR adds a warning about an NGINX configuration pitfall that I fell in. Hopefully it will help others who make my mistake.
N/A
> Docs: Add a warning about an NGINX pitfall and its symptom in HedgeDoc

- frontend/src/components/login-page/guest/guest-card.tsx
login page
This PR fixes the continue as guest button
none
> fix: show guest access button only with relevant config being set

- backend/package.json
- backend/src/realtime/websocket/websocket.gateway.ts
- backend/src/sessions/session.module.ts
- backend/src/sessions/session.service.spec.ts
- backend/src/sessions/session.service.ts
- yarn.lock
Previously, an undefined result in `fetchUsernameForSessionId`
was handled the same way as an error, rejecting the promise.
This fixes the behavior, only rejecting the promise if an error
is returned from the session store and properly returning
undefined if the session store returns that.
> fix(session-service): properly handle session store results 

- frontend/src/components/common/user-avatar/user-avatar.tsx
- frontend/src/components/landing-layout/navigation/user-dropdown.tsx
app bar user menu
This PR removes the tooltip from the user menu in the app bar
> refactor: remove name tooltip from user avatar

- frontend/src/components/editor-page/editor-pane/editor-pane.tsx
codemirror
This PR removes the language highlighting from the editor as it is defect and makes problems with Firefox.
(follows)
> fix(codemirror): remove defect language highlighting

- frontend/src/components/editor-page/editor-pane/editor-pane.tsx
- package.json
- yarn.lock
Editor code highlighting
This PR re-adds the code highlighting in the editor after fixing the codemirror errors.
Closes https://github.com/hedgedoc/hedgedoc/issues/5049
> Readd languages

- frontend/src/components/editor-page/editor-pane/tool-bar/emoji-picker/emoji-picker-popover.tsx
Editor emoji picker
This PR fixes the emoji picker by using an absolute path.
> fix(editor): fix emoji picker data path

- frontend/src/components/editor-page/editor-pane/linter/frontmatter-linter.spec.ts
- frontend/src/components/editor-page/editor-pane/linter/frontmatter-linter.ts
Editor
This PR fixes the broken tag migration in the editor
> fix(editor): fix positions of tag migration lint

- frontend/locales/en.json
- frontend/src/components/editor-page/sidebar/specific-sidebar-entries/note-info-sidebar-menu/note-info-line/note-info-line-updated-at.tsx
API and Frontend
This PR:
- renames "last updated at" to "last saved at" because it actually represents the time when the last revision has been saved
> fix: rename "last updated at" sidebar entry

- .github/workflows/docker.yml
CI
The Docker workflow should now run when tags starting with `v2` are created and push a corresponding image.
> ci: build docker images for tags

- docs/content/files/setup-docker/docker-compose.yml
- docs/content/how-to/reverse-proxy.md
- docs/content/tutorials/setup.md
docs
This PR adjusts the docs for the upcoming alpha release
> docs: add alpha version warning to setup instructions 

- docs/content/faq/index.md
- frontend/src/extensions/essential-app-extensions/fork-awesome-html-tag/fork-awesome-html-tag-app-extension.ts
docs and ForkAwesomeHtmlTagAppExtension
This PR adds the FAQ entry for fork awesome depcreation and adds the correct link to the ForkAwesomeHtmlTagAppExtension component
Fixes #5021
> docs: add faq entry about fork awesome deprecation

- README.md
readme
This PR adds a note about docs.hedgedoc.dev on the readme.
none
> docs: add readme note about docs.hedgedoc.dev

- frontend/src/api/common/api-request-builder/api-request-builder.ts
- frontend/src/components/common/base-url/base-url-context-provider.tsx
- frontend/src/utils/base-url-from-env-extractor.spec.ts
- frontend/src/utils/base-url-from-env-extractor.ts
internal api url
This PR fixes a bug when NOT setting the internal API URL.
If the env var is not set the renderer may use editor URL which can cause problem if they're not the same.
> fix internal api url

- backend/package.json
- backend/src/utils/serverVersion.ts
- docs/package.json
- frontend/package.json
version parsing
This PR fixes/adds/improves/...
> fix: support dots in semver prerelease identifier

- backend/package.json
- frontend/package.json
- yarn.lock
dependencies
This PR changes the specified version from main branch to a specific commit. Hopefully this changes will result in (better) caching of the ts-node package, especially in the GitHub CI. By setting a specific commit, the package is also pinned like all other dependencies and therefore ensures a more predictionable behaviour.
none
> chore(deps): use the same ts-node version in frontend/backend

- frontend/cypress/e2e/permissions.spec.ts
- frontend/cypress/support/visit-test-editor.ts
- frontend/locales/en.json
- frontend/src/components/editor-page/sidebar/specific-sidebar-entries/permissions-sidebar-entry/permissions-modal/hooks/use-get-special-permissions.ts
- frontend/src/components/editor-page/sidebar/specific-sidebar-entries/permissions-sidebar-entry/permissions-modal/permission-entry-special-group.tsx
- frontend/src/components/editor-page/sidebar/specific-sidebar-entries/permissions-sidebar-entry/permissions-modal/permission-entry-user.tsx
- frontend/src/components/editor-page/sidebar/specific-sidebar-entries/permissions-sidebar-entry/permissions-modal/permission-inconsistent-alert.tsx
- frontend/src/components/editor-page/sidebar/specific-sidebar-entries/permissions-sidebar-entry/permissions-modal/permission-modal.tsx
- frontend/src/components/editor-page/sidebar/specific-sidebar-entries/permissions-sidebar-entry/permissions-modal/permission-section-owner.tsx
- frontend/src/components/editor-page/sidebar/specific-sidebar-entries/permissions-sidebar-entry/permissions-modal/permission-section-special-groups.tsx
- frontend/src/components/editor-page/sidebar/specific-sidebar-entries/permissions-sidebar-entry/permissions-sidebar-entry.tsx
- frontend/src/pages/api/private/users/mock.ts
Editor page -> permission modal
This PR adds an alert icon when another permission overrides a permission.
none
> Show alert when permission is overridden by another permission

- frontend/src/extensions/essential-app-extensions/highlighted-code-fence/highlighted-code-fence-app-extension.ts
This PR adds a generic code block autocomplete suggestion before the language-specific entries.
By this the accidental usage of abc music notation as language is prevented.
fixes #5093
> enhancement(autocomplete): add generic code suggestion entry

- frontend/locales/en.json
- frontend/src/components/editor-page/sidebar/specific-sidebar-entries/users-online-sidebar-menu/active-indicator.module.scss
- frontend/src/components/editor-page/sidebar/specific-sidebar-entries/users-online-sidebar-menu/active-indicator.tsx
- frontend/src/components/editor-page/sidebar/specific-sidebar-entries/users-online-sidebar-menu/user-line/user-line.tsx
editor -> sidebar
This PR adds a little guest icon next to the active indicator showing that a user is not logged-in.
Furthermore, the active indicator now has a tooltip explaining it.
none
> feat(sidebar): distinguish guest users visually

- frontend/src/components/notifications/ui-notification-boundary.tsx
- frontend/src/components/notifications/ui-notification-toast.tsx
- frontend/src/components/notifications/ui-notifications.tsx
- frontend/src/test-utils/mock-ui-notifications.ts
UI Notifications
Notifications will be removed from the state after dismissal.
This PR changes the implementation from an array to a Map, as that makes accessing a notification for dismissal or removal more performant.
fixes #4948
> enhancement(notifications): remove from state after dismissal

- frontend/locales/en.json
translations
This PR fixes a wrong i18n key used in the maxLength modal for notes.
fixes #5145
> fix(i18n): wrong translation key for max length

- CONTRIBUTING.md
fix CODE_OF_CONDUCT.md file url , inside CONTRIBUTING.md
contributing.md
This PR fixes the url of CODE_OF_CONDUCT.md file inside  CONTRIBUTING.md
#5129
> fix CODE_OF_CONDUCT.md file url , inside CONTRIBUTING.md

- lib/web/auth/oauth2/index.js
auth/oauth2
This patch adds a try-catch around the rolesClaim extraction to prevent full crashes of HedgeDoc when a user profile is read, that doesn't contain any such claim, which can happen with some IdPs, like Keycloak, that omit the attribute when it's empty.
As a result an authorized user would crash the entire server, which is definitely unintended behaviour. The simply try-catch should resolve the issue and make sure that roles is always defined even if the `extractProfileAttribute` call fails.
> fix(oauth2): Fix crash in rolesClaim extraction

- frontend/build.sh
frontend build script
This PR fixes a small error in the frontend build script.
The extra `api` at the end did lead mv to try to copy the api directory in directory named api. This is not intended behaviour and fails if there is no api directory already.
> fix(frontend): build script error

- frontend/src/components/error-pages/common-error-page.tsx
Frontend
This PR removes the enforced light text color on the error page.
Fix #5189
> fix(frontend): remove light text class from error page

- frontend/src/components/editor-page/sidebar/specific-sidebar-entries/revisions-sidebar-entry/revisions-modal/revision-viewer.tsx
review viewer
This PR fixes the error in review viewer.
#5167
> fix(frontend): error in review viewer

- .github/workflows/e2e-tests.yml
- frontend/build.sh
- frontend/cypress/e2e/motd.spec.ts
- frontend/cypress/support/config.ts
- frontend/locales/en.json
- frontend/src/app/(editor)/layout.tsx
- frontend/src/components/global-dialogs/motd-modal/cached-motd-modal.tsx
- frontend/src/components/global-dialogs/motd-modal/fetch-motd.spec.ts
- frontend/src/components/global-dialogs/motd-modal/fetch-motd.ts
- frontend/src/components/global-dialogs/motd-modal/local-storage-keys.ts
- frontend/src/components/global-dialogs/motd-modal/motd-modal.spec.tsx
- frontend/src/components/global-dialogs/motd-modal/motd-modal.tsx
- frontend/src/components/layout/app-bar/app-bar-elements/help-dropdown/submenues/instance-submenu.tsx
- frontend/src/components/layout/app-bar/app-bar-elements/help-dropdown/submenues/instance/motd-modal-help-menu-entry.tsx
- frontend/src/components/layout/expected-origin-boundary.tsx
- frontend/src/components/motd/motd-context.tsx
- frontend/src/handler-utils/respond-to-matching-request.ts
Motd
This PR changes the loading mechanism of the motd.
It is loaded by a RSC and provided via context to the modals.
This reduces the number of fetches and makes it easier to re-show the motd
> feat(motd): read motd in RSC and provide via context

- frontend/package.json
- yarn.lock
Frontend
See https://github.com/hedgedoc/hedgedoc/issues/5201
> chore(deps): downgrade nextjs to 13.4.19

- backend/package.json
- docs/content/files/setup-docker/docker-compose.yml
- docs/content/how-to/reverse-proxy.md
- docs/package.json
- frontend/package.json
- package.json
package.json & docs
This PR increments the version number to `2.0.0-alpha.2`
> chore: release alpha 2

- backend/package.json
- frontend/package.json
- yarn.lock
update ts-node
This PR updates ts-node to  11.0.0-beta.1
> chore: update ts-node to 11.0.0-beta.1

- public/docs/features.md
- public/docs/release-notes.md
HedgeDoc 1.9.x bundles Mermaid version 9.1.7, which is old enough that current Mermaid syntax will fail to render inside HedgeDoc notes.
Add a pointer to Mermaid 9.1.7 docs, so users of the current stable HedgeDoc know what's actually supported.
https://github.com/mermaid-js/mermaid/blob/v9.1.7/docs/n00b-gettingStarted.md
documentation
#4479, #4894
> Add a reference to Mermaid 9.1.7 documentation

- frontend/src/components/editor-page/sidebar/specific-sidebar-entries/pin-note-sidebar-entry/pin-note-sidebar-entry.tsx
pin note button sidebar
This PR adds a loading state to the pin note button in the sidebar
possible fix for #5028
> fix(pin-button): add loading state

- frontend/src/components/editor-page/editor-pane/codemirror-extensions/document-sync/y-text-sync-view-plugin.ts
- frontend/src/components/editor-page/editor-pane/hooks/table-paste/table-extractor.ts
- frontend/src/extensions/essential-app-extensions/emoji/mapping.ts
- html-to-react/src/utils/convertInlineStyleToMap.ts
- html-to-react/src/utils/mapHtmlAttributesToReactElementAttributes.ts
multiple parts
This PR fixes the usage of reduce
> refactor: use reduce generic type instead of type cast

- docs/content/setup/getting-started.md
- docs/content/theme/styles/hedgedoc-custom.css
docs
This patch drops all references to the disabled HedgeDoc Twitter account.
> chore: Drop twitter from docs

- docs/content/how-to/reverse-proxy.md
2.0 docs
This PR fixes the reverse proxy docs for nginx that say one should set the `Host` header when instead `X-Forwarded-Host` is required.
#5332
> docs: fix reverse-proxy how-to using wrong host header

- README.md
readme
This PR fixes developer document link in readme.
I found out when implementating below PR.
- #5344
> fix(doc): developer document link in readme.

- frontend/src/components/landing-layout/navigation/user-dropdown.tsx
landing-layout navigation
This PR fixes color mode setting of user menu button.
DropdownToggle's default element type is button, so I use `use-outline-button-variant` component.
ref: https://react-bootstrap.netlify.app/docs/components/dropdowns/#dropdowntoggle
- #5086
> fix(frontend): color mode setting of user menu button 

- .github/workflows/lint.yml
- .github/workflows/test-and-build.yml
CI
This PR should fix the lint and test-and-build workflows for external contributors.
> Pull request target for more workflows

- .github/workflows/e2e-tests.yml
CI
This PR fixes the artifact upload of the frontend e2e screenlog.
It's basically https://github.com/hedgedoc/hedgedoc/pull/5381 but because external contributors can't change our CI configuration I've created this PR.
> fix(ci): artifact-upload in e2e tests

- frontend/src/components/editor-page/sidebar/specific-sidebar-entries/aliases-sidebar-entry/aliases-modal/aliases-list.tsx
editor-page sidebar aliases-modal
This PR fixes the error of updating reducer arguments on alias modal.
`#sort` was updating the state object directly, so I changed it to deep copy the object along with troubleshooting.
- error report
- [#5348](https://github.com/hedgedoc/hedgedoc/pull/5348#pullrequestreview-1827138216)
- error detail & troubleshooting
- https://redux.js.org/usage/troubleshooting#never-mutate-reducer-arguments
[#5348](https://github.com/hedgedoc/hedgedoc/pull/5348#pullrequestreview-1827138216)
> fix(frontend): Avoiding updates directly to state objects on alias modal

- docs/content/how-to/develop/frontend.md
docs develop-guide
This PR updates E2E test script name in development guide.
I found out when implementating below PR.
- #5348
> chore: Update E2E test script name in docs

- package.json
- yarn.lock
Dependencies
This PR adds a resolution for the nodes type to fix a version mismatch when compiling without cache.
> deps: pin node types

- .gitignore
.gitignore
This PR add .gitignore rule.
I add cypress test result directory for running local E2E test.
```sh
$ yarn test:e2e
$ git status
On branch develop
Your branch is up to date with 'origin/develop'.
Untracked files:
(use "git add <file>..." to include in what will be committed)
cypress/screenshots/
```
> chore: add cypress test result directory to .gitignore

- frontend/src/components/render-page/renderers/document/document-markdown-renderer.tsx
- frontend/src/components/render-page/renderers/document/document-toc-sidebar.tsx
- frontend/src/components/render-page/renderers/document/width-based-table-of-contents.tsx
render-page document width-based-table-of-contents
This PR replaces baseUrl with consumer/provider in width-based-table-of-contents.
It's a remaining TODO.
- #5035
> refactor: Replace baseUrl with consumer/provider in width-based-table-of-contents

- package.json
- yarn.lock
Turbo
Turbo 1.11 has a breaking change that is incompatible with our self hosted repository.
This causes log messages like
` WARNING  artifact verification failed: Error making HTTP request: HTTP status client error (412 Precondition Failed) for url ([URL])`
> chore(deps): Downgrade turbo

- app.js
- public/docs/release-notes.md
app router -> session creation
When the /_health endpoint for the docker container healthcheck was introduced, it seems that it was forgotten to exclude that route from the session creation. As the healthcheck runs quite periodically, this created a huge amount of session entries in the database.
This PR excludes the route from session creation.
fixes #5429
> fix(router): do not create sessions for /_health

- frontend/package.json
Frontend
Next 14.1 has a bug when specific browser targets are added. I've added https://github.com/vercel/next.js/issues/60909#issuecomment-1905103530 as workaround.
> fix: change frontend browserslist to fix build

- frontend/src/components/editor-page/sidebar/specific-sidebar-entries/permissions-sidebar-entry/permissions-modal/permission-add-entry-field.tsx
- frontend/src/components/editor-page/sidebar/specific-sidebar-entries/permissions-sidebar-entry/permissions-modal/permission-entry-buttons.tsx
- frontend/src/components/editor-page/sidebar/specific-sidebar-entries/permissions-sidebar-entry/permissions-modal/permission-owner-change.tsx
- frontend/src/components/editor-page/sidebar/specific-sidebar-entries/permissions-sidebar-entry/permissions-modal/permission-owner-info.tsx
editor-page sidebar permissions-modal
This PR improves accessibility on permission modal.
The change policy is the same as #5348 .
- #5087
> fix(frontend): improve accessibility on the permissions modal

- .github/actions/setup-node/action.yml
- .github/workflows/docs-netlify-deploy.yml
- .github/workflows/e2e-tests.yml
- .github/workflows/scorecard.yml
- .github/workflows/static-analysis.yml
- .github/workflows/test-and-build.yml
CI
This PR upgrades all pending GitHub actions in one PR with the relevant fixes for the artifacts v4 action.
obsoletes #5499 #5503 #5497 #5495 #5498 #5496
> chore(deps): upgrade github actions

- frontend/locales/en.json
- frontend/src/components/editor-page/sidebar/specific-sidebar-entries/aliases-sidebar-entry/aliases-modal/__snapshots__/aliases-add-form.spec.tsx.snap
- frontend/src/components/editor-page/sidebar/specific-sidebar-entries/aliases-sidebar-entry/aliases-modal/__snapshots__/aliases-list-entry.spec.tsx.snap
- frontend/src/components/editor-page/sidebar/specific-sidebar-entries/aliases-sidebar-entry/aliases-modal/aliases-add-form.tsx
- frontend/src/components/editor-page/sidebar/specific-sidebar-entries/aliases-sidebar-entry/aliases-modal/aliases-list-entry.spec.tsx
- frontend/src/components/editor-page/sidebar/specific-sidebar-entries/aliases-sidebar-entry/aliases-modal/aliases-list-entry.tsx
editor-page sidebar aliases-modal
This PR improves button's visibility and operability on the aliases modal.
Please see [here](https://github.com/hedgedoc/hedgedoc/issues/5087#issuecomment-1888830319) for detailed discussion.
- ➕ Add alias button
- The operation that users most want to do on this modal.
- → use primary variant 🟢 
- ⭐ Set primary alias button
- The operation that users want to do next on this modal.
- → use secondary variant ⚪️
- → if it's primary alias, renders a badge instead of a button.
- ❌ Remove alias button
- Removing is dangerous operation. (but a little dangerous in the case of this modal)
- → use danger variant 🔴  
- …
> fix(frontend): improves button's visibility and operability on the aliases modal

- backend/src/realtime/realtime-note/realtime-note.spec.ts
- backend/src/realtime/realtime-note/realtime-note.ts
Backend realtime note
This PR adds a timer before `RealtimeNote` gets deleted.
- adds 3 seconds lifetime to `RealtimeNote` without clients
- prevents from creating revision even if the last user reloads the screen
Please see issue #3608 for details.
- #3608
> chore(backend): Add timer berfore deleting realtime note

- frontend/global-styles/github-markdown.scss
- frontend/src/components/application-loader/loading-screen/loading-screen.tsx
- frontend/src/components/editor-page/sidebar/sidebar-button/sidebar-button.module.scss
- frontend/src/components/editor-page/sidebar/sidebar-menu-info-entry/sidebar-menu-info-entry.module.css
- frontend/src/components/editor-page/sidebar/specific-sidebar-entries/export-menu-sidebar-menu.tsx
- frontend/src/components/editor-page/sidebar/specific-sidebar-entries/import-menu-sidebar-menu.tsx
- frontend/src/components/editor-page/sidebar/specific-sidebar-entries/note-info-sidebar-menu/note-info-sidebar-menu.tsx
- frontend/src/components/editor-page/sidebar/specific-sidebar-entries/users-online-sidebar-menu/users-online-sidebar-menu.tsx
* frontend -> loading screen
* frontend -> renderer
* frontend -> sidebar
This PR fixes:
* the loading screen rendering an empty error box when no error is present (it should be hidden instead)
* table columns in the renderer being as small as possible, resulting in massive line-breaks
* visual accessibility for links in the renderer
* double borders on sidebar menus
fixes #5085
fixes #2918
> Style fixes

- frontend/src/components/common/html-to-react/__snapshots__/html-to-react.spec.tsx.snap
- frontend/src/components/common/html-to-react/html-to-react.spec.tsx
- frontend/src/components/common/html-to-react/html-to-react.tsx
renderer -> sanitization
This PR allows custom URI protocols to be used as link targets except for script ones like `javascript:` or `vbscript:`.
Safety considerations: Allowing links to other registered protocols is not much more problematic than linking to arbitrary websites. The important part is that browsers should not execute code in the link in the page context. Currently the only protocol capable of this is `javascript:`. Older versions of MSIE allowed also `vbscript:`, but this is not that relevant for HedgeDoc. To be on the safe side this change blocks all URI protocols ending in script.
Having an allow-list is much harder as this puts the decision about the safety of other protocols into our hands, although we can't assess them. If we just allow one scheme but not another, one …
> Allow custom uri protocols in links except for scripts

- backend/src/auth/auth.service.spec.ts
- backend/src/auth/auth.service.ts
- backend/test/private-api/tokens.e2e-spec.ts
backend -> auth -> API tokens
This PR adds a `hd2.` prefix to API tokens. This has the following benefits:
- HedgeDoc API tokens are more easily recognizable by a user e.g. in their clipboard history
- secret scanning solutions could be used to find accidentally published API tokens
- if future HedgeDoc versions have a new token format but need to keep backward-compatibility, the prefix can be used for distinguishing.
Prefixing API tokens is a common thing done for example by [GitHub](https://github.blog/2021-04-05-behind-githubs-new-authentication-token-formats/) or [GitLab](https://docs.gitlab.com/ee/security/token_overview.html#token-prefixes) as well. As neither the instance domain, associated account nor any more information is included this does not weaken its security and [not …
> API tokens: add prefix and more strict validation

- backend/src/history/history.service.spec.ts
backend history
This PR completes the remaining test TODO on HistoryService.
- #2799
> test(backend): complete the remaining test TODO on HistoryService

- backend/src/notes/alias.service.spec.ts
- backend/src/notes/alias.service.ts
- backend/src/notes/notes.service.spec.ts
- backend/src/notes/notes.service.ts
- backend/test/private-api/notes.e2e-spec.ts
- backend/test/public-api/notes.e2e-spec.ts
notes service
This PR adds a check to `createNote` to prevent creating new notes with an alias equal to an existing note ID.
> feat(api/notes): prevent creating new notes with alias equal to an existing note ID

- lib/web/imageRouter/minio.js
- public/docs/release-notes.md
image router -> minio
A change in the minio JS SDK resulted in uploads being stored with a defect metadata object in minio, resulting in all files served as application/octet-stream.
This was caused as the fifth argument to [putObject](https://min.io/docs/minio/linux/developers/javascript/API.html#putObject) is a metadata object and not the content-type alone anymore.
This PR fixes that.
none
> [1.x] Fix Minio uploads having defect metadata

- docs/content/references/hfm.md
documentation
This PR just fixes a typo: defition --> definition
> Fix typo in documentation about HFM

- frontend/src/components/global-dialogs/motd-modal/fetch-motd.ts
- frontend/src/utils/base-url-from-env-extractor.ts
frontend -> motd
The motd.md is user-supplied and should therefore not be prebuild during the HedgeDoc build process. As that required the presence of the base URL which is also not available in the build context, it fell back to our fallback value example.org, thus breaking offline builds. By removing the example.org domains and disabling the prebuild for the motd, this seems fixed.
1. `git clone --depth=1 -b fix/base-urls-example-org https://github.com/hedgedoc/hedgedoc.git`
2. `cd hedgedoc`
3. `yarn install`
4. `nmcli networking off`
5. `yarn build` -> should work
6. `nmcli networking on`
fixes #5527
> fix(frontend): do not hardcode example.org, do not prebuild motd

- backend/src/realtime/realtime-note/realtime-note.service.ts
- backend/src/realtime/realtime-note/realtime-note.spec.ts
- backend/src/realtime/realtime-note/realtime-note.ts
backend -> realtime processing
When the frontend is notified about metadata updates, it refreshes the data and therefore refreshes information like the timestamp of the last revision save in the sidebar.
This PR adds such a notification from the backend to all clients on each revision save, so that the "last saved at" value in the frontend is correct.
fixes #3657
> enhancement(realtime): send metadata update on revision save

- public/docs/release-notes.md
- public/js/extra.js
renderer
This PR fixes the duplicated headings for screen readers.
Because screen readers don't know that the anchor icon is not meant to be read,
they might read the title (which is the same as the heading itself) in addition
to the heading, thus causing a duplicated output.
fixes #5589
> [1.x] Fix screen readers announcing headings twice

- .reuse/dep5
- backend/src/revisions/__snapshots__/revisions.service.spec.ts.snap
- backend/src/revisions/revisions.service.spec.ts
- backend/src/revisions/revisions.service.ts
backend revision
This PR fixes the following feature's bug.
```javascript
/**
* @async
* Purge revision history of a note.
* @param {Note} note - the note to purge the history
* @return {Revision[]} an array of purged revisions
*/
async purgeRevisions(note: Note): Promise<Revision[]> {
```
If we delete all revisions except the latest one, we need to update the patch column of the latest one.
- https://github.com/hedgedoc/hedgedoc/pull/5349#issuecomment-1913119203
> fix(backend revision): Update patch column when removing revisions

- package.json
Run config
This PR fixes the run configs, because turbo now removes non specified environment variables we need to specify --env-mode explicitly as loose
> fix: turbo env

- dev-reverse-proxy/package.json
caddy run config
This PR improves the caddy run config.
We should use the most specific caddy first and go to more general caddy executables as is the norm and expected from systems in general.
> fix: caddy candidate order

- frontend/next.config.js
frontend build script
The urls are not https://example.org since https://github.com/hedgedoc/hedgedoc/pull/5598 and this message should have been changed then as well.
> fix(frontend): build messages

- frontend/src/extensions/essential-app-extensions/emoji/emoji-app-extension.ts
frontend
This PR fixes an issue with the emoji autocompletion by adding an empty entry to the emoji autocompletion which allows us to press enter to continue without any random emojis in the note where we did not intend them.
Fixes #5251
> fix: prevent emoji autocomplete

- commons/src/frontmatter-extractor/extractor.spec.ts
- commons/src/frontmatter-extractor/extractor.ts
- commons/src/frontmatter-extractor/types.ts
- frontend/src/components/editor-page/editor-pane/linter/frontmatter-linter.ts
- frontend/src/components/render-page/renderers/document/document-markdown-renderer.tsx
- frontend/src/extensions/essential-app-extensions/extract-first-headline/extract-first-headline-node-processor.ts
- frontend/src/redux/note-details/build-state-from-updated-markdown-content.ts
headline extractor
This PR fixes the headline extractor.
If one wrote a frontmatter the incomplete ending dashes where interpreted as a headline and therefore the last line in the frontmatter was handled as the first heading of the document.
> fix: frontmatter headline

- backend/package.json
- yarn.lock
backend -> dependencies
Due to failing docker builds it was brought to our attention, that the backend relied on the uuid package without declaring it as dependency. This worked in all development and build scenarios as the frontend declares uuid as dependency already and top-level `yarn install` installs all dependencies from all workspaces. However as the docker build only runs for either the backend or the frontend, this failed.
This PR adds the dependency to the backend as well.
none
> fix(packages): backend was missing uuid package

- frontend/global-styles/github-markdown.scss
- frontend/global-styles/index.scss
- frontend/src/components/common/highlighted-code/highlighted-code.module.scss
- frontend/src/components/editor-page/sidebar/style/sidebar.module.scss
frontend -> styles
The dark-mode selector changed from the class "dark" attached to the body element to a data-attribute with some react-bootstrap upgrade. This PR reflects this change in our custom css.
fixes #5550
> Use correct dark-mode selector in css

- frontend/src/components/common/user-avatar/__snapshots__/guest-user-avatar.spec.tsx.snap
- frontend/src/components/common/user-avatar/__snapshots__/user-avatar.spec.tsx.snap
- frontend/src/components/common/user-avatar/guest-user-avatar.spec.tsx
- frontend/src/components/common/user-avatar/guest-user-avatar.tsx
- frontend/src/components/common/user-avatar/user-avatar-for-username.tsx
- frontend/src/components/common/user-avatar/user-avatar.spec.tsx
- frontend/src/components/common/user-avatar/user-avatar.tsx
- frontend/src/components/editor-page/sidebar/specific-sidebar-entries/permissions-sidebar-entry/permissions-modal/permission-owner-info.tsx
* permissions -> owner
* user profile pictures
This PR fixes two issues related to user avatars:
- for most user info components, the profile picture is not correctly displayed
- for notes without an owner (anonymously created), the owner section is empty
fixes #5791
> Show correct user avatar pictures and for guests owners

- frontend/locales/en.json
translation
The url the placeholder text linked to is not accurate anymore and needed to be changed. Also the "Happy hacking" part seemed outdated so we changed it to "Let the ideas grow" in accordance with the new slogan of HedgeDoc
> fix(translation): change the placeholder text

- README.md
readme
This patch drops X link for already suspended account.
It's actually linked to mastodon's account.
- #5338
> chore: Drop X (Twitter) from README

- backend/src/notes/__snapshots__/notes.service.spec.ts.snap
- backend/src/notes/notes.service.spec.ts
- backend/src/revisions/__snapshots__/revisions.service.spec.ts.snap
- backend/src/revisions/revisions.service.spec.ts
- frontend/src/components/editor-page/sidebar/specific-sidebar-entries/revisions-sidebar-entry/revisions-modal/__snapshots__/invert-unified-patch.spec.ts.snap
- frontend/src/components/editor-page/sidebar/specific-sidebar-entries/revisions-sidebar-entry/revisions-modal/invert-unified-patch.spec.ts
test
This PR replaces all existing embedded(inline) snapshots with normal(file) snapshots.
- https://github.com/hedgedoc/hedgedoc/pull/5574#discussion_r1614953408
- https://github.com/hedgedoc/hedgedoc/pull/5349#discussion_r1614960141
> refactor(test): Replace inline snapshot with file snapshot

- backend/src/api/private/auth/oidc/oidc.controller.ts
- backend/src/identity/oidc/oidc.service.ts
- backend/src/sessions/session.service.ts
Auth/OIDC
While integrating HedgeDoc 2 with Authelia, I encountered an invalid_state error from Authelia. This is because HedgeDoc 2 does not use state during OIDC authorization. Honestly, I'm not very familiar with OIDC, but from my understanding, implementing both PKCE and [state](https://arc.net/l/quote/ogpluvht) is a good security practice. Therefore, I created this PR.
- Added / updated tests (Perhaps implemented by #5792)
My commits are signed-off to accept the DCO.
This PR targets the correct branch: master for 1.x & docs, develop for 2.x
None
> Feat: Add OIDC state parameter

- lib/web/auth/oauth2/index.js
- public/docs/release-notes.md
- yarn.lock
auth/oauth2
This PR fix the issue https://github.com/hedgedoc/hedgedoc/issues/5521 .
If `parseProfile` function throw an error (in example with the bug mentionend in the issue) it will show an error message in the browser and will not crash. 
Its just a new try/catch
https://github.com/hedgedoc/hedgedoc/issues/5521
> fix(oauth2): Fix crash when profile fields are missing

- html-to-react/src/utils/convertInlineStyleToMap.ts
react-to-html
Fixes incorrectly splitted statements in inline css that contain non-delimiting `;` characters.
Fixes #5839
> fix: use more complex parsing for inline css statement splitting

- html-to-react/src/utils/convertInlineStyleToMap.spec.ts
html-to-react library 
This PR adds tests for the new convertInlineStyleToMap method in the html-to-react library
> test: add tests for convertInlineStyleToMap

- html-to-react/src/utils/convertInlineStyleToMap.ts
react-to-html
fixes incorrectly transformed inline css custom properties
fixes #5596
> fix: ellide css custom properties when converting css inline styles to map

- lib/csp.js
- public/docs/release-notes.md
CSP
For embedded mermaid images `img-src: data:` has to be included in the CSP Header.
> fix(csp): allow 'data:' images in pads

- frontend/global-styles/markdown-tweaks.scss
frontend
If a task in a markdown todo list has multiple lines, the checkbox is now correctly placed at the first line and not the last line.
#5907
> feat(frontend): Correctly align todo list checkbox

- public/docs/release-notes.md
We don't want to mix security fixes with major dependency updates, so this release will still work with v18, but the next one won't support it anymore.
release notes
This PR adds a deprecation warning for node v18
> docs: add deprecation warning for node v18

- docs/content/setup/docker.md
Docs -> Setup -> Docker
This PR updates the docs since they mentioned that we only support `amd64` architecture for docker images, when in fact we support `arm64` too since HD 1.9.8.
See 1.10.1 manifest for example: https://quay.io/repository/hedgedoc/hedgedoc/manifest/sha256:a65798c1735d086e0b0fdb57719eeb7d0143b044469ae26b95a46137ea7b1a79
fixes #5985
> docs(setup): list of supported docker architectures

- package.json
- turbo.json
turbo monorepo configuration
This PR changes the way turbo handles environment variables and is required due to a bug in turborepo.
It seems there's a bug in turborepo which results in turbo not passing through arbitrary environment variables despite `--env-mode=loose` being set. This config option resolves the problem by passing through all HedgeDoc environment variables prefixed by `HD_`. This somewhat also enhances stability and reproducability of builds since other env vars wouldn't interfere anymore.
The additional variable `CADDY_HOST` is required to make overriding the listening port in our Caddyfile work.
none
> fix(turborepo): passthrough HD_* env vars by config option

- docs/content/dev/openapi.yml
- docs/content/setup/docker.md
- docs/content/setup/manual-setup.md
- package.json
- public/docs/release-notes.md
internal version
This PR bumps the version of HedgeDoc to 1.10.2
> chore: bump version to 1.10.2

- frontend/src/components/login-page/new-user/new-user-card.tsx
frontend -> login -> new-user form
The new user form which is shown when a new user logs in via an external auth provider did not include the event.preventDefault() statement. This meant that on submitting the form there was a race-condition between the JS code sending the data to the API and the browser reloading the page. Chromium-based browsers seem to handle events before handling page navigation, and because the form event initiates a page navigation on a successful API response it worked. Firefox seems to call the event handler and the page navigation in parallel, resulting in a loop on the new user form.
see [matrix chat …
> fix(login): prevent default for new user confirmation form event

- docs/content/references/config/database.md
docs
This PR removes a dangling reference to mysql.
> docs(database): remove mention of mysql

- config.json.example
- docs/content/configuration.md
- lib/config/default.js
- lib/config/environment.js
- lib/web/auth/saml/index.js
auth -> saml
This PR adds two config options for more fine-grained requirement checks for SAML authentication. This is required since the change to `@node-saml/passport-saml` in the last release broke some SAML login setups with the new default values. So now, everyone can set these options as they like.
[Matrix chat](https://matrix.to/#/!oaRMJImPLfUnnXzwnN:shivering-isles.com/$zQ1XkiMhWkyHE9AY7VnLf0lqJ204mGYqJ-RRtpv4Foo?via=matrix.org&via=envs.net&via=mozilla.org)
> feat(saml): add config options to set required signings

- .github/actions/setup-node/action.yml
- .github/workflows/docs-netlify-deploy.yml
- .github/workflows/e2e-tests.yml
- .github/workflows/scorecard.yml
- frontend/package.json
- turbo.json
- yarn.lock
CI
It seems cypress installs its own binary under a different path than
the path where it later looks for it for running the tests. This
change adds proper versioned caching for the binary to avoid re-
downloads and configures the binary path accordingly.
> fix(ci): cache cypress binary correctly

- frontend/src/components/common/html-to-react/html-to-react.tsx
Frontend
The update to dompurify 3.2.4 (902abf72e65903d78ade7bb08c322b9648d07384) broke the import of dompurify.sanitize, which now fails with a TypeScript error (likely related to the introduction of type definitions in 3.2.0). Using the DOMPurify default export fixes the issue.
The issue is reproducible both with the local development server and with the published frontend container; without this fix, the frontend is completely broken.
> fix(frontend): fix dompurify.sanitize import

- docs/content/guides/reverse-proxy.md
Cloudflare has deprecated the Auto Minify feature as of August 2024, so this warning is no longer correct.
However while setting up HedgeDoc, I noticed another issue when I had Rocket Loader enabled, which also does it's own form of optimization which breaks HedgeDoc's CSP.
Documentation
This PR updates the documentation warning for using Cloudflare. 
As of August 2024, Cloudflare has deprecated and removed the Auto Minify feature
Link: https://community.cloudflare.com/t/deprecating-auto-minify/655677
However now we have a new Cloudflare product which may break your HedgeDoc instance, [Rocket Loader](https://developers.cloudflare.com/speed/optimization/content/rocket-loader). 
This PR updates the docs to address this.
- This …
> Updating Cloudflare warning in Reverse Proxy guide.

- docs/content/guides/auth/keycloak.md
- Documentation
- HedgeDoc 1.x
Several URLs patterns in the Keycloak guide for HedgeDoc 1 are (have become?) incorrect. For users, that makes the integration harder than it needs to be.
This patch updates the documentation page to reflect the current state of Keycloak.
> Fix Keycloak Integration Documentation

- public/js/index.js
Strings
This PR updates wording to match in a part that does not use the translation system.
> update non-localised strings

- renovate.json
Renovate dependency automation
Due to ongoing package fraud on npm, we decided to disable auto-merge of patch updates for dependencies
none
> Disable Renovate automerge
